feat(app): Improve applicants identification
betagouv/rdv-insertion pull request #1026
Opened 2023-05-04 03:42 UTC by aminedhobb

2023-05-10 13:08 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +    @applicant = process_input.matching_applicant || Applicant.new
ici on peut faire `@applicant = process_input.matching_applicant.presence || Applicant.new` pour éviter la ligne 93

2023-05-10 13:08 UTC, qblanc commented on app/services/applicants/validate.rb
il faudrait a minima ajouter un commentaire sur le modèle Applicant précisant que des validations sont runnées dans Applicants::Validate via Applicants::Save
ou alors faire un callback sur le modèle Applicant pour le déclencher depuis le modèle

2023-05-10 13:08 UTC, qblanc commented on app/models/applicant.rb
> +    errors.add(:base, "Il doit y avoir au moins un attribut permettant d'identifier la personne")
peut-être ajouter la liste des attributs attendus potentiellement comme identifier dans l'erreur ?

2023-05-10 13:08 UTC, qblanc commented on app/views/applicants/_create_or_update_choice.html.erb
> +    <% end %>
ce form devrait renvoyer vers l'update, ce qui enlèverait le souci de l'encrypted_id
de fait, n'importe quel agent peut déjà  update un beneficiaire, c'est juste que pour l'instant on le fait dans le create ; donc à mon sens c'est le authorize que l'on devrait changer (ou enlever) plutôt que de faire cette solution un peu complexe

2023-05-10 13:08 UTC, qblanc commented
je n'ai pas encore tout review mais voilà mes propositions pour essayer d'avoir un flow un peu moins complexe et plus lisible

2023-05-10 13:38 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +    @applicant = process_input.matching_applicant || Applicant.new
et rajouter sur la ligne suivante 
```
    # ici un comentaire expliquant dans quel cas cette ligne se déclenche (nir_matches? d'autres cas ?)
    # si je voulais vraiment être embettant je dirais que cette ligne ne devrait pas se trouver ici, 
    # mais "péter" dans le `save_applicant` (peut-être en interdisant l'update du NIR ?, 
    # ou en trouvant une autre solution) ; mais bon, on peut laisser ça là
    return render_errors(process_input.errors) unless process_input.success?
```
je trouve ça plus logique de render les errors dans l'action, et ça permet de simplifier la méthode `process_input`

2023-05-10 15:13 UTC, qblanc reviewed
C'est top merci Amine ! Je n'ai pas review les tests mais voilà mes retours 🚀

2023-05-10 15:13 UTC, qblanc commented on app/services/applicants/validate.rb
> +    end
on devrait peut-être prendre aussi les `inactives`, et si il y a un match proposer de rouvrir le dossier (ou le rouvrir automatiquement)

2023-05-10 15:13 UTC, qblanc commented on app/services/applicants/validate.rb
> +    end
est-ce qu'on est obligé d'utiliser un scope `applicants_from_same_departments` pour ce check ? Le `affiliation_number` est national non ?

2023-05-10 15:13 UTC, qblanc commented on app/services/applicants/validate.rb
> +    end
pourquoi faire ce check au sein du département ?

2023-05-10 15:13 UTC, qblanc commented on app/services/applicants/validate.rb
> +            applicant.first_name.split.first.downcase == @applicant.first_name.split.first.downcase
même remarque ici pour le scope `active`

2023-05-10 15:13 UTC, qblanc commented on app/views/file_configurations/update_for_all_configurations.turbo_stream.erb
> -<%= render_turbo_stream_flash_messages %>
pourquoi cette suppression ?

2023-05-10 15:23 UTC, qblanc commented
J'ai fait des commentaires là-dessus dans `validate` mais ça mériterait peut-être qu'on se pose la question pour `process_input` aussi : est-ce qu'on ne devrait pas toujours chercher sur tous les bénéfs, même les inactifs, et rouvrir les dossiers lorsqu'il y a un match (ça demande peut-être une EPIC à part entière, avec peut-être une réouverture avec des rdvs_contexts "vierges", et un accès à l'historique quelque part)

2023-05-10 15:38 UTC, Michaelvilleneuve commented on app/javascript/react/lib/createOrUpdateApplicant.js
> +  const humanDuplicateAttribute = FRENCH_DULPLICATE_ATTRIBUTES[duplicateAttribute];
Bonjour 👋 , je regarde juste ce qui se passe ici! Pour info votre variable a une faute, elle devrait être
```
FRENCH_DUPLICATE_ATTRIBUTES
```

2023-05-11 01:29 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> +      end
Oui c'est la réponse en fonction du format de la requête, c'est plutôt standard et homogène avec ce qu'on fait j'ai l'impression

2023-05-11 03:05 UTC, aminedhobb commented on app/services/applicants/validate.rb
Je n'ai pas mis ces validations dans le model parce que je pense que ces validations sont vraiment liés à de la logique métier spécifique et qui dépendent d'autres model, or je préfère n'avoir que les validations vraiment liées à la validité du format de la donnée . Les mettre dans le model rendrait notre appli beaucoup plus rigide IMO.

En d'autres termes: si on se place dans le model `applicant` sans avoir connaissances du reste de l'appli, 2 entrées qui partagent le même `department_internal_id` sont valides. Pour le mail et le tel cet exemple marche moins, mais on a tout de même des règles métiers spécifques avec la logique de conjoint. J'ai tout ms ici pour regrouper toute cette logique d'unicité au même endroit.

(Sans compter le fait que la personne pourra être mise à jour sur RDVS où ces règles ne sont pas mise en place. Que fait-on dans ce cas-là: est-ce qu'on assume le fait d'être async? On les remet à jour nous-même sur RDVS)

2023-05-11 03:07 UTC, aminedhobb commented on app/services/applicants/validate.rb
J'ai d'ailleurs fait la même chose avec le service `Invitations::Validate`. Après on peut peut-être trouver un autre nom pour différencier les 2 types de validations.
Par contre je préfère ne pas y faire référence dans le model `Applicant` vu qu'on ne l'appelle pas depuis ce mode.

2023-05-11 03:10 UTC, aminedhobb commented on app/services/applicants/save.rb
> +        validate_applicant!
Oui j'ai fait pour que les données soit enregistrées et donc bien formattées (uid, tel), mais on peut peut-être faire autrement. Peut-être que si le nom diffère aussi (commentaire plus haut) ce serait moins confusant, mais je suis d'accord que ça fait bizarre là, je vais revoir ça.

2023-05-11 03:17 UTC, aminedhobb commented on app/views/applicants/_create_or_update_choice.html.erb
> +    <% end %>
Je suis pas forcément d'accord sur le fait d'enlever l'autorisation: ça voudrait dire que n'importe qui pourrait mettre à jour et ajouter un bénéficiaire à son orga avec le simple id.

Ici on laisse la personne ajouter et mettre à jour parce qu'elle a déjà les coordonnées de la personne (via son nir o son email ou son tel etc.).

Mais je vais essayer de voir si je peux pas essayer de faire quelque chose sans amener cet `encrypted_id` qui m'embête un peu aussi...

2023-05-11 03:19 UTC, aminedhobb commented on app/javascript/react/lib/createOrUpdateApplicant.js
> +  const humanDuplicateAttribute = FRENCH_DULPLICATE_ATTRIBUTES[duplicateAttribute];
Bien vu merci pour la typo 🙏 😄 !!

2023-05-11 04:28 UTC, aminedhobb commented on .eslintrc.json
> +    "import/no-cycle": "off"
C'est parce que`createOrUpdateApplicant` appelle `handleApplicantCreation` et vice-versa. 
J'ai préféré les mettre dans des fichiers différents pour que ce soit plus lisible

2023-05-11 04:28 UTC, aminedhobb commented on app/controllers/applicants/searches_controller.rb
> +    end
Bien vu elle devrait l'être merci  🙌 !

2023-05-11 04:31 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> +  end
hmm je suis pas sûr de comprendre ta suggestion. Dans le cas ou le process fail, on renvoie soit le choix soit les erreurs.
Tu voulais dire que le service pourrait renvoyer un duplicate et ne pas échouer ?

2023-05-11 04:34 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> +    @applicant = process_input.matching_applicant || Applicant.new
> peut-être en interdisant l'update du NIR ?

Ce serait la seule solution que je vois pour faire ce que tu proposes, or je ne pense pas qu'on veuille faire ça

2023-05-11 04:35 UTC, aminedhobb commented on app/services/applicants/find_contact_duplicate.rb
> +    end
J'y ai pensé mais j'ai peur que ce soit moins lisible et c'est pas très coûteux de recopier ici

2023-05-11 04:37 UTC, aminedhobb commented on app/services/applicants/validate.rb
> +    end
Les "inactives" sont les personnes supprimées, je ne pense pas qu'il faille les considérer (de toutes façons le soft delete efface les données d'identifications mais je le mets au cas où)

2023-05-11 04:37 UTC, aminedhobb commented on app/services/applicants/validate.rb
> +    end
non

2023-05-11 04:38 UTC, aminedhobb commented on app/views/file_configurations/update_for_all_configurations.turbo_stream.erb
> -<%= render_turbo_stream_flash_messages %>
j'ai remarqué que l'action `configurations#update_for_all_configurations` n'existe pas

2023-05-11 04:40 UTC, aminedhobb commented
> C'est top merci Amine ! Je n'ai pas review les tests mais voilà mes retours 🚀

Merci @qblanc 🙌 , j'ai répondu à certains de tes commentaires, j'appliquerai tes suggestions demain !

2023-05-11 09:13 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +      end
oui oui c'est vraiment pas indispensable, c'est surtout parce que la méthode est assez longue que je dis ça mais on peut sans doute s'en passer

2023-05-11 10:35 UTC, qblanc commented on app/views/applicants/_create_or_update_choice.html.erb
> +    <% end %>
1) n'importe qui ça reste des agents loggés
2) avec ce qui est fait là, et comme tu le dis, il te suffit du prénom + téléphone ou prénom + mail pour modifier n'importe qui, ça reste pas très safe, donc que ce soit l'id ou pas... Je pense que si on met un papertrail pour garder trace de qui fait quelle modif on peut prendre ce "risque". Ce serait quand même plus clean de passer par un `update` imo

Sinon si on veut quand même passer par un `create` sans utiliser l`'encrypted_id`, j'avais pensé à un `attr_accessor``duplicate_applicant`

2023-05-11 10:37 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +    @applicant = process_input.matching_applicant || Applicant.new
🤷‍♂️ je sais pas, peut-être qu'on devrait. Mais bon faisons sans pour l'instant ; ma première suggestion tient toujours cependant

2023-05-11 10:37 UTC, qblanc commented on app/services/applicants/find_contact_duplicate.rb
> +    end
ok

2023-05-11 10:39 UTC, qblanc commented on app/views/file_configurations/update_for_all_configurations.turbo_stream.erb
> -<%= render_turbo_stream_flash_messages %>
ah bien vu

2023-05-11 10:41 UTC, qblanc commented on app/services/applicants/validate.rb
> +    end
ah yes j'ai confondu avec les `archived`. Ceci dit, est-ce qu'on ne devrait pas s'assurer qu'on désarchive les `applicants` quand ils sont save via l'action `create` ? Du coup ça devrait sans doute se passer dans `process_input` (dans le service ou éventuellement dans le controller si un `matching_applicant` est trouvé)

2023-05-11 12:46 UTC, qblanc commented on app/services/applicants/validate.rb
> +    end
ok je ne savais pas, merci pour l'info ! 🙏

2023-05-11 13:54 UTC, qblanc commented on app/services/applicants/validate.rb
> si on se place dans le model applicant sans avoir connaissances du reste de l'appli, 2 entrées qui partagent le même department_internal_id sont valides

en fait dans l'app, à part si l'on save un `applicant` depuis la db, il passera toujours par le service `Save` et donc par le service `Validate`. Je m'interroge donc sur la pertinence de garder cette flexibilité qui est un peu illusoire à mon sens. En tout cas, comme cette validation est run à chaque fois, je pense que ça ne coute pas grand chose de mettre un commentaire dans le modèle au niveau des validations pour préciser que d'autres validations sont run dans un service spécifique lorsque le modèle est save via le service save.

2023-05-25 16:02 UTC, aminedhobb commented
Après avoir vu avec Rémi il semblerait que l'affichage d'un choix spécifique au cas où on essaierait d'enregistrer une fiche avec un mail ou tel existant et un prénom différent ne soit pas un besoin remonté du terrain: du coup on attend d'avoir plus de recul après le déploiement des nouvelles règles d'identifications (#976 ) avant d'éventuellement incorporer de la complexité supplémentaire.

Cette PR contient cependant: 

* Les nouvelles règles de validations lorsqu'on enregistre une personne (via le formulaire ou l'upload de liste)
* Le fait de s'assurer que le nir match quand un matching se fait

Pour ce dernier point j'ai finalement utilisé 2 services `Applicants::FindOrInitialize` et `Applicants::Find` qui remplace `Applicants::ProcessInput`.

2023-05-25 16:03 UTC, aminedhobb commented on app/controllers/applicants/searches_controller.rb
> +    end
Done here: https://github.com/betagouv/rdv-insertion/pull/1026/commits/85ba26278fadc71fca71df9154ab16fe31c06d2a

2023-05-25 16:06 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> +    @applicant = process_input.matching_applicant || Applicant.new
Du coup la logique est similaire à ce qu'on avait avant, à part le fait que `FindOrIntialize` peut fail et que l'assignation des attributs se fait dedans (ce qui est iso avec la méthode d'activerecord `find_or_intialize_by` ) : https://github.com/betagouv/rdv-insertion/pull/1026/commits/fd2f5c8be7d96cf15d71608de7efd4191f22f8aa

2023-05-25 16:06 UTC, aminedhobb commented on app/policies/organisation_policy.rb
> +  end
Bien vu je les ai enlevé ici 👍 ! https://github.com/betagouv/rdv-insertion/pull/1026/commits/85ba26278fadc71fca71df9154ab16fe31c06d2a

2023-05-25 16:07 UTC, aminedhobb commented on app/services/applicants/validate.rb
> +    end
On pourra peut-être voir ça dans un second temps, sur la page upload (le cas principal) on propose déjà de rouvrir le dossier avant d'afficher le CTA

2023-06-01 13:53 UTC, qblanc requested changes
Top ! 2-3 petite remarques, dont une interrogation sur le nom d'un service, mais à part ça ça me paraît niquel 🔥 (je mets en `request changes` à cause de la coquille sur le `=`)

2023-06-01 13:53 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +    @find_or_initialize_applicant || Applicants::FindOrInitialize.call(
il manque un `=` ici je crois

2023-06-01 13:53 UTC, qblanc commented on app/controllers/applicants_controller.rb
> -    authorize @organisation, :add_applicant?
on enlève cette policy ici ?

2023-06-01 13:53 UTC, qblanc commented on app/services/applicants/find_or_initialize.rb
Est-ce qu'on ne devrait pas renommer `Applicants::FindOrInitialize` : au final, ce n'est plus tout à fait ce que fait ce service, et en plus cela permettrait de mieux comprendre la différence avec le service `Find`. On pourrait l'appeler par exemple `UpdateOrInitialize` : techniquement ce n'est pas tout à fait un `update`parce qu'il n'y a pas de `save` mais ça y ressemble et je ne suis pas sûr de trouver mieux. Peut-être `EditOrInitialize` ?

2023-06-01 13:53 UTC, qblanc commented on app/services/applicants/find_or_initialize.rb
> +      result.applicant = @matching_applicant || Applicant.new
Si on renomme la méthode `find_matching_applicant` en `matching_applicant`, que cette méthode mémoize le résultat, et que l'on appelle sur la ligne suivante `@matching_applicant` comme une méthode plutôt que comme une variable d'instance sur la ligne 10, est-ce qu'on peut pas supprimer la ligne 9 ?

2023-06-05 10:47 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> -    authorize @organisation, :add_applicant?
Oui je trouve qu'elle ne sert à rien, on vérifiait que l'agent appartenait à l'orga, or on utilise le `policy_scope` pour retrouver l'orga en question (= orgas de l'agent)

2023-06-05 10:48 UTC, aminedhobb commented on app/services/applicants/find_or_initialize.rb
Ok finalement j'ai laissé le mécanisme qu'il y avait avant et garder le nom du service

2023-06-05 10:48 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> +    @find_or_initialize_applicant || Applicants::FindOrInitialize.call(
Bien vu merci 🙌 !

2023-06-05 10:48 UTC, aminedhobb commented on app/services/applicants/find_or_initialize.rb
> +      result.applicant = @matching_applicant || Applicant.new
Yes j'avais fait ça quand il y avait encore qu'un seul service, done here: https://github.com/betagouv/rdv-insertion/pull/1026/commits/e0c244d82ede79dbf6f829122756b7db289bab2a

2023-06-07 12:54 UTC, qblanc submitted a review, later dismissed
A part un petit commentaire sur un test, ça me parait niquel ! 🚀

2023-06-13 12:25 UTC, qblanc submitted a review, later dismissed
📨

2023-06-26 11:28 UTC, qblanc commented
PI qu'est-ce qu'on attend pour déployer cette PR ?

2023-06-27 18:36 UTC, merged