Feat/Add warnings with errors for applicants file upload
betagouv/rdv-insertion pull request #110
Opened 2021-10-27 18:11 UTC by qblanc

closes issue #72 
Dans cette PR, j'ajoute la vérification du fichier des nouveaux bRSA lorsqu'il est uploadé par les agents.

Les solutions retenues visent à :
- Etre tolérant sur le nom de feuille : si le nom attendu n'est pas trouvé, on essaye avec la première
- Etre tolérant dans les noms de colonne : on "parametrize" dans un premier temps pour éviter de bloquer pour des erreurs de formatage, puis on vérifie que les informations nécessaires sont présentes.
- Délivrer des messages d'erreurs clairs et intelligibles pour les agents : le if de la ligne 33 pourrait être évité, mais il permet d'avoir un objet `human_column_names` plus facile à maintenir dans configuration (sinon, ça oblige à avoir les values de `column_names` en keys de `human_column_names`, et quand il faut faire une modif des deux, c'est moins intuitif)
![image](https://user-images.githubusercontent.com/46218316/139122204-a5cae18b-c049-4924-bb8c-9f1a1b8324e4.png)

Ajouts notables : 
- une colonne `human_column_names` à la table `configuration` (penser à modifier les tables existantes en prod après déploiement). Sans cette colonne, impossible de signaler aux agents les valeurs attendues sous forme "humaine"
- une fonction `getKeyByValue()` pour récupérer les clés en partant de la valeur (nécessaire pour le if de la ligne 33 détaillé ci-dessus)
- correction d'un micro-bug css qui traînait

La traduction des erreurs venant des calls API à RDV-Solidarités sera traitée dans une PR séparée (j'ai créé une issue) : la logique n'est pas la même et il sera plus simple de le faire une fois la PR d'ajout des boutons d'invitation mail sur la page new sera mergée.

2021-11-02 11:02 UTC, aminedhobb requested changes
Cette feature va nous être utile 🚒  !
Je t'ai fait quelques retours sur l'implémentation LMKWYT.

2021-11-02 11:09 UTC, qblanc commented on app/javascript/react/pages/ApplicantsUpload.jsx
> +    const expectedColumnNames = Object.values(columnNames);
Ce sont déjà que les colonnes strictement nécessaires. Cela reprend les values de `columnNames`, qui sont les colonnes définies comme indispensables dans la config du département

2021-11-02 11:15 UTC, qblanc commented on db/migrate/20211027114843_add_human_column_names_to_configuration.rb
> +    add_column :configurations, :human_column_names, :json
Le souci, c'est qu'il faut pouvoir récupérer individuellement les noms humains des colonnes manquantes si une colonne pose problème. Je n'ai pas trouvé d'autre solution que d'avoir une table de correspondance comme celle-là (en soit, avoir un json plutôt qu'un array de valeur en db ne me parait pas beaucoup plus compliqué ; la complexité rajoutée est plus sur la ligne 33, c'est pour ça que j'avais essayer d'expliquer pourquoi j'avais laissé cette complexité).

Avec ta solution, je ne vois pas comment on peut remonter au nom humain une fois qu'il a été paramétrizé, si tu vois ce que je veux dire.

2021-11-02 13:30 UTC, aminedhobb commented on app/javascript/react/pages/ApplicantsUpload.jsx
> +    const expectedColumnNames = Object.values(columnNames);
Non elles sont pas toutes indispensables justement, cf. le `custom_id` qui est l'id IODAS qu'on peut mettre ou non.

2021-11-02 13:38 UTC, aminedhobb commented on db/migrate/20211027114843_add_human_column_names_to_configuration.rb
> +    add_column :configurations, :human_column_names, :json
Oui on a besoin du nom humain maintenant c'est pour ça que ce que je proposais c'est de n'enregistrer **que** les noms humains, et les paramétriser nous-mêmes à la volé.  
On aurait 
```
const columnNames = configuration.column_names;
const parameterizedColumnNames  =  parameterizeObjectValues(columnNames)
```

Au final tu récupèreras les noms humains avec `configuration.column_names[missingAttribute]`.

2021-11-02 13:40 UTC, aminedhobb requested changes
J'ai répondu à tes commentaires directement !

2021-11-02 14:19 UTC, qblanc commented on app/javascript/react/pages/ApplicantsUpload.jsx
> +    const expectedColumnNames = Object.values(columnNames);
ah je n'avais pas cette colonne dans mon environnement de dev.

2021-11-03 09:45 UTC, aminedhobb commented on app/javascript/react/pages/ApplicantsUpload.jsx
> +
c'est un nitpick mais tu pourrais instancier `requiredColumns` ici vu que tu ne l'utilises qu'ici.

2021-11-03 09:58 UTC, aminedhobb commented on app/javascript/react/pages/ApplicantsUpload.jsx
> +    }
C'est pas clair dans les noms de variables que `missingColumns` contient les noms de colonnes manquantes en parameterized et `missingColumnNames` les noms manquants humains.
Je te propose soit de renommer `missingColumns` en `missingColumnNames` et `missingColumnName(s)` en `missingColumnName(s)Human` soit de  garder `missingColumnName(s)` et de préfixer tous les autres par `parameterized` (ce qui est peut-être + consistant avec le reste).

2021-11-04 16:58 UTC, aminedhobb approved these changes
Merci pour les changements @qblanc 🙌  !
Faudra pas qu'on oublie d'updater les champs `column_names` existant quand on déploiera !

2021-11-08 10:48 UTC, merged