Feat/Show page
betagouv/rdv-insertion pull request #116
Opened 2021-11-04 15:10 UTC by qblanc

closes issue #52  
Dans cette PR, j'ajoute une page show pour consulter les informations détaillées des applicants, et permettre aux agents de les (ré)inviter si nécessaire. Un lien pour consulter facilement la fiche RDV-Solidarités de l'usager a également été ajouté. Enfin, la palette de couleur utilisée a été harmonisée pour plus de cohérence.

Au niveau technique, un composant React `ApplicantTracker.jsx` a été créé pour la partie basse de la page show. Elle réutilise la logique utilisée pour les boutons d'invitation de `Applicant.jsx`, et pour pour garder la même logique d'alertes sur les erreurs, les fonctions `handleApplicantCreation` et `handleApplicantInvitation` ont été extraites dans des fichiers séparés. (Au final, `handleApplicantCreation` n'est pas utilisé par `ApplicantTracker`, mais à la base, j'avais mis un bouton "Créer compte" sur la page show. Je me suis finalement dit qu'une page show ne devenait disponible qu'une fois le compte créé, donc je l'ai enlevé, mais si tu penses qu'il y a des cas où l'utilisateur peut exister sur rdv-insertion sans être présent sur rdv-solidarités, on peut le remettre)

2021-11-05 15:18 UTC, aminedhobb requested changes
Merci @qblanc pour cette PR, la page est vraiment belle tu es un vrai artiste 👨‍🎨 !

Je t'ai fait une première salve de retour, tu me diras ce que tu en penses.

Ça me va d'avoir un component React dans la page (je pensais au début que c'était toute la page que tu voulais faire avec du React :) ).
Par contre je me demande si c'est pertinent d'avoir dans ce component les informations liées aux RDVs et au statut, puisqu'à priori ceux-ci ne changeront pas avec les actions effectués (à part pour le changement de statut "non invité" -> "invitation en attente").
Je pense aussi qu'il faut faire attention à ne pas trop inonder les CDs de couleur ça pourrait être confusant.

Sinon ça m'a l'air plutôt bon !

2021-11-05 15:18 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  }
Ça va pas ce que tu fais ici, tu changes la classe CSS alors que le statut n'est pas updaté: 

![image](https://user-images.githubusercontent.com/7602809/140531520-c5533765-04b2-4e19-8f62-1de2f67ca50e.png)

2021-11-05 15:18 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  }
Je suis pas sûr qu'ill faille mettre des couleurs sur les dates de RDVs, le statut suffit je pense. Un RDV n'est pas + ou - bon en fonction de la date, et ça ramène potentiellement trop de couleurs.

2021-11-05 15:18 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +    (action === "smsInvitation") ? format = "sms" : format = "email"
Je pense qu'écrire `const format =  (action === "smsInvitation") ? "sms" : "email"` serait plus lisible

2021-11-05 15:18 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +              disabled={isLoading.smsInvitation || (rdvs.length > 0 && !hasActionRequired) || !applicant.phone_number_formatted}
Pourquoi le `!hasActionRequired` ? Est-ce qu'on considérerait pas qu'à partir du moment où la personne a un RDV, on ne la réinviterait pas ? 
On pourrait éventuellement mettre en place une relance mais ça me semble bizarre d'envoyer une invit comme celle que l'on a a qqun qui a pris un RDV ou été convoqué.

2021-11-05 15:18 UTC, aminedhobb commented on app/policies/applicant_policy.rb
> +    (pundit_user.organisation_ids & record.organisations.pluck(:rdv_solidarites_organisation_id)).empty?
Cette condition n'est pas bonne, tu compares des ids d'orga sur RDVI à des ids de RDV-Solidarités 😬 .

2021-11-05 16:08 UTC, qblanc commented on app/helpers/applicants_helper.rb
> +  def display_notice(applicant)
J'ai opté pour `display_time_notice`, expiration me semble un peu fort

2021-11-05 16:32 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +  }
Ok, j'ai enlevé tous les warning et danger. J'ai juste laissé le success pour le `rdv_pending`, car dans ce cas-là le statut n'a pas de couleur : cela permet de signaler à l'agent que le rendez-vous a bien été pris.

2021-11-05 16:50 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +              disabled={isLoading.smsInvitation || (rdvs.length > 0 && !hasActionRequired) || !applicant.phone_number_formatted}
Oui, c'était dans le cas où le rendez-vous était annulé ou non honoré.  Je pense qu'effectivement il faudra prévoir une relance spécifique dans ce cas-là ; en attendant, je m'étais dit que le texto d'invitation pouvait faire l'affaire, car au final il ne fait que parler de l'obligation d'accompagnement et renvoie vers le choix de rendez-vous. Mais si tu penses qu'il vaut mieux ne pas offrir de possibilité de relance on peut changer cette condition.

2021-11-05 19:01 UTC, qblanc commented
J'ai pris en compte tes différentes remarques. J'ai essayé de mettre un minimum de couleur, juste de quoi orienter la lecture des agents.

Pour l'opportunité de mettre la partie rdv/statut en React, il y a deux raisons : la mise à jour du statut en cas d'invitation, mais surtout les deux blocs font partie d'une même flexbox, et React rajoutant un niveau de div automatiquement, sortir la deuxième moitié rend le front foireux.

J'ai également rajouté un test pour la page show, et pour traiter l'issue #102, j'ai rajouté un bouton "Clôturer le dossier" et un statut `resolved`. Je ne sais pas si l'approche retenue pour ce bouton est la bonne (nouvelle route).

Je rajoute aussi une capture d'écran pour @guillett qui nous fait des coucous avec ses emojis.
![image](https://user-images.githubusercontent.com/46218316/140559415-867bb437-946d-4ab4-b8be-55bdb6d9ca84.png)

2021-11-08 15:07 UTC, aminedhobb requested changes
Je t'ai fait qq autres retours @qblanc . 
Aussi quand j'ai fait des  tests fonctionnels j'ai remarqué que des nouveaux records d'invitations étaient créés pour le même format, ça devrait pas être le cas normalement, si tu peux essaye de regarder si t'arrives à reproduire cette erreur.

2021-11-08 15:07 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +              disabled={isLoading.emailInvitation || (rdvs.length > 0 && !hasActionRequired) ||
> Oui, c'était dans le cas où le rendez-vous était annulé ou non honoré. Je pense qu'effectivement il faudra prévoir une relance spécifique dans ce cas-là ; en attendant, je m'étais dit que le texto d'invitation pouvait faire l'affaire, car au final il ne fait que parler de l'obligation d'accompagnement et renvoie vers le choix de rendez-vous. Mais si tu penses qu'il vaut mieux ne pas offrir de possibilité de relance on peut changer cette condition.

Je pense qu'il faut pas permettre d'inviter qqun qui a un RDV pour l'instant, je suis même pas sûr que le flow marche bien dans ce cas-là.

2021-11-08 15:07 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +              onClick={() => handleClick("smsInvitation")}
Petit nitpick mais pourquoi au lieu d'utiliser toujours `handleClick` avec des conditions chaque boutton n'aurait pas sa propre méthode ? (dans `Applicant.jsx` c'est pareil).

2021-11-08 15:07 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +      }
L'indentation n'est pas bonne ici

2021-11-08 15:07 UTC, aminedhobb commented on app/models/applicant.rb
> +    invitations.where(format: "sms").select(&:sent_at).max_by(&:sent_at)
Il faut utiliser du ruby ici avec `select` et non pas `where`, sinon on a une requête supplémentaire pour chaque demandeur dans la page index (N+1 query)

2021-11-08 15:07 UTC, aminedhobb commented on app/models/applicant.rb
> +    invitations.where(format: "email").select(&:sent_at).max_by(&:sent_at)
Pareil ici

2021-11-08 18:55 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const baseCssClass = "col-4 d-flex align-items-center justify-content-center"
Pourquoi faudrait-il mettre l'espace dans la balise plutôt que dans la méthode ? En plaçant les espaces au niveau des balises, on laisse un espace dans la balise lorsque méthode ne retourne rien (ça ne fait pas bugger, mais c'est moche).

2021-11-08 19:01 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +  }
Je ne met pas la couleur sur le statut, pour garder la logique de ne mettre du vert sur le statut que quand le dossier est résolu. Je met du vert sur les rendez-vous pour signifier que la prise de rendez-vous est résolue. Et c'est pareil pour la remarque suivante par rapport au vert sur les invitations time out : l'idée, c'est d'utiliser le vert pour montrer visuellement à l'agent quelle phase du processus a été validée, ou bloque. Si on ne met rien on crée potentiellement de l'incertitude, et on le pousse à agir alors qu'il n'a pas besoin. Comme tu m'as demandé, j'ai essayé de limiter au maximum l'utilisation de la couleur, mais là ça me parait cohérent : elle n'est utilisée pour chaque page show que une fois, sur une étape.

2021-11-08 19:01 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +    return ""
même explication que la remarque précédente

2021-11-08 19:02 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +    return ""
mais si on a des remontées comme quoi c'est pas clair, on peut évidemment changer

2021-11-08 19:27 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +              onClick={() => handleClick("smsInvitation")}
Parce que c'est plus dry ? au moins 80% des méthodes seraient identiques

2021-11-09 15:00 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  }
Déso mais je trouve toujours pas ça hyper cohérent 😬 . 
Autant sur l'exemple du dessous ok je peux comprendre, on flag le processus d'invitation. Mais là le processus de rdv est déjà flagé, y a pas à flaguer "la prise de rdv", qui plus est sur une date de RDV.
On débat beaucoup pour quelque chose qui n'a peut-être pas tant d'impact, mais tu penses  pas que sans rentrer dans le  fond du sujet ajouter du vert sur les dates ça risque d'être confondu avec le fait que le RDV est  honoré ?

2021-11-09 15:00 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +    return ""
Ok ça me va de laisser comme ça pour l'instant

2021-11-09 15:03 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +              onClick={() => handleClick("smsInvitation")}
Non mais + lisible avec deux méthodes différentes, parce que là on se retrouve avec beaucoup de `if...` dans la méthode `handleClick`. Mais c'est un détail, ça me va de laisser la méthode telle qu'elle est.

2021-11-09 15:06 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const baseCssClass = "col-4 d-flex align-items-center justify-content-center"
Parce que  la méthode a pour but de computer la classe CSS pour la  backgroud couleur en fonction du statut. 
Elle n'a pas à savoir où elle va être utilisée et du coup la structure de la balise html où elle va être mise en ajoutant en espace.
Ici c'est peu probable qu'elle soit réutilisée autre part mais c'est toujours bien de garder les bonnes pratiques. C'est pour ça aussi que le nom doit préciser exactement ce  que fait cette méthode  (trouver la classe pour le **background uniquement**)

2021-11-09 15:25 UTC, aminedhobb reviewed
Merci pour les changements @qblanc !
J'ai resolve presque tous mes commentaires, j'en ai juste  laisser 2 sur lesquels on pourrait discuter.
Par contre je me suis rendu compte d'un truc dont je crois que je t'avais parlé à l'oral :  
On devrait prendre en compte la configuration pour afficher ou pas les deux types d'invitations avec leurs actions sur la page.

Je pense qu'on devrait  être bon après ça 🔥

2021-11-09 15:25 UTC, aminedhobb commented on app/models/concerns/has_status_concern.rb
> +    return if status == "resolved"
good call 👍

2021-11-09 15:25 UTC, aminedhobb commented on app/policies/applicant_policy.rb
> +    (pundit_user.organisation_ids & record.organisations.pluck(:id)).any?
nice 👍

2021-11-09 15:25 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  }
Si tu préfères on peut demander un avis extérieur pour essayer d'appréhender un peu plus un point de vue utilisateur

2021-11-09 15:31 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const baseCssClass = "col-4 d-flex align-items-center justify-content-center"
Oui mais du coup ça laisse un espace vide au bout de la classe css quand on rajoute aucune couleur et ça m'énerve 😂
Perso je préfère un résultat clean dans le html livré que dans le code que seul nous voyons. Mais bon c'est vraiment pas important du tout comme débat donc si tu y tiens tant je le change :)

2021-11-09 15:49 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const baseCssClass = "col-4 d-flex align-items-center justify-content-center"
Oui pardon l'idée c'était pas du tout de laisser un espace ça va pas  non plus.  
Pour être vraiment clean on pourrait faire : 
```
const cssClassForInvitationDate = (format) => {
    const bgColorClass = backgroundColorClassForInvitationDate(format);
    return "col-4 py-2" + (bgColorClass.length === 0 ? "" : ` ${bgColorClass}`);
  };

  const backgroundColorClassForInvitationDate = (format) => {
    let lastInvitationDate = null;
    if (format === "sms") {
      lastInvitationDate = lastSmsInvitationSentAt;
    } else if (format === "email") {
      lastInvitationDate = lastEmailInvitationSentAt;
    }

    if (rdvs.length === 0 && applicantStatus !== "resolved") {
      if (lastInvitationDate && isOutOfTime) {
        return "bg-warning";
      }
      if (lastInvitationDate) {
        return "bg-success";
      }
      if (!lastSmsInvitationSentAt && !lastEmailInvitationSentAt) {
        return "bg-danger";
      }
    }
    return "";
  };
```

2021-11-09 15:57 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const baseCssClass = "col-4 d-flex align-items-center justify-content-center"
top ! Ca ressemble beaucoup à ce que j'avais essayé de faire avec `baseClass`, mais ça me va.

2021-11-09 16:09 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +  }
yes carrément, du coup on laisse comme ça en attendant ou on l'enlève ? Ce serait dommage ne pas déployer à cause de ça.

2021-11-09 16:10 UTC, qblanc commented
Ok j'ai ajouté l'affichage conditionnel des invitations sms et mail. On en avait parlé pour la page Upload, mais je n'avais pas pensé le faire pour celle-ci, indeed. Pour les record d'invitation ça ne m'en créé pas de nouveaux perso, donc je n'ai pas pu travailler sur cette erreur.

2021-11-09 16:20 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const baseCssClass = "col-4 d-flex align-items-center justify-content-center"
Oui c'est vrai ^^

2021-11-09 16:36 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  }
Si tu me demandes à moi je dirais plutôt de l'enlever :).

2021-11-09 16:43 UTC, aminedhobb reviewed
Ça marche nickel 👍 .
J'ai toujours le même souci où la date d'envoi d'email s'affiche sur la page index, c'est lié à la PR précédente que contient celle-ci?

2021-11-09 16:43 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const shouldDisplaySmsInvitation = (invitationFormat === "sms" || invitationFormat === "sms_and_email")
ça me gêne un peu d'avoir `invitationFormat` alors qu'on utilises beaucoup les formats dans les méthodes du dessous qui représentent autre chose, mais ça vient aussi du fait que c'est déjà mal nommé au niveau de la configuration...

2021-11-09 16:49 UTC, qblanc commented
What do you mean ? Moi ça ressemble à ça l'index
![image](https://user-images.githubusercontent.com/46218316/140968025-c519b8f1-e128-4016-9aa3-f9a1538dc73b.png)

2021-11-09 16:51 UTC, qblanc commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const shouldDisplaySmsInvitation = (invitationFormat === "sms" || invitationFormat === "sms_and_email")
tu préfères que je l'appelle `invitationConfiguration` par exemple ?

2021-11-09 17:02 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  const shouldDisplaySmsInvitation = (invitationFormat === "sms" || invitationFormat === "sms_and_email")
c'est mieux non ?

2021-11-09 18:23 UTC, aminedhobb approved these changes
Merci pour les changements et la patience @qblanc 🙇 🚀 !

2021-11-09 18:23 UTC, aminedhobb commented on app/javascript/react/components/ApplicantTracker.jsx
> +  showEmailInvitation,
top 👍

2021-11-10 09:36 UTC, aminedhobb approved these changes

2021-11-10 09:37 UTC, merged