fix(jobs): avoid race condition for rdvs/participations
betagouv/rdv-insertion pull request #1235
Opened 2023-07-27 11:06 UTC by qblanc

closes #1036 

Cette PR vise à résoudre les erreurs Sentry remontées par rapport au `process_rdv_job` et documentées dans l'issue.
Concrètement, les participations sont crées _via_ les rdvs et des nested_attributes. Je rajoute ici un `reject_if` afin que ces nested_attributes ne soient plus pris en compte dans les cas où le `process_rdv_job` n'avait pas récupéré de participation mais que cette participation est existante au moment où est process le service `upsert_record`.

2023-07-27 12:05 UTC, aminedhobb reviewed
Trop bien merci @qblanc 🙏 ! 
Vu que le process des webhooks de rdv/participations est vraiment important, on peut peut-être rajouter qq tests au niveau du model `rdv` pour voir que le comportement souhaité s'applique bien (création si id nul et participation non créée, rejet si id nul et participation créé, update si id non nul et participation créée, voire destroy si  id non nul `_destroy` est passé) ?

2023-07-28 19:20 UTC, Michaelvilleneuve reviewed
👍 mérite peut-être juste un petit TU ?

2023-08-01 12:21 UTC, aminedhobb reviewed
Merci pour les tests @qblanc 👍 !
Pourquoi avoir changé l'implémentation de la méthode `participation_already_created?` ?
J'ai l'impression que tu essayes de répliquer le fonctionnement natif de `accepts_nested_attributes_for` dans cette méthode qui est censée seulement filtrer certains attributes.

2023-08-01 12:54 UTC, qblanc commented
mmm j'ai du modifier parce que ça ne marchait pas tout à fait ce que j'avais fait ; j'ai peut-être trop complexifié au passage. J'ai essayé de re-simplifier, je te laisse regarder.

2023-08-01 13:16 UTC, Michaelvilleneuve commented on spec/models/rdv_spec.rb
> +      end
```ruby
      let!(:rdv) { create(:rdv, participations_attributes: participation_attributes) }
```
J'ai peut-être loupé un truc mais ceci devrait être suffisant, plus besoin du before du coup et ça évitera une requête 👍

2023-08-01 13:18 UTC, Michaelvilleneuve approved these changes

2023-08-01 13:22 UTC, aminedhobb requested changes
Je change juste le statut de la review

2023-08-01 13:31 UTC, aminedhobb commented on app/models/rdv.rb
> +      self.participations = [participation]
On pourrait voir quels tests qui ne passaient pas avec l'implémentation initiale et voir d'où vient le problème

2023-08-01 14:28 UTC, qblanc commented
comme ça ça te convient ?

2023-08-01 16:17 UTC, aminedhobb reviewed
J'ai laissé une possible explication sur pourquoi les tests ne passaient pas avec l'implem initiale et une mini suggestion mais LGTM 👍

2023-08-01 16:17 UTC, aminedhobb commented on app/models/rdv.rb
> +      Participation.find_by(
ça marche 👍 , mais une participation est toujours lié qu'à un seul rdv, donc si une participation existe elle est forcément lié à ce rdv en question (c'est pour ça que la première implémentation suffit normalement).
Je pense que le problème dans les tests venait du fait que la participation n'était pas bien lié au rdv au moment de sa création. Si tu les crées en même temps (`let(:rdv) { create(:rdv, participations: [create(:participation, ...)] }) ça devrait marcher.

2023-08-01 16:17 UTC, aminedhobb commented on app/models/rdv.rb
> +  def participation_already_created?(participation_attributes)
nitpick: J'y avais pas pensé mais `new_participation_already_created?` est peut-être plus adapté ?

2023-08-22 12:07 UTC, aminedhobb approved these changes
Merci pour les changements 🙇 !

2023-08-22 12:12 UTC, merged