wip: allow updating rdv status
betagouv/rdv-insertion pull request #1347
Opened 2023-09-08 16:11 UTC by Michaelvilleneuve

2023-09-11 13:10 UTC, aminedhobb reviewed
Je t'ai laissé qq commentaires mais les bases sont tops 👍 !

2023-09-11 13:10 UTC, aminedhobb commented on app/models/concerns/rdv_participation_status.rb
> -    enum status: { unknown: 0, waiting: 1, seen: 2, excused: 3, revoked: 4, noshow: 5 }
Je pense pas que ce soit une bonne idée de l'enlever totalement tant que c'est encore présent sur RDVS.
Tant que RDVS le permet, on aurait des erreurs si une participation était mise das cet été sur RDVS

2023-09-11 13:10 UTC, aminedhobb commented on app/views/rdvs/_rdv_form.html.erb
> +document.addEventListener("turbo:submit-end", function() {
Ce serait mieux par consistence de placer cette action dans un controller stimulus

2023-09-11 13:10 UTC, aminedhobb commented on app/controllers/rdvs_controller.rb
> +    RdvSolidaritesApi::UpdateRdv.call(
Il faudrait gérer les cas d'erreurs tout de même et afficher l'erreur clairement lorsque l'update ne se fait pas

2023-09-11 13:10 UTC, aminedhobb commented on app/views/rdv_contexts/_rdv_context.html.erb
> +                <% end %>
N'y a-t-il pas moyen de mettre tout le rdv dans une frame et de mettre à jour la frame depuis le controller avec le record mis  à jour, plutôt que d'utiliser `Turbo.visit` ?

2023-09-11 13:51 UTC, Michaelvilleneuve commented on app/views/rdv_contexts/_rdv_context.html.erb
> +                <% end %>
J'ai retravaillé ma PR en utilisant turbo de manière plus classique, dis moi ce que tu en penses :)

2023-09-11 13:51 UTC, Michaelvilleneuve commented on app/views/rdvs/_rdv_form.html.erb
> +document.addEventListener("turbo:submit-end", function() {
Dis moi ce que tu penses du dernier commit

2023-09-11 13:54 UTC, Michaelvilleneuve commented on app/models/concerns/rdv_participation_status.rb
> -    enum status: { unknown: 0, waiting: 1, seen: 2, excused: 3, revoked: 4, noshow: 5 }
Non justement, ce statut n'existe pas côté RDVS :/

2023-09-11 13:56 UTC, Michaelvilleneuve commented on app/javascript/stylesheets/application.scss
> +}
🤢 si vous avez une meilleure idée. 
Le problème initial est que les `turbo-frame-tag` de stimulus ne fonctionnent pas quand on wrap un `<td>` car le `<td>` est trop stricte (le browser réécrit le DOM si jamais on lui envoi un élement qui wrap un TD.....)

Ceci fait qu'on est obligé de wrap uniquement les children, et en wrappant le children, on perdait le height 100% offert par le TD pour la classe mettant un bg

2023-09-11 14:13 UTC, Michaelvilleneuve commented on app/controllers/rdvs_controller.rb
> +    RdvSolidaritesApi::UpdateRdv.call(
Oui oui bien sur ça fait parti des trucs que je vais rajouter mais vu que j'étais pas sur du fonctionnel (confusion rdv_context / rdv / etc) je voulais attendre d'être sur

2023-09-12 08:59 UTC, aminedhobb reviewed
Merci @Michaelvilleneuve 🙏 !! 
Je t'ai laissé quelques suggestions sur l'implémentation.
Concernant l'UX je me demande si c'est très intuitif de cliquer sur le statut du rdv. Je me demande si une liste déroulante comme ce qui se fait sur RDVS ne serait pas mieux, à voir peut-être 🤷‍♂️ .

2023-09-12 08:59 UTC, aminedhobb commented on app/models/concerns/rdv_participation_status.rb
> -    enum status: { unknown: 0, waiting: 1, seen: 2, excused: 3, revoked: 4, noshow: 5 }
Ah mince on était pas à jour 😬 . Merci de l'avoir enlevé 👍

2023-09-12 08:59 UTC, aminedhobb commented on app/controllers/participations_controller.rb
> +      @participation.rdv_context.set_status
Par mesure de précaution j'aurais plutôt tendance à englober tout ça dans une transaction, et par consistance avec ce qui est fait ailleurs j'aurais plutôt tendance à englober ça dans un service (comme tu as fait dans ton premier commit).

2023-09-12 08:59 UTC, aminedhobb commented on app/views/participations/update.turbo_stream.erb
> +<% if flash[:error] %>
Je comprends ce qui a voulu été faire mais je trouve ça bizarre de se baser sur un élément de l'UI pour cette condition.
On a plutôt tendance à instancier une variable d'instance `@success` (liée généralement au succès d'un service) pour nos conditions ici.

2023-09-12 08:59 UTC, aminedhobb commented on app/views/participations/update.turbo_stream.erb
> +  <% @participation.rdv_context.motif_category.configurations.each do |configuration| %>
Tu n'as pas besoin de mettre à jour tous les contextes ici. 
Il suffit que tu englobes la partial `rdv_context_status_cell_tag` avec un élément  dépendant de l'id du `rdv_context`.
Du coup ici il suffirait de faire: 
```
<%= turbo_stream.replace "rdv_context_status_tag_#{@participation.rdv_context_id}", partial: "rdv_contexts/rdv_context_status_cell_tag", locals: { rdv_context: @participation.rdv_context, configuration: current_configuration } %>
```

La configuration tu peux la récupérer (peut-être l'instancier dans le controller ou une méthode `current_configuration`dans le model `participation` ?) en faisant quelque chose comme: 
```ruby
@participation.organisation.configurations.find { |configuration| configuration.motif_category == @participation.motif_category }
```

2023-09-12 08:59 UTC, aminedhobb commented on spec/features/agent_can_create_a_rdv_context_spec.rb
> +      context "when applicant has rdvs" do
Je me demande si c'est le bon fichier pour ajouter ces tests (en tous cas au vu du titre du fichier c'est pas évident de deviner). 
Peut-être qu'il vaut mieux utiliser un nouveau fichier sinon

2023-09-12 10:00 UTC, Michaelvilleneuve commented on app/controllers/participations_controller.rb
> +      @participation.rdv_context.set_status
Effectivement j'avais fait ça dans mon premier commit mais je trouvais que cet englobage n'ajoutait pas suffisamment de valeur et que la gymnastique mentale imposée par l'abstraction ne valait pas gain associé. 

Ok je repasse là dessus pour être cohérent avec le reste, mais je suis pas 100% convaincu de la valeur ajoutée 🤔 

Concernant la transaction oui pourquoi pas mais de toute façon si le call à l'API lève une erreur on ne ferait pas l'update sur le status donc IMO elle n'apporte pas grand chose non plus 🤷‍♂️

2023-09-12 10:04 UTC, Michaelvilleneuve commented on app/views/participations/update.turbo_stream.erb
> +  <% @participation.rdv_context.motif_category.configurations.each do |configuration| %>
Ahhh oui tu as raison c'est beaucoup mieux, je savais qu'il y avait un code smell ici mais je voyais pas ce que je pouvais faire de mieux 🙇

2023-09-12 11:44 UTC, aminedhobb commented on app/controllers/participations_controller.rb
> +      @participation.rdv_context.set_status
L'implémentation aurait pu rester comme ça sans problème 👍 . Mais au-delà de la consistence, je pense que le principal intérêt d'englober ça dans un service et de pouvoir réutiliser cette logique. C'est fort probable qu'on ait un besoin de mettre un jour une participation via une autre action ou même via la console, et dans ce cas ce sera pratique de réutiliser un service qui gère déjà pour nous la chaine d'instruction (transaction, appel api, update  de statut etc.). C'est d'ailleurs le principal cas d'usage des services et du command pattern selon moi.
J'ai pas l'impression que l'utilisation de ces services soit très complexe, mais je veux bien te croire parce que tu as un oeil plus neuf que moi sur la codebase. Après les différentes abstractions se justifient selon moi par le fait qu'elles ont toutes une tache précise et qu'elles peuvent être réutilisées chacune indépendamment. 
Merci de soulever le débat en tous cas, il se peut que les avis divergent sur cette question :) !

2023-09-12 13:20 UTC, Michaelvilleneuve commented on app/controllers/participations_controller.rb
> +      @participation.rdv_context.set_status
Alors effectivement c'est la première fois que je rentrais dans cette stack d'appel donc j'ai mis un moment à comprendre le rôle qui incombe à chacune des couches de la pile. 
Mais je vois bien ce que tu veux dire et une fois que j'aurais vu plus d'usage ça me paraitra problablement plus logique de l'avoir 👍 .
Quoi qu'il en soit faut savoir que c'est quand même le genre d'enchainement qui ne facilitent pas la lecture quand on ne connait pas le projet. 

Faut donc arbitrer entre "avoir tout en procédural dans un seul fichier", et l'inverse qui serait "abstraire la moindre ligne dans une classe pour permettre la réutilisabilité". 

Globalement le curseur ne semble pas trop mal placé même si là il semblait un peu plus envers la seconde. 
Il faut aussi prendre en compte le fait qu'on ne recrute pas tous les jours donc ça me semble OK d'avoir certaines knowledge de la codebase pour lesquels il faut un peu d'effort pour les démeler

2023-09-12 21:07 UTC, aminedhobb commented on app/controllers/participations_controller.rb
> +      @participation.rdv_context.set_status
> Faut donc arbitrer entre "avoir tout en procédural dans un seul fichier", et l'inverse qui serait "abstraire la moindre ligne dans une classe pour permettre la réutilisabilité".

🤝 🤝

2023-09-13 08:00 UTC, Holist commented on app/controllers/participations_controller.rb
> +    flash.now[:error] = "Impossible de changer le statut de ce rendez-vous." if @success
`unless @success` non ?

2023-09-13 08:05 UTC, Michaelvilleneuve commented on app/controllers/participations_controller.rb
> +    flash.now[:error] = "Impossible de changer le statut de ce rendez-vous." if @success
Bien vu merci ! Je vais peut-être rajouter un test sur ce controller d'ailleurs

2023-09-13 08:06 UTC, Holist commented
> Concernant l'UX je me demande si c'est très intuitif de cliquer sur le statut du rdv. Je me demande si une liste déroulante comme ce qui se fait sur RDVS ne serait pas mieux, à voir peut-être 🤷‍♂️ .

Je me suis fait la même réflexion. 
Je ne suis pas certain que les utilisateurs actuels arrivent à voir l'existence de cette nouvelle feature si on ne leur montre  pas. Il y a que le hover de la souris qui peut leur indiquer la nouvelle possibilité de changement de status.

2023-09-13 08:15 UTC, Michaelvilleneuve commented
@aminedhobb @Holist Merci pour vos retours, je vais essayer une UX à la RDVs dans ce cas, sans modal 👌

2023-09-13 08:54 UTC, Holist requested changes
Il y a un petit soucis d'implémentation au niveau de la route je pense.
Sinon c'est très clair, merci @Michaelvilleneuve :)

2023-09-13 08:54 UTC, Holist commented on app/clients/rdv_solidarites_client.rb
> +      "#{@url}/api/v1/rdvs/#{rdv_id}/rdvs_users/#{user_id}",
En faisant la review coté rdvs je pense qu'il y a un petit soucis d'implem (qu'il faudra corriger dans la pr rdvs aussi)
En choisissant de nester `rdvs_users` dans `rdvs` il faut utiliser `rdvs_user_id` (dans rdvi il s'agit de `rdv_solidarites_participation_id`) et pas `user_id`
Ou alors on neste `users` dans `rdvs` mais je pense que c'est pas vraiment utile et qu'il est préférable d'utiliser directement 
"#{@url}/api/v1/rdvs_users/#{rdvs_user_id}". 
C'est le plus logique car `rdvs_user` porte déjà l'id du rdv et celui du user directement.

2023-09-13 15:52 UTC, Michaelvilleneuve commented on app/clients/rdv_solidarites_client.rb
> +      "#{@url}/api/v1/rdvs/#{rdv_id}/rdvs_users/#{user_id}",
C'est push des 2 côtés :+1:

2023-09-14 14:09 UTC, Holist commented on app/models/concerns/rdv_participation_status.rb
> +    available_list = in_the_future? ? %w[unknown revoked] : %w[seen revoked excused noshow]
Laisser la possibilité de `revoked` une participation directement n'est pas implémenté dans rdvs (pour l'instant).
Si on décide de mettre ça en place ici, il faut prévoir un mécanisme coté rdv-s qui va garder une cohérence entre les status revoked des participations et le status du rdv. J'ai fait une proposition à ce sujet dans la PR coté rdvs.
Et dans ce cas on pourra utiliser : 
`available_list = in_the_future? ? %w[unknown revoked excused] : %w[seen revoked excused noshow]`

2023-09-14 19:14 UTC, Michaelvilleneuve commented on app/models/concerns/rdv_participation_status.rb
> +    available_list = in_the_future? ? %w[unknown revoked] : %w[seen revoked excused noshow]
J'ai updaté ça suite à la mise à jour que tu as fait sur la PR Rdvs 👍

2023-09-18 15:21 UTC, aminedhobb requested changes
Merci @Michaelvilleneuve pour les changements, l'UI est top 🙏 !!
Je pense qu'il y a encore un souci lorsqu'il y a plusieurs catégories pour la personne, mais on y est presque 💪 !

2023-09-18 15:21 UTC, aminedhobb commented on app/views/participations/update.turbo_stream.erb
> +  <%= turbo_stream.replace "rdv_context_status_tag", partial: "rdv_contexts/rdv_context_status_cell_tag", locals: { rdv_context: @participation.rdv_context, configuration: @participation.current_conf
Je ne comprends toujours pas comment est-ce qu'on pourrait savoir le statut de quelle `participation` et de quelle `rdv_context` il faut mettre à jour sur la page si on ne précise pas leurs ids. 
Il faudrait que le nom de tes turbo frames `participation_status` et `rdv_context_statuts_tag` soient plutôt  `participation_status_#{participation.id}` et `rdv_context_statuts_tag_#{rdv_context.id}` (il y a le helper [`dom_id`](https://apidock.com/rails/v6.1.3.1/ActionView/RecordIdentifier/dom_id) qui fait ça aussi). 
D'ailleurs vu qu'on utilise `turbo_stream` les partials pourrait tout aussi bien être encadrés par un `<div id=participation_status_#{participation.id}>` plutôt qu'une turbo frame ça marcherait aussi.

En faisant un test fonctionnel avec 2 rdvs c'est parfois le mauvais rdv qui se met à jour dans l'interface 😬

2023-09-18 15:21 UTC, aminedhobb commented on app/javascript/controllers/dropdown_controller.js
> +
Ce serait bien aussi de cacher le dropdown lorsqu'on click ailleurs sur la page

2023-09-19 12:49 UTC, Michaelvilleneuve commented on app/views/participations/update.turbo_stream.erb
> +  <%= turbo_stream.replace "rdv_context_status_tag", partial: "rdv_contexts/rdv_context_status_cell_tag", locals: { rdv_context: @participation.rdv_context, configuration: @participation.current_conf
Ahh effectivement ça m'est completement sorti de la tête vu que je travaillais avec une seule ligne... J'avais pas pensé que la page show pouvait en avoir plusieurs 🤦‍♂️

2023-09-20 09:41 UTC, aminedhobb submitted a review, later dismissed
Trop cool merci pour les changements @Michaelvilleneuve , c'est top 🙇 !!
En faisant des tests fonctionnels j'ai vu que la dropdown s'affichait parfois alors qu'on clique pas exactement dessus, mais c'est pas bloquant pour moi 👍

2023-09-20 09:41 UTC, aminedhobb commented on app/services/participations/update.rb
> +        @participation.update!(status: @participation_params[:status])
du coup on pourrait updater avec tous les params et pas juste le statut

2023-09-20 09:41 UTC, aminedhobb commented on app/javascript/stylesheets/pages/_applicant.scss
> +}
Pour ce qui est du conflit avec les turbo frames et si ça t'embêtes, tu peux utiliser des div à la place des turbo frames ici vu que tu mets à jour via turbo stream

2023-09-20 09:41 UTC, aminedhobb commented on spec/features/agent_can_update_a_participation_status_spec.rb
> +        expect(page).to have_content("Annulé (par le service)")
nitpick: on aurait pu tester que le statut du contexte se met à jour aussi ici

2023-09-20 10:03 UTC, aminedhobb commented on app/controllers/participations_controller.rb
> +    flash.now[:error] = "Impossible de changer le statut de ce rendez-vous." unless @success
ce n'est pas du tout lié à cette PR mais cette ligne me refait penser à un débat qu'on avait eu avec @qblanc et @Holist : Je ne comprends pas pourquoi une partie de la logique de mise à jour de la vue est placée ici en assignant ce flash et l'autre partie dans le fichier `turbo_stream.erb`. On voit bien d'ailleurs que la condition de l'affichage du flash en fonction du succès est réécrit dans le fichier turbo stream. 
Pour moi tout devrait être au même endroit.

2023-09-20 14:41 UTC, Michaelvilleneuve commented on app/controllers/participations_controller.rb
> +    flash.now[:error] = "Impossible de changer le statut de ce rendez-vous." unless @success
Je vois ce que tu veux dire mais ça me choque pas. Sur le fond c'est le même principe que si tu faisais ça:  
```ruby
# controller
def show
  @applicant = Applicant.find(id)
end

...

# show.turbo_stream.erb
turbo_stream.replace('applicant-modal', partial: 'applicant', locals: { applicant: @applicant } 
```
Qui est un truc qu'on fait partout : instantier une variable dans le controller que tu utilises dans ta vue

À choisir je préferais effectivement faire ça dans le fichier turbo_stream: 
```ruby
if @success
  ...
else
  render_flash_message("Impossible de changer le statut de ce rendez-vous."
end
```

2023-09-20 14:42 UTC, Michaelvilleneuve commented on app/javascript/stylesheets/pages/_applicant.scss
> +}
C'était génant de faire le changement mais maintenant qu'il est fait finalement c'est même mieux, ça permet d'avoir un partial plus réutilisable et qui ne renvoi pas une TD mais son contenu

2023-09-20 15:26 UTC, aminedhobb commented on app/javascript/stylesheets/pages/_applicant.scss
> +}
👌

2023-09-20 15:27 UTC, aminedhobb commented on app/controllers/participations_controller.rb
> +    flash.now[:error] = "Impossible de changer le statut de ce rendez-vous." unless @success
Oui je suis de ton avis aussi 👍 . 
Je retiens pour notre prochain point tech RDVI où je re-soumettrai cette proposition 😄 👌 .

2023-09-20 15:27 UTC, aminedhobb approved these changes
🚀

2023-09-21 07:54 UTC, merged