feat: add logos and maps for Gard and Pas-de-Calais
betagouv/rdv-insertion pull request #1400
Opened 2023-09-19 12:19 UTC by Michaelvilleneuve

2023-09-19 12:22 UTC, aminedhobb approved these changes
🙏

2023-09-19 12:25 UTC, qblanc requested changes
il faut que les logos des départements soient en png (ou alors qu'il y ait svg + png), sinon ça ne passe pas dans les invits

2023-09-19 12:28 UTC, aminedhobb commented
> il faut que les logos des départements soient en png (ou alors qu'il y ait svg + png), sinon ça ne passe pas dans les invits

J'avais pas fait attention, effectivement sinon ça passe pas dans les mails 👍

2023-09-20 08:40 UTC, aminedhobb approved these changes

2023-09-20 09:59 UTC, qblanc approved these changes
🔥

2023-09-20 10:04 UTC, merged