Feat/stats page
betagouv/rdv-insertion pull request #143
Opened 2021-12-02 15:39 UTC by qblanc

close #114

Dans cette PR, j'ajoute une page stat, ainsi qu'un "encart" de stats sur la page d'accueil.
Sur la page dédiée, les statistiques sont filtrables par département.
- ajout d'un `stats_controller` et d'un modèle `Stat`
- ajout de la colonne `oriented_at` à la table `applicants`, pour permettre de calculer le délai d'orientation des bRSA dont le dossier a été clos manuellement par les agents (la date retenue est alors la date de cloture du dossier, ou, si la clôture a eu lieu avant cette PR, la date de dernière MAJ de l'applicant).
- J'ai pris comme starting point du calcul des bénéficiaires orientés en mois de 30 jours le premier jour du mois de la création du compte, comme suggéré par Rémi dans l'issue ; on pourra modifier ça quand on aura la date d'ouverture des droits.
- Je n'ai pas encore mis l'évolution par mois, car on a pas assez d'historique, ce n'est pas très vendeur. Pour les comparaisons avec la situation d'avant, je n'ai pas les données pour l'instant, sauf erreur de ma part

![image](https://user-images.githubusercontent.com/46218316/144453524-0d3ca431-6809-46df-aa3f-112834d945e4.png)
![image](https://user-images.githubusercontent.com/46218316/144453654-d6fa733f-24a7-4f89-8331-3bc0efed86db.png)

2021-12-06 15:17 UTC, aminedhobb requested changes
Je t'ai fait quelques retours @qblanc , les fondations sont cools mais il reste encore des choses à changer pour que soit pleinement fonctionnel, notamment dans la manière de calculer les différents ratios.

Aussi il faudrait peut-être faire quelque chose pour l'Yonne parce que vu leur utilisation leur stats ne voudront rien dire (ils n'invitent pas les utilisateurs et ils ne précisent pas le statut du RDV sur RDV-S). Soit on zappe complètement soit on affiche le nombre de convocations envoyées (table `notifications`) cc @rprebot @ClaireCasu

2021-12-06 15:17 UTC, aminedhobb commented on app/models/stat.rb
> +  end
ll faut que la rapport soit un float et que tu multiplies ce rapport par 100 sinon le ratio vient d'une division euclidienne ce qui rend le résultat bcp moins précis : 
`(applicants_oriented_in_less_than_30_days.count  / (applicants_orientable_in_time.count.nonzero? || 1)).to_f * 100`

2021-12-06 15:17 UTC, aminedhobb commented on app/models/stat.rb
> +  end
Il faut que la moyenne soit un float pour être + précis

2021-12-06 15:17 UTC, aminedhobb commented on app/models/stat.rb
> +
Il faut que la moyenne soit un float pour être + précis

2021-12-06 15:17 UTC, aminedhobb commented on app/models/stat.rb
> +  end
Ici c'est pas un pourcentage vu que tu ne multiplies pas par 100. Il faut aussi que ce le ratio soit un float pour être + précis.

2021-12-07 17:27 UTC, qblanc commented on app/models/applicant.rb
> +    starting_date = created_at - 3.days
si on fait ça, ça veut dire que l'on calcule un délai d'orientation de 0 jour pour tous les utilisateurs dont les dossiers sont clos à la mano (ce qui sera extrêmement favorable pour nous).

2021-12-07 17:46 UTC, qblanc commented on app/models/applicant.rb
> +      DateTime.now
Je me trompe peut-être, mais à mon sens on en a besoin : les utilisateurs qui sont présents depuis moins de 30 jours sont déjà exclus du calcul dans `percentage_of_applicants_oriented_in_time` ; en revanche, pour ceux qui sont déjà présents depuis + de 30 jours et non orientés, il me paraît pertinent de les réintégrer, car c'est une donnée non favorable pour nous. Cela donne un résultat moins "consolidé", mais plus représentatif de ce qui se passe. Je ne sais pas si je l'explique très bien, on peut en discuter si tu veux.
On peut effectivement ne rien mettre et totalement exclure du calcul du délai d'orientation les utilisateurs non encore orientés, mais cela sort aussi du calcul les bRSA que les départements n'arriveraient éventuellement pas à orienter, ce qui devrait ressortir à mon sens.

2021-12-07 17:51 UTC, qblanc commented on app/models/stat.rb
> +    applicants - applicants.where("applicants.created_at > ?", 30.days.ago).where.not(status: %w[resolved rdv_seen])
Non, il me semble que ta proposition donne : tous les applicants orientés présents dans le système depuis plus de 30 jours (or on veut a minima tous les applicants orientés, quoi qu'il arrive).
Ce que je fais là, c'est : tous les applicants orientés + tous les applicants non orientés présents dans le système depuis plus de 30 jours

2021-12-07 17:54 UTC, qblanc commented on app/models/rdv.rb
> +  scope :closed, -> { where(status: %w[seen excused revoked noshow]) }
`informed` ça ne me paraît vraiment pas clair, ça implique de bien connaître la logique de rdv-s comme quoi c'est les agents qui manuellement "tagent" les rdvs. Je ne suis pas bloqué sur `closed` mais je cherche à exprimer le fait que les dossiers de ces rendez-vous sont clos, donc ça me paraissait logique et plus facile à comprendre pour un dev qui ne connaît pas parfaitement les logiques métier derrière le code.

2021-12-07 19:13 UTC, qblanc commented on app/models/stat.rb
> +  end
`applicants_oriented_in_less_than_30_days` et `applicants_orientable_in_time` seront toujours deux integers, donc la différence de précision sera minime. Et j'ai l'impression qu'afficher cette stat sous forme décimale n'est pas nécessaire (je pense même que ça sera moins agréable niveau lecture). Je modifie pour avoir un résultat décimal, mais du coup je vais rajouter des `to_i` dans les views

2021-12-07 19:20 UTC, qblanc commented on app/models/stat.rb
> +  end
même réponse que la précédente

2021-12-07 19:20 UTC, qblanc commented on app/models/stat.rb
> +
idem

2021-12-07 20:27 UTC, qblanc commented
Pour l'Yonne (et d'éventuels départements similaires), sur les 8 statistiques présentées pour l'instant : 
- Nombre de bénéficiaires du RSA gérés dans RDV-Insertion : pas de souci
- Nombre de bénéficiaires invités par mail ou SMS : ça ne me parait pas problématique, les convocations sont une forme d'invitation (la date est seulement imposée)
- Nombre de rendez-vous : ça ne me paraît pas problématique non plus, les rendez-vous sont gérés sur RDV-S mais on participe à leur gestion (sans nous, l'Yonne ne les aurait sans doute pas créés sur RDV-S), donc ça reste un indicateur ok pour de l'affichage à titre informatif à mon sens
- % de no show : **les usagers de l'Yonne doivent être retirés du calcul**
- % de bénéficiaires orientés en - de 30 jours : **les usagers de l'Yonne doivent être retirés du calcul**
- délai d'orientation bénéficiaire : **les usagers de l'Yonne doivent être retirés du calcul**
- délai d'orientation rdv : **les usagers de l'Yonne doivent être retirés du calcul**
- Nombre d'agents et de départements : pas de souci

Du coup, j'ai rajouté un filtre dans `stat.rb` pour filtrer les applicants de l'Yonne et d'éventuels départements similaires. Au-delà de l'implémentation technique que Amine vérifiera, est-ce que cette logique vous convient @rprebot @ClaireCasu @aminedhobb ?

2021-12-09 11:56 UTC, aminedhobb reviewed
Merci pour les changements @qblanc , au niveau de l'implémentation y a pas grand chose à redire, c'est plus sur la logique où j'ai des remarques, notamment sur comment on considère qu'un allocataire est orienté

2021-12-09 11:56 UTC, aminedhobb commented on app/models/applicant.rb
> +  end
En fait j'y pense: Quelqu'un qui est `resolved` c'est quelqu'un dont on a clôturé le dossier parce qu'il n'est finalement pas éligible au RSA (reprise d'emploi, déménagement) et donc au rdv d'orientation. Ça n'a pas de sens de le considérer comme orienté dans ce cas-là non ? Par contre il faudrait peut-être les enlever des autres calculs.

2021-12-09 11:56 UTC, aminedhobb commented on app/models/applicant.rb
> +  scope :oriented, -> { where(status: %w[resolved rdv_seen]) }
same here

2021-12-09 11:56 UTC, aminedhobb commented on db/migrate/20211201102104_add_oriented_at_to_applicants.rb
> +    add_column :applicants, :oriented_at, :datetime
Du coup je pense pas que l'on ait besoin de cette colonne. Désolé dans ma première review j'ai confondu ça avec la date d'ouverture des droits 🤦 .
Aujourd'hui la date d'orientation c'est **la date du premier rdv honoré**. Je vois pas d'autres cas.

2021-12-09 11:56 UTC, aminedhobb commented on app/javascript/components/update-applicant-button.js
> +  const attributes = (action === "Rouvrir le dossier") ? { status: "invitation_pending", oriented_at: today } : { status: "resolved", oriented_at: today };
Du coup on aurait pas besoin de ça.

2021-12-09 11:56 UTC, aminedhobb commented on app/models/applicant.rb
> +      DateTime.now
Je suis pas sûr de comprendre le problème, on peut en discuter de vive voix si tu veux.
Parce que là l'`orientation_date` c'est logiquement que pour des gens qui ont été orientés non ? 
D'ailleurs c'est ce que tu fais dans tes stats j'ai l'impression ?
Du coup pour moi ici ce serait juste `rdvs.seen.first.starts_at` si la personne a été orienté (ie a pris son rdv comme dit au dessus).

2021-12-09 11:56 UTC, aminedhobb commented on app/models/applicant.rb
> +    starting_date = created_at - 3.days
Oui pardon du coup tu as raison `oriented_at` n'a rien à faire ici.
Non `oriented_at` c'est bien mais je pense pas qu'on ait besoin de le stocker (cf. commentaires précédents)

2021-12-09 11:56 UTC, aminedhobb commented on app/models/rdv.rb
> +  scope :closed, -> { where(status: %w[seen excused revoked noshow]) }
Il y a peut-être mieux que `informed` pour indiquer qu'un "compte-rendu" du rdv a été renseigné mais j'ai pas trouvé.
Mais ici `rdv` représente réellement un RDV et pas un dossier de RDV comme tu dis (il a une date, une durée, une adresse etc.), donc `closed` me parait pas adapté  à ce modèle non plus.

2021-12-09 11:56 UTC, aminedhobb commented on app/views/static_pages/welcome.html.erb
> +        <p class="highlight-stat"><%= @stats.average_rdv_delay_in_days.to_i %> jours</p>
Il faudrait utiliser `round` plutôt que `to_i` pour avoir des vrais arrondis au sens mathématique.

2021-12-09 11:56 UTC, aminedhobb commented on app/models/stat.rb
> +    organisations.find(Configuration.where(notify_applicant: false).collect(&:organisation_id))
Ça devrait planter avec `find` et une collection d'id. Je pense qu'ici ce que tu cherches à faire c'est plutôt 
``` ruby
organisations.joins(:configuration).where(configuration: { notify_applicant: false })
```

2021-12-09 11:57 UTC, aminedhobb commented on app/models/stat.rb
> +  end
Ben du coup moi j'avais des `0%` alors qu'il y avait des RDV donc c'était problématique.
Mais oui pour l'affichage on peut les arrondir, mais plus avec `round` que `to_i` du coup.

2021-12-09 11:58 UTC, aminedhobb commented on app/models/stat.rb
> +    applicants - applicants.where("applicants.created_at > ?", 30.days.ago).where.not(status: %w[resolved rdv_seen])
Ah ok alright 👍

2021-12-09 15:22 UTC, qblanc commented on app/views/static_pages/welcome.html.erb
> +        <p class="highlight-stat"><%= @stats.average_rdv_delay_in_days.to_i %> jours</p>
`informed` je trouve que ce n'est pas assez clair, car un rendez-vous pourrait tout à fait être informed et pending/waiting (d'ailleurs informed peut-être un synonime de "caler" un rendez-vous). Or là il s'agit de rendez-vous qui sont "clos", je continue à penser que c'est le terme le + clair. Mais voilà typiquement le genre de cas ou je trouve que l'on chipote trop et que c'est un peu dommage d'y perdre du temps, on aura jamais le truc parfait :-)
Je change `closed` en `resolved`, en espérant que ça te convienne mieux. Sinon, je te laisse faire le changement toi-même avant de merge s'il n'y a plus que ça, je m'en fiche un peu en réalité.

2021-12-09 16:01 UTC, aminedhobb approved these changes
J'ai mis quelques petites remarques mais j'ai approve 🚀

2021-12-09 16:34 UTC, qblanc commented on app/models/stat.rb
> +    relevant_applicants - non_pertinent_applicants
non car je m'en sert aussi pour `relevant_rdvs` :)

2021-12-09 16:43 UTC, aminedhobb commented on app/models/stat.rb
> +    relevant_applicants - non_pertinent_applicants
Mais on veut pas prendre en compte les utilisateurs supprimés ou dont le dossier a été clôturés quoiqu'il arrive je pense ? D'ailleurs `relevant_rdvs` ça devrait plutôt être `rdvs.where(applicants: relevant_applicants)` à mon avis

2021-12-10 09:53 UTC, qblanc commented on app/models/stat.rb
> +    relevant_applicants - non_pertinent_applicants
J'ai fait les deux changements. Mais pour les applicants `deleted`, il faut espérer que les agents ne se mettent pas à faire des vagues de suppression de temps en temps des applicants pour "cleaner" un peu leur liste, sinon ça va fausser nos stats.
Pour prévenir ce comportement indésirable, on pourrait peut-être faire disparaître les usagers `rdv_seen` et `resolved` de l'index lorsqu'ils passent à ce statut (ou x jours après être passés à ce statut), en créant une page "historique", ou un nom du genre, où les agents peuvent retrouver leur fiche si nécessaire. Qu'en penses-tu ? (ce serait une autre issue of course)

2021-12-13 09:07 UTC, aminedhobb approved these changes
🚀

2021-12-13 09:23 UTC, merged