feat(api): add new endpoint to create and invite
betagouv/rdv-insertion pull request #1476
Opened 2023-10-09 22:21 UTC by aminedhobb

2023-10-18 16:20 UTC, qblanc commented on app/controllers/api/v1/application_controller.rb
> +      def render_errors(errors)
j'ajouterais bien ici un commentaire précisant que cet argument est attendu sous forme d'array

2023-10-18 16:21 UTC, qblanc commented on app/controllers/api/v1/application_controller.rb
> +        render json: { success: false, errors: }, status: :unprocessable_entity
quand l'argument porte le même nom on est pas obligé de le réécrire explicitement (pour `errors:` ?)

2023-10-18 16:35 UTC, qblanc commented on app/controllers/api/v1/users_controller.rb
> +        invite_user_service = call_invite_user_service_by("sms")
je pense que tu voulais plutôt écrirer `invite_user_service = call_invite_user_service_by(format)`, non ?

2023-10-18 17:13 UTC, qblanc requested changes
Je n'ai pas review les tests mais à part ça LGTM !! 🚀
Il y a juste une petite remarque qui me semble bloquante (le commentaire sur `"sms"` plutôt que `format`) sinon ce sont plutôt des questions.

2023-10-18 17:13 UTC, qblanc commented on app/controllers/users_controller.rb
> +    )
on pourrait peut-être mettre ça dans une méthode `upsert_user` (ce serait plus cohérent avec ce qu'on fait dans le reste du controller)

2023-10-18 17:13 UTC, qblanc commented on app/models/invitation.rb
> +  end
je ne connais pas cette syntaxe, tu peux m'expliquer ?

2023-10-18 17:13 UTC, qblanc commented on app/services/users/validate.rb
>        return if users_with_same_email_and_first_name.empty?
- on peut pas mettre un `||` plutôt que deux lignes ?

2023-10-18 17:13 UTC, qblanc commented on app/services/users/validate.rb
> +
Pourquoi cet ajout ? Enfin je crois comprendre : tu veux que la validation de la présence du `first_name` et du `last_name` se fasse ici plutôt que dans les autres méthodes, mais pourquoi ? On ratait d'autres validations ?

2023-10-19 10:34 UTC, aminedhobb commented on app/controllers/invitations_controller.rb
> +      .to_a
Je pense que je voulais passer un array au service comme c'est fait au niveau de l'API, mais effectivment il n'y a pas forcément besoin. J'ai changé ici: https://github.com/betagouv/rdv-insertion/pull/1476/commits/d2f8ccf6cc78ee7180dab337f4a5e2f92363d4a3

2023-10-19 10:35 UTC, aminedhobb commented on app/controllers/api/v1/users_controller.rb
> +        invite_user_service = call_invite_user_service_by("sms")
Oui bien vu 🙏 ! réctifié ici https://github.com/betagouv/rdv-insertion/pull/1476/commits/d2f8ccf6cc78ee7180dab337f4a5e2f92363d4a3.
Je n'ai pas écrit de test sur cet endpoint parce que je suis en train de le faire via ma nouvelle PR dans laquelle j'introduis rswag.

2023-10-19 10:35 UTC, aminedhobb commented on app/controllers/api/v1/application_controller.rb
> +      def render_errors(errors)
Dans ma nouvelle PR ce sera plus mis en évidence, je laisse comme ça ici pour l'instant si ça te va

2023-10-19 10:35 UTC, aminedhobb commented on app/controllers/api/v1/application_controller.rb
> +        render json: { success: false, errors: }, status: :unprocessable_entity
Oui depuis ruby 3 :)

2023-10-19 10:36 UTC, aminedhobb commented on app/controllers/users_controller.rb
> +    upsert_user = Users::Upsert.call(
Parce que pour l'action `update` on a déjà un record de `user`, du coup pas besoin de passer par l'étape `find_or_initialize`

2023-10-19 10:37 UTC, aminedhobb commented on app/controllers/users_controller.rb
> +    )
Yes c'est parce qu'il était pas utilisé ailleurs mais effectivement c'est pas homogène, j'ai changé ici https://github.com/betagouv/rdv-insertion/pull/1476/commits/d2f8ccf6cc78ee7180dab337f4a5e2f92363d4a3

2023-10-19 12:03 UTC, aminedhobb commented on app/models/invitation.rb
> +  end
C'était parce que dans la requête on envoyer `invitation_format` en param et pas `format` pour ne pas que ce soit confondu avec le format de la requête.
Mais en fait les params n'était pas nesté derrière une clé `:invitation`, je l'ai fait ici et du coup j'ai enlevé cette méthode: https://github.com/betagouv/rdv-insertion/pull/1476/commits/5a9cefa238646848bc6bf6782cdf092291b67661

2023-10-19 12:04 UTC, aminedhobb commented on app/services/base_service.rb
> +      service = new(**kwargs)
C'est pas lié à cette PR c'est vrai, mais c'est juste qu'on appelle et on veut toujours appeler les services avec des keyword arguments et pas des arguments et que donc ça ne servait à rien de prendre en compte les arguments.

2023-10-19 12:05 UTC, aminedhobb commented on app/services/users/validate.rb
>        return if users_with_same_email_and_first_name.empty?
done here https://github.com/betagouv/rdv-insertion/pull/1476/commits/d2f8ccf6cc78ee7180dab337f4a5e2f92363d4a3

2023-10-19 12:08 UTC, aminedhobb commented on app/services/users/validate.rb
> +
Je l'ai enlevé c'est vrai que c'était pas le bon endroit où le mettre, ce service vérifie uniquement la validité du record par rapport à notre logique métier contrairement à la validation active record qui fait la validation du format de donné.
C'était juste qu'on faisait cette validation avant la validation active record mais ce n'est pas gênant.

2023-10-19 12:20 UTC, aminedhobb commented
Merci @qblanc pour ta review minutieuse et pertinte 🙌 !
J'ai appliqué tes suggestions et répondu à tes questions.

2023-10-19 22:17 UTC, qblanc approved these changes
Merci pour les réponses ! 🚀

2023-11-06 13:10 UTC, merged