feat(rgpd): destroy old ressources every day
betagouv/rdv-insertion pull request #1584
Opened 2023-12-05 12:37 UTC by qblanc

closes #1375 
closes #1380 

Dans cette PR, je permet de supprimer les usagers inactifs depuis 2 ans et leurs ressources liées. Je détruis également les notifications, qui ne sont plus forcément liées aux utilisateurs, au bout de 2 ans.

2023-12-11 13:49 UTC, aminedhobb requested changes
J'ai laissé remarques, je pense pas qu'on puisse merger ça en l'état.
Aussi, au vu de la sensibilité de ces actions destructrices, il faudrait que ce soit bien testé avec tous les cas possibles (que je mentionne dans mes commentaires) :).

2023-12-11 13:49 UTC, aminedhobb commented on app/jobs/destroy_old_ressources_job.rb
> +    Rdv.where.missing(:participations).destroy_all
Ça va détruire les rdv collectifs qui n'ont pas encore de participations 😬 .
Je pense pas que ce soit nécessaire de gérer ces cas-là

2023-12-11 13:49 UTC, aminedhobb commented on app/jobs/destroy_old_ressources_job.rb
> +    Notification.where("created_at < ?", date_limit).destroy_all
Ça nous enlève juste la date de l'envoi de la convocation, c'est peut-être pas hyper impactant mais je vois pas trop l'utilité de le supprimer non plus

2023-12-11 13:49 UTC, aminedhobb commented on app/jobs/destroy_old_ressources_job.rb
> +        .where("users_organisations.created_at < ? OR users_organisations.created_at IS NULL", date_limit)
Est-ce qu'on est sûr que si c'est le MAX des `invitations.created_at`, `participations.created_at` etc. qui est pris en compte ici ? Sinon on va supprimer ceux qui ont eu des rdvs ou des invitations ils y a 2 ans 😄

2023-12-11 17:56 UTC, qblanc commented on app/jobs/destroy_old_ressources_job.rb
> +    Notification.where("created_at < ?", date_limit).destroy_all
C'est pas une bonne pratique de supprimer les ressources qui ne servent plus à rien ? Ça économise du stockage (c'est qui est préférable d'un point de vue autant économique qu'écologique)

2023-12-11 18:15 UTC, aminedhobb commented on app/jobs/destroy_old_ressources_job.rb
> +    Notification.where("created_at < ?", date_limit).destroy_all
Ça ne sert pas à rien, on affiche les notifications envoyées (ainsi que la date d'envoi) pour les rdvs de convocations.
Pour des rdvs de + de 2 ans l'info est peut-être moins utile, mais on va avoir des rdvs de convocations qui n'ont pas de notifications et ça va avoir des conséquences au niveau de l'UI.

2023-12-11 18:36 UTC, qblanc commented on app/jobs/destroy_old_ressources_job.rb
> +    Rdv.where.missing(:participations).destroy_all
si on limite aux rdvs qui ont plus de deux ans ça résoudrait le problème. Même logique que pour les notifications : je suis d'accord que ces records ne gênent pas mais ils ne servent à rien non plus, pourquoi les garder ?

2023-12-11 18:37 UTC, qblanc commented on app/jobs/destroy_old_ressources_job.rb
> +        .where("users_organisations.created_at < ? OR users_organisations.created_at IS NULL", date_limit)
bien vu, la requête n'était pas encore tout à fait au point

2023-12-12 08:53 UTC, qblanc commented on app/jobs/destroy_old_ressources_job.rb
> +    Notification.where("created_at < ?", date_limit).destroy_all
Ah oui pardon j'avais mal écrit ce que je voulais faire : je ne voulais en en fait target que les notifications sans `participation_id`, puisque celles-ci sont définitivement inutiles (il me semble)

2023-12-14 13:46 UTC, aminedhobb reviewed
Merci pour les tests @qblanc 🙏 !
C'est bon pour moi 👍 , mais vu la sensibilité de la chose je préfère qu'il y ait un autre regard attentif sur cette PR (cc @Michaelvilleneuve ) avant qu'on merge.

2023-12-14 13:46 UTC, aminedhobb commented on app/jobs/destroy_old_ressources_job.rb
> +            )", date_limit)
remarque: Je pense qu'on pourrait le faire en utilisant AR mais pas sûr que ce soit mieux ou plus lisible

2023-12-19 10:38 UTC, Michaelvilleneuve commented
Bah écoute cette solution me paraît simple et efficace et les tests associés me semblent convaincants 👌.
Sachant que le premier run sera celui qui supprimera le plus de données, à voir peut-être si on peut pas au début ne pas inclure le cron et à la place run le job manuellement en faisant en sorte qu'il fasse juste un reporting de la data à supprimer histoire qu'on ai pleinement confiance ?

2023-12-19 10:39 UTC, Michaelvilleneuve approved these changes

2023-12-19 10:48 UTC, aminedhobb commented
> Bah écoute cette solution me paraît simple et efficace et les tests associés me semblent convaincants 👌. Sachant que le premier run sera celui qui supprimera le plus de données, à voir peut-être si on peut pas au début ne pas inclure le cron et à la place run le job manuellement en faisant en sorte qu'il fasse juste un reporting de la data à supprimer histoire qu'on ai pleinement confiance ?

Je suis d'accord, ce serait bien d'avoir un mode `dry_run` (ou alors juste un script à côté) qui fait que reporter les ids des ressources que le job va supprimer sans vraiment les supprimer, pour vérifier au début que c'est bien ce qu'on veut avant de vraiment setter le CRON

2023-12-19 12:14 UTC, qblanc commented
J'ai ajouté un script reprenant les mêmes requêtes et j'ai désactivé le cron [dans ce commit](https://github.com/betagouv/rdv-insertion/pull/1584/commits/c498f246c18d48a3459c875508ba25f0d810882f) pour pouvoir faire un dry run de reporting dans un premier temps, est-ce que ça vous paraît suffisant ?

2023-12-19 12:15 UTC, qblanc commented
J'ai ajouté un script reprenant les mêmes requêtes et j'ai désactivé le cron [dans ce commit](https://github.com/betagouv/rdv-insertion/pull/1584/commits/c498f246c18d48a3459c875508ba25f0d810882f) pour pouvoir faire un dry run de reporting dans un premier temps, est-ce que ça vous paraît suffisant ? @Michaelvilleneuve @aminedhobb

2023-12-19 16:27 UTC, aminedhobb approved these changes
C'est nickel merci 🙇‍♂️ !!!

2023-12-19 16:42 UTC, merged