fix(stats): minor issues
betagouv/rdv-insertion pull request #1648
Opened 2024-01-10 10:00 UTC by Michaelvilleneuve

Cette PR permet de corriger 2 problèmes liées au stats : 
- Le mois en cours était pris en compte et donnait des résultats biaisant la lecture des courbes :
<img width="1207" alt="image" src="https://github.com/betagouv/rdv-insertion/assets/4990201/33063b20-b9cb-4989-affc-778d0ffd35d9">

- Les insertion manuelles de participations / rattrapage de données faite après les dates originales par les agents pouvaient fausser la lecture du graphique de délai moyen d'invitation en mettant des valeurs négatives. 
Afin de corriger ça on ne prend désormais plus en compte les valeurs négatives dans le calcul. 
<img width="598" alt="image" src="https://github.com/betagouv/rdv-insertion/assets/4990201/a8aac7c3-c066-4c0d-a658-1f3e8b4f931b">

2024-01-15 13:47 UTC, aminedhobb reviewed
Merci @Michaelvilleneuve 🙌 ! 
Je t'ai posé une question sur le décalage d'un mois du calcul de stat, pour les valeurs négatives LGTM 👌 .

2024-01-15 13:47 UTC, aminedhobb commented on app/services/stats/compute_average_time_between_invitation_and_rdv_in_days.rb
> +        next if rdv_context.time_between_invitation_and_rdv_in_days.negative?
Il faudrait peut-être mettre un commentaire ici pour dire pourquoi on ne les prend pas en compte.
En regardant le code je vois que le délai est le delta entre la date de l'envoi de l'invitation et la date de la création de l'invitation. 
Donc les rdvs créés qui ont lieu dans le passé ne sont pas la cause de ce problème, mais plutôt les contextes pour lesquels on invite la personne alors qu'on avait déjà placé un rdv au préalable directement via rdv solidarités. Ça doit être notamment le cas pour les personnes créées sur rdv-s et récupérées sur l'appli

2024-01-15 13:47 UTC, aminedhobb commented on app/services/stats/monthly_stats/upsert_stat.rb
> +          stat_attribute.merge!({ (@date - 1.month).strftime("%m/%Y") => stat_value })
Mais donc toutes les stats que l'on calcule et affiche sont en réalité les stats du mois précédent de ce que l'on affiche ?
Je me demande si ça fausse pas un peu les stats (mais peut-être pas toutes)

2024-01-15 15:52 UTC, Michaelvilleneuve commented on app/services/stats/monthly_stats/upsert_stat.rb
> +          stat_attribute.merge!({ (@date - 1.month).strftime("%m/%Y") => stat_value })
Effectivement, c'est un choix mais ça permet d'éviter les courbes incohérentes sur le mois en cours. Si on souhaite que ce soit purement de l'affichage on pourrait faire un filtre au niveau de l'affichage de la donnée.
Mais personnellement ça me semble cohérent de se dire qu'on considère une stat comme "affichable" lorsque le mois se termine.

2024-01-15 16:41 UTC, qblanc commented on app/services/stats/monthly_stats/upsert_stat.rb
> +          stat_attribute.merge!({ (@date - 1.month).strftime("%m/%Y") => stat_value })
pour le coup je ne suis pas d'accord, il faut que les stats qu'on affiche pour le mois X correspondent aux stats du mois X. Si on veut cacher le mois en cours il vaut mieux le faire du côté de l'affichage imo

2024-01-16 13:07 UTC, aminedhobb requested changes

2024-01-16 16:18 UTC, Michaelvilleneuve commented on app/services/stats/monthly_stats/upsert_stat.rb
> +          stat_attribute.merge!({ (@date - 1.month).strftime("%m/%Y") => stat_value })
All right ça me va aussi 👌

2024-01-17 16:09 UTC, merged