feat(creneaux_alert_job): add availability alert job for organisation…
betagouv/rdv-insertion pull request #1690
Opened 2024-01-23 16:19 UTC by Holist

2024-01-24 13:19 UTC, Michaelvilleneuve commented on app/jobs/send_creneau_availability_alert_job.rb
> +  end
Peut-être peut-on split le job en X job (1 par organisation) ?

Cela permettra :
- D'avoir des jobs qui vont beaucoup plus vite (éviter de monopoliser un worker pendant plus d'une minute -> moins de chance que le job fail pour des raisons hardware (OOM, etc))
- D'éviter de bloquer le process entier si certaines orga engendrent une erreur 
- D'éviter d'avoir à relancer tout le job s'il y a des failures, le retry sera géré individuellement par job
- Et ainsi d'éviter d'envoyer des mails en doublon en cas d'erreur sur le job

2024-01-24 14:49 UTC, aminedhobb reviewed
Merci @Holist ça va être top cette feature 💪 !!
J'ai fait quelques suggestions sans rentrer trop dans les détails 🙌

2024-01-24 14:49 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      @organisation.invitations.valid.map do |invitation|
On peut regrouper une seule invitation par `rdv_context` , ça ne sert à rien de faire la vérif sur le mail/sms/courrier IMO puisque les paramètres seront les mêmes (à part énorme exception).

Auquel cas le map en bas ne sert plus si je ne me trompe pas.

2024-01-24 14:49 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +    end
J'ai eu beaucoup de mal à comprendre ce code parce qu'on parle de motifs alors qu'à priori on ne manipule rien qui est lié aux `motifs`. Ici ce sont encore des paramètres de l'invitation qu'on manipule

2024-01-24 14:49 UTC, aminedhobb commented on app/views/mailers/organisation_mailer/creneau_unavailable.html.erb
> +  <%= tag.p ("Les codes postaux concernés sont : #{motif[:city_codes].join(", ")}.") if motif[:city_codes].present? %>
Il faudrait préciser que les codes postaux n'ont de l'importance que si la sectorisation n'est pas activée.

2024-01-24 14:49 UTC, aminedhobb commented on app/views/mailers/organisation_mailer/creneau_unavailable.html.erb
> +  <%= tag.p ("Les référents concernés sont : #{motif[:referent_ids].join(", ")}.") if motif[:referent_ids].present? %>
Les ids de référent ne sont pas utiles pour les agents rdv-i à priori, il faudrait au moins les email je pense

2024-01-24 14:49 UTC, aminedhobb commented on app/mailers/organisation_mailer.rb
> +    return if organisation.email.blank?
Il faudrait pas qu'on soit au moins notifié si c'est le cas ?

2024-01-24 14:49 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      motif_name = MotifCategory.find_by(short_name: invitation[:motif_category_short_name]).name
c'est un peu révélateur que les `motif_category` ça devrait être des `motifs` (c'est ce que veut faire rdv-s il me semble)

2024-01-24 15:04 UTC, Holist commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      }
Effectivement, on ne prend pas en compte ces params `address`, `latitude`, `longitude` et `organisation_ids`

2024-01-24 15:35 UTC, Holist commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      motif_name = MotifCategory.find_by(short_name: invitation[:motif_category_short_name]).name
Je fais ca pour récupérer le nom de la catégorie et pas le `motif_category_short_name ` qu'on utilise dans l'invitation qui ne parlera pas à l'agent qui recevra le mail d'alerte mais oui il y a des améliorations à apporter au niveau des motifs et des catégories (en cours de discussion chez rdvsp)

2024-01-24 16:08 UTC, Holist commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +    end
Je règle ca. Merci :)

2024-01-24 16:10 UTC, Holist commented on app/mailers/organisation_mailer.rb
> +    return if organisation.email.blank?
Bien vu j'ajoute une petite ligne dans la notif mattermost pour nous prévenir si ce cas arrive.

2024-01-24 16:59 UTC, Holist commented on app/jobs/send_creneau_availability_alert_job.rb
> +  end
Merci, effectivement que des avantages. :) C'est fait.

2024-01-25 13:20 UTC, Holist commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      }
J'ai amélioré la lisibilité du code à ce niveau.

2024-01-25 13:20 UTC, Holist commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      @organisation.invitations.valid.map do |invitation|
J'ai amélioré la lisibilité du code à ce niveau.

2024-01-25 15:42 UTC, samanthaauffret commented
@Holist , 
Effectivement le mail est assez dur à lire à première vue. 
Je peux l'optimiser et te faire une propal de texte lundi pro, ça te va ?

2024-01-29 14:24 UTC, samanthaauffret commented
@Holist , 

Voici une version retravaillé du texte de l'email des créneaux complets. 

Il y a également deux modifications qui vont au-delà du changement de texte : 
> Le titre de l'email qui devient un texte lié au sujet du mail, à la place du simple "Madame, Monsieur"
> L'ajout d'un bouton de redirection pour faciliter l'accès à RDVS. Celui-ci peut renvoyer sur la page "sign in" de RDVS. Les utilisateurs pourront trouver la fonctionnalité des créneaux en autonomie. 

Cette nouvelle version a été vu par @amaurydubot 

<img width="720" alt="v1 simple" src="https://github.com/betagouv/rdv-insertion/assets/156072816/27a345f4-c27f-4e15-b9c2-df026fdb0363">

2024-02-07 14:50 UTC, aminedhobb requested changes
Merci @Holist pour les changements c'est beaucoup mieux je trouve 💪 !
Je pense qu'il y a encore quelques petites choses à changer mais on y est presque :) !

2024-02-07 14:50 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      Current.agent = @organisation.agents.first
On peut peut-être mettre un commentaire ici pour dire qu'on set un `Current.agent` pour pouvoir appeler l'api rdvs

2024-02-07 14:50 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      return unless @organisation.invitations.valid.any?
nitpick: on pourrait encapsuler `@organisation.invitations.valid` dans une méthode `organisation_valid_invitations` et la mémoizer (vu qu'on réutilise l'expression plus bas).

Aussi, mais ça c'est vraiment question de préférence donc je te laisse juger, je trouve que `return unless ...any?` c'est un peu plus dur cognitivement que `return if ...empty?`

2024-02-07 14:50 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      category_params_group[:invations_counter] += 1
```suggestion
      category_params_group[:invitations_counter] += 1
```
👀

2024-02-07 14:50 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      category_params_group = { motif_category_name: motif_category_name, city_codes: [], referent_ids: [],
Tu peux utiliser des `sets` plutôt que des `array` sur les `city_codes` et les `referent_ids` qui vont gérer directement l'unicité

2024-02-07 14:50 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      result.unavailable_params_motifs = process_invitations_params_without_creneau
Pourquoi ne pas garder `grouped_invitation_params_by_category` comme nom ici ? Je trouve ça beaucoup plus clair. 
on pourrait d'ailleurs le faire en deux lignes pour bien montrer que c'est la même variable 
```ruby 
process_invitations_params_without_creneau
result.grouped_invitation_params_by_category = @grouped_invitation_params_by_category 
```

2024-02-07 14:50 UTC, aminedhobb commented on app/mailers/organisation_mailer.rb
> +    @motifs = motifs
le nom `@motifs` est vraiment trompeur ici parce que ce ne sont pas des motifs comme ailleurs dans l'application. Je serais plutôt d'avis de garder `grouped_invitation_params_by_category` même si c'est plus long (à moins que tu n'aies une autre suggestion)

2024-02-07 14:50 UTC, aminedhobb commented on app/views/mailers/organisation_mailer/creneau_unavailable.html.erb
> +    <%= tag.p tag.span("*Les codes postaux n'ont de l'importance que si la sectorisation n'est pas activée.", style: "color: grey;") if motif[:city_codes].present? %>
c'est pas plutôt 
```suggestion
    <%= tag.p tag.span("*Les codes postaux n'ont de l'importance que si la sectorisation est activée.", style: "color: grey;") if motif[:city_codes].present? %>
```
😄 ?

2024-02-07 14:50 UTC, aminedhobb commented on app/views/mailers/organisation_mailer/creneau_unavailable.html.erb
> +<p>Nous vous invitons donc à créer de nouvelles plages d'ouverture pour des RDV individuels ou collectifs, afin que les usagers puissent bien prendre rendez-vous.</p>
On devrait directement parler d'allongement du délai de visibilité ici IMO, parce qu'on dirait que le CTA est lié seulement à l'action "créer de nouvelles plages d'ouvertures" ce qui est trompeur

2024-02-07 14:50 UTC, aminedhobb commented on app/views/mailers/organisation_mailer/creneau_unavailable.html.erb
> +  <%= link_to "Ouvrir des créneaux", "https://www.rdv-solidarites.fr/agents/sign_in", class: "btn btn-primary", target: :blank %>
Est-ce qu'il n'y a pas une page un peu plus précise vers laquelle on redirigerait, au moins l'interface admin de l'organisation ?

2024-02-07 14:50 UTC, aminedhobb commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      category_params_group[:referent_ids] << referent_ids
on ne devrait plutôt faire 
```suggestion
      category_params_group[:referent_ids] += referent_ids
```
pour ne pas se retrouver avec un tableau de tableau je pense

2024-02-07 16:14 UTC, Holist commented on app/services/invitations/verify_organisation_creneaux_availability.rb
> +      category_params_group[:invations_counter] += 1
🤦‍♂️

2024-02-07 16:16 UTC, Holist commented on app/views/mailers/organisation_mailer/creneau_unavailable.html.erb
> +    <%= tag.p tag.span("*Les codes postaux n'ont de l'importance que si la sectorisation n'est pas activée.", style: "color: grey;") if motif[:city_codes].present? %>
🤦‍♂️ again

2024-02-08 15:36 UTC, aminedhobb approved these changes
Merci pour les changements @Holist 🚀 🚀  !!

2024-02-08 15:38 UTC, merged