fix(invitations): better configurations selection + send explicit error when invitation is not sent
betagouv/rdv-insertion pull request #1699
Opened 2024-01-24 14:21 UTC by qblanc

closes #1695 
closes #1698 

Cette PR résout 2 faiblesses du service `InviteUser` : 
- les configurations prises en compte pour l'envoi de l'invitation doivent faire partie des organisations du `user` et pas seulement du `agent`
- lorsque nous bloquons l'envoi d'une invitation parce qu'une identique a déjà été envoyée le même jour, nous affichons une erreur à l'agent

2024-01-24 14:57 UTC, aminedhobb reviewed
Je t'ai laissé un commentaire sur le edge case 👍

2024-01-24 14:57 UTC, aminedhobb commented on app/services/invite_user.rb
> +    check_if_invitation_should_be_sent
```suggestion
    check_if_invitation_should_be_sent!
```
pour être plus cohérent avec ce qu'on fait par ailleurs

2024-01-24 14:57 UTC, aminedhobb commented on app/services/invite_user.rb
>    def set_current_configuration
Mais du coup si on est dans le edge case que j'évoque dans le ticket, `@current_configuration` sera `nil` et on aura une erreur 500. 
Il faudrait faire une vérif ici je pense. On fait déjà une vérif [ici](https://github.com/betagouv/rdv-insertion/blob/d5efb6550271e9329eb8ab301eb6050b8652d5ba/app/services/invitations/validate.rb#L47) mais ça intervient plus/trop tard

2024-01-24 17:02 UTC, qblanc commented on app/services/invite_user.rb
>    def set_current_configuration
Ok, j'ai fait en sorte que ce edge case ne soit plus possible dans le nouveau commit

2024-01-29 10:20 UTC, aminedhobb reviewed
Merci @qblanc 🙏 !
C'est top, je me demande du coup si on devrait pas utiliser ce service (ou un nouveau service `RdvContexts::FindOrCreate`) dans le service `InviteUser` au niveau de la méthode `find_or_create_rdv_contexts`.
(Si on fait ça, ça pose la question de la pertinence de garder le check dans `Invitations::Validate`).

2024-01-29 11:30 UTC, aminedhobb commented
> Merci @qblanc 🙏 ! C'est top, je me demande du coup si on devrait pas utiliser ce service (ou un nouveau service `RdvContexts::FindOrCreate`) dans le service `InviteUser` au niveau de la méthode `find_or_create_rdv_contexts`. (Si on fait ça, ça pose la question de la pertinence de garder le check dans `Invitations::Validate`).

Si tu veux on peut séparer ça en deux PRs et garder cette PR pour le premier fix et faire une autre pour gérer les cas des contextes / organisations

2024-01-30 10:21 UTC, aminedhobb requested changes
Merci @qblanc, je pense qu'il y a quelques choses à changer sur cette dernière implémentation.
Mais comme on a pas encore shippé le bug initial qui est impactant et qu'on est en train de gérer des edge cases, je serais partant qu'on revienne sur sur [ton dernier commit](https://github.com/betagouv/rdv-insertion/pull/1699/commits/e405a72940636ffec7e15b53b2b1c08fcd1e8678) (en ajoutant peut-être un test au service) et qu'on gère ces cas-là plus tard (j'écrirai un ticket). C'est bon pour toi ?

2024-01-30 10:21 UTC, aminedhobb commented on app/jobs/inbound_webhooks/rdv_solidarites/process_rdv_job.rb
> +            RdvContexts::FindOrCreate.call(user:, motif_category:).rdv_context
Du coup le cas d'erreur n'est pas géré ici donc ça aura un comportement inattendu quand le service va fail

2024-01-30 10:21 UTC, aminedhobb commented on app/services/invite_user.rb
> +      RdvContexts::FindOrCreate.call(user: @user, motif_category: @current_configuration.motif_category).rdv_context
pareil ici le cas d'erreur n'est pas géré

2024-01-30 10:21 UTC, aminedhobb commented on app/services/rdv_contexts/find_or_create.rb
> +        authorize @rdv_context, :create?
On met les autorisations dans le controller en général, notamment parce que si la personne n'est pas autorisé ça va raise une `Pundit::NotAuthorizedError` qui est rescued au niveau des controllers mais pas ici

2024-01-30 10:28 UTC, qblanc commented
ha ha oui, moi ça me va de revenir au commit précédent, c'est toi qui me demandait de rajouter une nouvelle brique à chaque fois :)

2024-01-30 11:12 UTC, aminedhobb submitted a review, later dismissed
Merci @qblanc 🙏 !!

2024-01-30 11:31 UTC, merged