fix(tags): add policy restriction
betagouv/rdv-insertion pull request #1719
Opened 2024-01-30 14:32 UTC by Michaelvilleneuve

Ajout d'une policy sur les tags pour n'afficher que ceux des organisations de l'agent connecté. 
Correction aussi d'un problème de distinct, la liste des tags affichés n'étaient pas dé-dupliquée. 
J'ai vérifié en prod il n'y a pas de doublon dans la table Tag c'était bien juste un distinct à ajouter pour la jointure

Fix https://github.com/betagouv/rdv-insertion/issues/1655
Fix https://github.com/betagouv/rdv-insertion/issues/1658

2024-02-05 10:37 UTC, qblanc commented on app/controllers/tag_assignations_controller.rb
> +    @available_tags = department_level? ? policy_scope(department.tags).distinct : organisation.tags
on pourrait appliquer la policy dans les deux cas du coup (même si _a priori_ ça ne changera rien dans le second cas)

2024-02-05 13:32 UTC, Michaelvilleneuve commented on app/controllers/tag_assignations_controller.rb
> +    @available_tags = department_level? ? policy_scope(department.tags).distinct : organisation.tags
Je suis pas trop d'accord car comme tu dis ça ne change rien (l'agent a nécessairement accès à cette organisation) donc cela permet d'éviter ce join qui n'est pas anodin `.joins(:organisations).where(organisations: pundit_user.organisations)`

2024-02-07 13:21 UTC, aminedhobb requested changes
Merci @Michaelvilleneuve , il faudrait appliquer cette policy sur la page show car tous les tags du département restent visibles sur cette page

2024-02-08 10:53 UTC, aminedhobb approved these changes
👍

2024-02-08 12:58 UTC, merged