feat(statuses): clearer wording for unknown rdv/participation status
betagouv/rdv-insertion pull request #1848
Opened 2024-03-11 12:58 UTC by qblanc

closes #1809 

Dans cette PR, je fais plusieurs petits changements liés au statut `unknown` des participations/rdvs : 
- pour les utilisateurs de l'app, je fais en sorte que le statut `Non déterminé` (qui n'est pas facile à comprendre) n'apparaisse plus jamais. Il sera affiché soit `RDV à venir` ou `Statut du RDV à préciser`
- en db, et en output (ce qui sort via l'API), je fais en sorte que le statut reste `unknown`, afin de rester iso avec rdv-sp
- j'en profite pour remplacer `RDV pris` par `RDV à venir` (qui me paraît plus clair)

<img width="1299" alt="Capture d’écran 2024-03-11 à 13 57 12" src="https://github.com/betagouv/rdv-insertion/assets/46218316/e4d7c82a-4a09-4780-b723-430ca22b59cc">
<img width="1156" alt="Capture d’écran 2024-03-11 à 13 57 26" src="https://github.com/betagouv/rdv-insertion/assets/46218316/f8572e00-b4d7-4b8f-b694-cc6e4014bdac">

2024-03-11 13:49 UTC, Michaelvilleneuve commented on app/blueprints/participation_blueprint.rb
> +  end
Pas sur de comprendre l'intention, peut-être mériterait un commentaire ?

2024-03-11 13:57 UTC, qblanc commented on app/models/concerns/rdv_participation_status.rb
> +    read_attribute(:status) == "unknown" ? unknown_status : read_attribute(:status)
non, `unknown_status` c'est une méthode. Peut-être que j'aurais du l'appeller `human_unknown_status`

2024-03-11 13:58 UTC, qblanc commented on app/blueprints/participation_blueprint.rb
> +  end
elle sert à rétablir la valeur de la db dans ce qu'on transmet à l'extérieur.

2024-03-11 14:08 UTC, aminedhobb requested changes
J'ai fait une petite review mais il faudrait garder cette logique d'affichage de texte différent en fonction de la date de rdv et du statut éloignée de la donnée et de la logique actuelle de statut

2024-03-11 14:08 UTC, aminedhobb commented on app/blueprints/participation_blueprint.rb
> +  end
`status` doit toujours renvoyer ce qui est définit dans l'enum (et donc en db), ce n'est pas une bonne idée d'override cette méthode

2024-03-11 14:08 UTC, aminedhobb commented on app/models/concerns/rdv_participation_status.rb
> +    read_attribute(:status) == "unknown" ? unknown_status : read_attribute(:status)
du coup oui on devrait plutôt changer le nom de cette méthode et renvoyer directement ce qu'il y a dans le Yaml

2024-03-11 14:08 UTC, aminedhobb commented on app/models/stat.rb
> +    participations_set.where(status: %w[seen pending needs_status_update])
ça ne marche pas correctement ici je pense

2024-03-12 09:53 UTC, aminedhobb reviewed
Merci pour les changements @qblanc 👍 , 
Je t'ai encore laissé quelques suggestions, je suis un peu pointilleux sorry mais je pense que c'est important de rester le plus clair possible si on peut sur la logique de statut

2024-03-12 09:53 UTC, aminedhobb commented on app/models/concerns/rdv_participation_status.rb
> +  def human_status
Je suis pas encore complètement d'accord avec le nom de cette méthode, je pense pas que les termes associés à l'output de cette méthode comme `needs_status_update` correspondent à un `human_status`

2024-03-12 09:53 UTC, aminedhobb commented on app/models/concerns/rdv_participation_status.rb
>    end
Vu que cette distinction sur les unknown status ne sert que pour le wording, je pense qu'on pourrait mettre directement les traduction en output de ces méthodes: 

```ruby
def human_status
  status == "unknown" ? human_unknown_status : I18n.t("activerecord.attributes.rdv.statuses.#{status}")
end 

def human_unknown_status
   I18n.t("activerecord.attributes.rdv.unknown_statuses.#{in_the_future? ? 'pending' : 'needs_status_update'}")
end

2024-03-12 09:53 UTC, aminedhobb commented on config/locales/models/rdv.fr.yml
> +          needs_status_update: Statut du RDV à préciser
comme ce ne sont pas des vrais statuts je trouverais ça plus propre de les ranger sous une clé propre `unknown_statuses` (ça va dans le sens de ma proposition précédente)

2024-03-12 10:18 UTC, Holist commented on app/models/concerns/rdv_participation_status.rb
> +  def human_status
Pour info, dans RDVS on utilise le nom de méthode : `temporal_status`

```ruby
  def temporal_status
    if status == "unknown"
      rdv_date = rdv.starts_at.to_date
      if rdv_date > Time.zone.today # future
        "unknown_future"
      elsif rdv_date == Time.zone.today # today
        "unknown_today"
      else # past
        "unknown_past"
      end
    else
      status
    end
  end
  ```

2024-03-12 10:29 UTC, qblanc commented on config/locales/models/rdv.fr.yml
> +          needs_status_update: Statut du RDV à préciser
pour le coup je vais garder ça car ça permet de mettre `pending` dans les `available_statuses` (ce qui est beaucoup plus clair pour les agents imo)

2024-03-12 10:33 UTC, qblanc commented
Ok, je suis d'accord avec tes suggestions, en effet cela permet en plus d'avoir un comportement iso avec la méthode `human_status` des `rdv_context` (une méthode qui n'était d'ailleurs pas utilisée dans les exports csvs alors qu'elle aurait pu l'être, j'en profite donc pour l'y insérer)

2024-03-13 11:11 UTC, aminedhobb requested changes
Merci pour les changements 🙏 🙏 !!
Je t'ai laissé quelques retours.

2024-03-13 11:11 UTC, aminedhobb commented on app/views/participations/_participation_status.html.erb
> +            <%= link_to "#", class: "dropdown-item", data: { value: status } do %>
Justement il faut que `available_statuses` reste également agnostique de ces états seulement lié à l'affichage. Si tu envoies `{ statuts: "pending" }`  dans le formulaire on ne saura pas le traiter

2024-03-13 11:11 UTC, aminedhobb commented on config/locales/models/rdv.fr.yml
> +          needs_status_update: Statut du RDV à préciser
pour éviter la confusion il est préférable de définir ces statuts sur une autre clé

2024-03-13 11:11 UTC, aminedhobb commented on config/locales/models/rdv.fr.yml
> +            needs_status_update: Le rendez-vous a eu lieu mais le statut n'a pas été renseigné par un agent
pareil ici

2024-03-13 11:11 UTC, aminedhobb commented on app/models/concerns/rdv_participation_status.rb
> +  def human_unknown_status
en prenant en compte le commentaire de Romain, `human_temporal_status` serait peut-être plus adapté (dans la clé du `yml` aussi du coup)

2024-03-13 11:11 UTC, aminedhobb commented on app/views/participations/_participation_status.html.erb
>                  <%= t("activerecord.attributes.rdv.statuses.#{status}") %>
du coup on serait obligé d'ajouter une méthode de helper ici pour appeler la bonne traduction

2024-03-13 13:23 UTC, qblanc commented on app/models/concerns/rdv_participation_status.rb
> +  def human_unknown_status
je ne suis pas d'accord. Effectivement la résolution dépend d'un critère temporel, mais ce que fait cette méthode, c'est transcrire le statut `unknown` en une string claire pour l'humain

2024-03-14 12:37 UTC, aminedhobb commented on config/locales/models/rdv.fr.yml
> +            pending: L'uasger a pris rendez-vous mais le rendez-vous n'a pas encore eu lieu
```suggestion
            pending: L'usager a pris rendez-vous mais le rendez-vous n'a pas encore eu lieu
```

2024-03-14 12:37 UTC, aminedhobb commented on app/helpers/users_helper.rb
> +    temporal_unknown_status = participation.in_the_future? ? "pending" : "needs_status_update"
si on utilise pas temporal dans le model il faut pas l'utiliser ici non plus :)

2024-03-14 12:37 UTC, aminedhobb commented on app/helpers/users_helper.rb
> +    participation.human_status
la logique ne devrait pas être liée à la temporalité ici aussi ?

2024-03-14 14:01 UTC, qblanc commented on app/helpers/users_helper.rb
> +    temporal_unknown_status = participation.in_the_future? ? "pending" : "needs_status_update"
l'un n'empêche pas l'autre... dans le concern on return une string humaine, ici on return un status, ça me paraît pas incohérent de pas parler de la même chose. Pour être très honnête j'aimerais bien conclure là, j'ai déjà pris en compte 99% des retours et on continue les allers retours pour pas grand chose, essaye de m'accorder certains namings dans certains cas stp, je ne dis pas que tes propositions ne sont pas bonnes mais les miennes fonctionnent très bien aussi...

2024-03-14 14:22 UTC, aminedhobb commented on app/helpers/users_helper.rb
> +    temporal_unknown_status = participation.in_the_future? ? "pending" : "needs_status_update"
Je pensais sincèrement que c'était un oubli au vu de cette remarque 

> je ne suis pas d'accord. Effectivement la résolution dépend d'un critère temporel, mais ce que fait cette méthode, c'est transcrire le statut unknown en une string claire pour l'humain

mais j'ai mal compris alors no problem

2024-03-14 14:26 UTC, aminedhobb submitted a review, later dismissed
👍

2024-03-14 14:26 UTC, aminedhobb commented on app/helpers/users_helper.rb
> +    participation.human_status
ok 👍

2024-03-14 14:58 UTC, merged