feat(index): add orientation_type filter
betagouv/rdv-insertion pull request #2084
Opened 2024-06-03 15:40 UTC by Michaelvilleneuve

Cette PR ajoute un filtre par type d'orientation

2024-06-03 15:41 UTC, Michaelvilleneuve commented on app/views/users/_users_list_header.html.erb
>            <i class="fas fa-angle-down"></i>
Ceci corrige un bug qui fait que l'icone n'est plus visible une fois filtrée

2024-06-03 15:41 UTC, Michaelvilleneuve commented on app/views/users/_users_list_header.html.erb
> +        </span>
idem ici correction du même bug

2024-06-04 16:04 UTC, aminedhobb reviewed
Une petite remarque mais sinon LGTM !

2024-06-04 16:04 UTC, aminedhobb commented on app/controllers/concerns/users/filterable.rb
> +             .where("orientations.ends_at >= ?", Time.zone.now)
il ne faut prendre en compte que les orientations du département ici. On peut combiner avec la remarque précédente et loader les orientations du département dans le controller

2024-06-05 09:22 UTC, qblanc requested changes
Moi en l'état ça ne fonctionne pas. Je pense qu'il y a besoin d'une modif - pour le reste, LGTM

2024-06-05 09:22 UTC, qblanc commented on app/controllers/concerns/users/filterable.rb
> +             .where("orientations.ends_at >= ?", Time.zone.now)
si l'orientation est active, `ends_at` est nil (en tout cas c'est ce qu'il se passez chez moi). Du coup lorsque j'essaye de filtrer je n'ai jamais aucun résultat

2024-06-05 09:22 UTC, qblanc commented on app/controllers/concerns/users/filterable.rb
> +             .where("orientations.ends_at >= ?", Time.zone.now)
quand je remplace la dernière ligne par `.where(orientations: { ends_at: nil })` ça fonctionne en revanche

2024-06-06 07:52 UTC, merged