fix(accessibility): add new mention
betagouv/rdv-insertion pull request #2099
Opened 2024-06-05 14:34 UTC by Michaelvilleneuve

Cette PR ajoute une mention dans la page d'accessibilité

<img width="1205" alt="image" src="https://github.com/betagouv/rdv-insertion/assets/4990201/cb767f21-8235-4008-8e42-cf89209d71c0">

Fix https://github.com/betagouv/rdv-insertion/issues/2043

2024-06-05 14:40 UTC, qblanc requested changes

2024-06-05 14:40 UTC, qblanc commented on app/views/static_pages/accessibility.html.erb
> +        Son schéma pluriannuel décrit les points importants sur lesquels le GIP de la plateforme de l’inclusion s’appuiera pour améliorer l’accessibilité numérique de l’ensemble de ses sites internet
`du plan d’action annuel qui détaille`
plutôt que `du plans d’action annuels qui détaillent`
`ainsi que l’état de suivi de ces actions,`

2024-06-05 14:47 UTC, Michaelvilleneuve commented on app/views/static_pages/accessibility.html.erb
> +        Son schéma pluriannuel décrit les points importants sur lesquels le GIP de la plateforme de l’inclusion s’appuiera pour améliorer l’accessibilité numérique de l’ensemble de ses sites internet
En fait c'est même plutôt `de plans d'actions` juste le du en de à change

2024-06-08 19:09 UTC, qblanc approved these changes

2024-06-09 13:51 UTC, merged