fix(users): fix action required filter
betagouv/rdv-insertion pull request #2118
Opened 2024-06-11 23:28 UTC by aminedhobb

Le filtre "intervention nécessaire" ne fonctionnait plus correctement et renvoyait des usagers avec invitations dont le délai n'était pas dépassé, probablement suite à la migration de #2056 .
Je tente ici de le réparer, et j'en profite pour mettre un index sur les `trigger` de la table invitation.

2024-06-12 15:01 UTC, Michaelvilleneuve commented on db/schema.rb
> +    t.index ["trigger"], name: "index_invitations_on_trigger"
Je pense qu'il manque ta migration

2024-06-12 15:02 UTC, Michaelvilleneuve requested changes
Tu n'as pas mis le fichier de migration pour l'ajout de ton index

2024-06-12 15:21 UTC, aminedhobb commented
> Tu n'as pas mis le fichier de migration pour l'ajout de ton index

Damn merci pour ta vigilance 🙏 !

2024-06-13 09:48 UTC, Michaelvilleneuve approved these changes
🙌

2024-06-13 10:05 UTC, merged