feat(exports): create export role for basic agents
betagouv/rdv-insertion pull request #2159
Opened 2024-06-23 22:59 UTC by qblanc

closes #2125 

Dans cette PR, j'ajoute une feature permettant d'autoriser les agents "basiques" à télécharger des exports csvs. 

Notes sur la PR :
- je me base sur la nouvelle colonne `export_authorization` pour tous les agents (admin y compris) pour autoriser les exports, je fais donc en sorte que cette colonne soit toujours set à `true` pour les admins
- comme on ne peut pas configurer ça au niveau département, je considère qu'un agent autorisé dans une organisation l'est dans toutes les orgas du département - sinon ça risque d'être laborieux pour les admins de parcourir toutes les orgas et autoriser chaque agent plusieurs fois
- les combos nom-prénom + email des agents tenaient rarement sur une ligne dans la modal, pareil pour la modal des référents ou d'assignation d'orga. J'ai donc agrandi (légèrement) la taille standard de nos modals pour un meilleur confort de lecture

<img width="1366" alt="Capture d’écran 2024-06-23 à 01 32 00" src="https://github.com/betagouv/rdv-insertion/assets/46218316/6ca948f8-2006-4518-b194-9a91224ba7b1">
<img width="672" alt="Capture d’écran 2024-06-24 à 00 57 57" src="https://github.com/betagouv/rdv-insertion/assets/46218316/d6ecbcf3-e267-40a8-8b4a-7005fe7eff55">

2024-06-24 15:38 UTC, aminedhobb requested changes
Merci pour le taff @qblanc 🔥 ! 
Bien vu d'avoir laissé cette colonne responsable de l'autorisation même quand on est admin 👍 .
Par contre je pense qu'on ne veut vraiment pas autoriser cet export pour d'autres organisations que celle dans laquelle on se trouve.
Je t'ai laissé aussi quelques suggestions de naming, LMKWYT.

2024-06-24 15:38 UTC, aminedhobb commented on app/controllers/agent_roles_controller.rb
> +  def create
on ne crée pas d'agent role ici donc cette action `agent_role#create` ne me parait pas appropriée pour ce que cette action fait.
On devrait soit faire une action custom `batch_update_export_authorizations`  et même pour être plus REST plutôt avoir un nouveau controller `export_authorizations_controller` avec une action dédiée `export_authorizations#batch_update`

2024-06-24 15:38 UTC, aminedhobb commented on app/controllers/agent_roles_controller.rb
> +    params.require(:export_authorization).permit(:organisation_id, agent_role_ids: [])
On voit bien d'ailleurs que la ressource est `export_authorization` ici

2024-06-24 15:38 UTC, aminedhobb commented on db/migrate/20240622164616_add_export_authorization_to_agent_roles.rb
> +    add_column :agent_roles, :export_authorization, :boolean, default: false
je trouve que `export_authorization` c'est plus dur à lire que `authorized_to_export_csv` qui est implicitement un booléen. Par exemple les méthodes générées `agent_role.authorized_to_export_csv?` sont plus simple à lire que `agent_role.export_authorization?`.

2024-06-24 15:38 UTC, aminedhobb commented on app/models/agent_role.rb
> +  scope :with_export_authorization, -> { where(export_authorization: true) }
pareil ici `agent_roles.authorized_to_export_csv` est plus simple cognitivement

2024-06-24 15:38 UTC, aminedhobb commented on app/models/agent_role.rb
> +  before_save -> { self.export_authorization = true }, if: -> { admin? && export_authorization == false }
nitpick: ici aussi on pourrait avoir :)
```suggestion
  before_save -> { self.authozried_to_export = true }, if: -> { admin? && !authorized_to_export? }
```

2024-06-24 15:38 UTC, aminedhobb commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +      @agent_roles_checked_to_be_authorized = agent_roles
là aussi si on peut se permettre de nommer la variable `@agent_roles_to_authorize`, c'est + digeste et le scope de l'autorisation est rappelé dans le nom de la classe

2024-06-24 15:38 UTC, aminedhobb commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +        close_export_authorizations
parei ici je trouve les termes `open` et `close` pas très parlant.

2024-06-24 15:38 UTC, aminedhobb commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +    end
Je pense qu'on ne veut pas autoriser tous l'export sur toutes les orgas de l'usager. On devrait en tous cas garder la flexibilité de ne pas le faire. 
En plus aujourd'hui notre interface supporte déjà la logique d'autoriser l'export  seulement si l'agent est autorisé à le faire dans toutes ses org, il n'y a rien à faire en + ici que de modifier la policy `export_csv?` (que tu fais ici).

2024-06-24 15:38 UTC, aminedhobb commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +    end
Je pense du coup qu'on a pas besoin de ces méthodes, on aura les `@agent_roles_to_authorize` en entrée et on devra juste avoir les `agent_roles_to_unauthorize` en faisant le diff des roles basiques de l'orga

2024-06-24 15:38 UTC, aminedhobb commented on db/migrate/20240622164616_add_export_authorization_to_agent_roles.rb
> +  end
On devrait autoriser les admins au sein de cette migration

2024-06-24 15:38 UTC, aminedhobb commented on app/views/category_configurations/index.html.erb
> +      Sélectionner les agents non-administrateurs de votre organisation qui peuvent avoir accès à la fonctionnalité d'export. Un agent autorisé l'est automatiquement pour toutes ses organisations.
Du coup faudrait enlever la dernière phrase

2024-07-03 13:25 UTC, aminedhobb reviewed
Merci @qblanc pour les changements, je trouve ça vraiment top 🙌 !
Je t'ai posé deux questions sur la logique du service et sur le naming de la ressource au niveau du controller/route.

2024-07-03 13:25 UTC, aminedhobb commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +      @basic_agent_roles_authorized_in_organisation ||= @organisation.agent_roles.basic.authorized_to_export_csv
Pourquoi est-ce qu'ici on ne prend pas tous les agent roles basic de l'organisation ? 
Comme ça ceux qu'on autorise c'est simplement ces agent roles avec les ids en entrée de ce service et ceux qu'on autorise pas c'est ces agent roles qui ne sont pas ceux données en entrée.
Ça me parait plus simple cognitivement je sais pas ce que tu en penses.

2024-07-03 13:25 UTC, aminedhobb commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +      @agent_roles_with_authorization_granted = agent_roles
du coup on pourrait passer les ids seulement sans passer les records

2024-07-03 13:25 UTC, aminedhobb commented on app/controllers/concerns/agent_roles/authorized_to_export_csv_controller.rb
> +  class AuthorizedToExportCsvController < ApplicationController
Autant je trouve ça trop bien le changement de nom du champ dans le model `agent_role`, autant ici comme nom de ressource ce serait plus commun d'appeler ça `csv_export_authorizations` non ?

2024-07-04 10:14 UTC, qblanc commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +      @basic_agent_roles_authorized_in_organisation ||= @organisation.agent_roles.basic.authorized_to_export_csv
parce que ca lance un update sur des agent roles qui n'ont pas forcément besoin d'être update. Donc je trouve ça plus clean de sélectionner seulement ceux qui ont besoin d'être update

2024-07-04 10:17 UTC, qblanc commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +      @agent_roles_with_authorization_granted = agent_roles
de toute façon il faut lancer le `update_all` sur des records et pas des ids, donc il faut bien les récupérer quelque part, je ne vois pas trop ce que ça change

2024-07-04 11:22 UTC, aminedhobb commented on app/services/agent_roles/manage_export_authorizations_for_an_organisation.rb
> +      @basic_agent_roles_authorized_in_organisation ||= @organisation.agent_roles.basic.authorized_to_export_csv
Ok merci pour l'explication 👍

2024-07-04 11:23 UTC, aminedhobb approved these changes
Merci pour les changements @qblanc 🙇‍♂️ 🚀 !!

2024-07-04 11:23 UTC, merged