fix(create): allow creation of existing applicants
betagouv/rdv-insertion pull request #239
Opened 2022-03-01 11:24 UTC by qblanc

close issue #221 
Dans cette PR, je résous deux soucis liés à la création de doublons.

**1) Création d'utilisateurs existant déjà dans une autre organisation du département**
Plutôt que d'empêcher la création de ces utilisateurs en les considérant comme des doublons, nous ajoutons désormais l'organisation qui envoie la requête à l'utilisateur, et nous updatons ses informations avec les informations fournies.

Dans applicants_controller, j'ajoute un service `FindApplicant` pour répondre correctement aux différents cas de figure (création par upload de fichier et création manuelle). 
Dans les deux cas, on veut vérifier si l'utilisateur existe par rapport à son uid ou son department internal id avant de l'instancier (en ne faisant pas ce find si ces valeurs sont nil). Si on en trouve un, il faut l'ajouter à l'organisation, ce qui normalement était fait dans le Applicant.new.
Mais dans le cas de la création via la page new, on veut aussi vérifier qu'il n'appartient pas déjà à l'application, car ce check n'est pas fait au préalable comme sur la page upload. Et si on ne le fait pas, la tentative de création de doublon via cette page ne remontrait pas d'erreur. Si l'applicant existe déjà au sein de l'organisation qui tente de le créer, on laisse le processus repartir vers le Applicant.new pour que les erreurs de validation classiques soient remontées dans le formulaire new. 
Quelle que soit la page, si l'utilisateur existe déjà mais n'est pas rattaché à l'organisation actuelle, on l'ajoute à l'organisation en updatant les champs renseignés (priorité aux informations les plus "fraîches"), et on laisse le save se dérouler normalement. 

**2) Doublons d'utilisateurs au sein d'un même fichier upload**
En modifiant la logique de création des allocataire avec le service décrit ci-dessus, des allocataires "doublon" présents dans un même fichier pourraient être créé et invités avec succès deux fois.

Pour éviter ce souci, je vérifie au moment du chargement du fichier si des doublons existent. Je gèle alors les lignes superflues, en ajoutant un texte d'explication pour aider l'agent à se décoincer s'il a besoin de créer ces utilisateurs.
![image](https://user-images.githubusercontent.com/46218316/156158759-982abae2-a75e-4d17-827e-cfdd8e0c3cc8.png)

Précision sur `checkForApplicantsDoubles`
=> J'utilise ce find et cette méthode pour que lorsqu'il y a des duplicates, il y en ait un qui ne soit pas marqué duplicate, et que sa création soit possible. Les autres sont marqués comme duplicate et leur ligne est gelée.
Je reverse l'array pour que ce soient les derniers qui soient marqués en duplicates, pas le(s) premier(s).

2022-03-01 14:03 UTC, aminedhobb requested changes
Thank you @qblanc , je t'ai fait quelques retours.

Globalement j'ai 2 remarques:
* Côté back j'ai l'impression qu'on peut faire + simple et + clair sans avoir besoin de nouveau service
* Côté front ça marche, mais là aussi on rajoute beaucoup de code et de logique alors qu'on pourrait juste refaire une recherche/update à chaque création de compte et ce serait + simple à implémenter je pense. Mais je suis moins tranché sur ça, du coup je me demandais quelle avantage nous procure la solution actuelle par rapport à celle-ci ?

2022-03-01 14:35 UTC, qblanc commented on .rubocop.yml
> +  Enabled: false
l'applicant_controller est trop long, et je vois pas trop ce que ça apporte de l'enable mais bon... On peut monter la limite si tu préfères

2022-03-01 15:08 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +  end
Je ne fais pas que ça par rapport à la page du formulaire. Si on fait ce que tu proposes (et que j'avais testé dans un premier temps) il y a plusieurs problèmes :
1) si `applicant_params[:department_internal_id]`, `applicant_params[:affiliation_number]` ou `applicant_params[:role]` n'est pas renseigné, ça remonte un allocataire random qui a un `department_internal_id` ou un `affiliation_number` qui est `nil`.
2) il faut prévoir un cas d'erreur si `applicant` existe et est déjà rattaché à l'organisation qui essaie de le créer

Du coup ça commence à prendre de la place de gérer ces cas-là, et le `applicants_controller` est déjà très long, d'où le choix d'un service.

Ok pour la remarque sur assign_attributes, j'ai pushé un changement, est-ce que ça t'irait mieux si j'organise ça comme ça (ça résout aussi le problème du nom du fichier)

2022-03-01 15:19 UTC, aminedhobb commented on .rubocop.yml
> +  Enabled: false
Yes tu peux le disable sur la classe seulement en mettant `# rubocop:disable Metrics/ClassLength` en haut du fichier

2022-03-01 16:55 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +  end
1) A partir du moment où l'on garde un service, je ne trouve pas pas qu'écrire les requêtes comme ça soient plus clair que ce que j'ai fait, au contraire même.
2) De mon point de vue, on a impérativement besoin d'un cas d'erreur : si un agent essaye de créer un.e conjoint.e alors que l'autre est déjà créé avec des coordonées différentes, et se trompe sur le rôle, il n'est absolument pas souhaitable de faire un update.
3) Si on garde le service et qu'on veut un cas d'erreur, et étant donné que le service s'appelle `FindOrInstantiateApplicant`, je trouve que le check sur l'orga a sa place dans le service : on cherche un applicant, et on l'instantie si on ne le trouve pas _ou_ si on le trouve mais qu'un applicant identique appartient déjà à cette organisation.

2022-03-02 14:07 UTC, aminedhobb reviewed
Thank you for the changes @qblanc  🙌 . 
Je t'ai fait des mini suggestions mais sinon c'est bon pour moi 💯 .

2022-03-02 14:07 UTC, aminedhobb commented on spec/services/find_or_initialize_applicant_spec.rb
> +      allow(applicant).to receive(:assign_attributes)
Du coup c'est plus le cas ici

2022-03-02 14:07 UTC, aminedhobb commented on spec/services/find_or_initialize_applicant_spec.rb
> +        end
On aurait pu tester que `subject.applicant = applicant`. 
D'ailleurs je pense que t'as pas besoin de stubber `find_by` tu peux tester directement 🐎

2022-03-02 14:07 UTC, aminedhobb commented on app/services/find_or_initialize_applicant.rb
> +  def initialize(applicant_params:, organisation:)
On a plus besoin d'`organisation` du coup.
D'ailleurs ce serait peut-être mieux de passer `department_internal_id`, `affiliation_number` et `role` directement.

2022-03-02 14:07 UTC, aminedhobb commented on app/javascript/lib/findDuplicates.js
> +  ...new Set(arr.filter((element, index, array) => array.indexOf(element) !== index)),
👍

2022-03-03 15:24 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +    # To do : if an applicant exists, return it to the agent to let him decide what to do
Le mien ne le fait pas visiblement 😂 Mais ça me fait plaisir de te faire plaisir

2022-03-03 15:27 UTC, qblanc commented on spec/services/find_or_initialize_applicant_spec.rb
> +        end
Si je stub pas `find_by` ça ne marche pas.
Je rajoute un test sur `subject.applicant = applicant`

2022-03-03 15:41 UTC, qblanc commented on app/services/find_or_initialize_applicant.rb
> +  def initialize(applicant_params:, organisation:)
👍🏻

2022-03-03 16:54 UTC, aminedhobb approved these changes
Thank you for the changes @qblanc 🚀 !

2022-03-04 11:21 UTC, qblanc commented
J'ai juste adapté les méthodes à la nouvelle refacto du fichier `ApplicantsUpload` en faisant le merge, mais à part ça il n'y a rien qui change. Je te laisse merger si tu veux checker avant.

2022-03-07 09:44 UTC, merged