fix(show page): smart_redirect_to_rdvs
betagouv/rdv-insertion pull request #276
Opened 2022-03-22 15:26 UTC by qblanc

Dans cette PR, je modifie l'assignation des organisations lorsque la navigation se fait au niveau du département afin de récupérer en priorité celle portant le dernier rendez-vous du bénéficiaire.

2022-03-22 17:33 UTC, aminedhobb requested changes

2022-03-22 17:33 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> +        @applicant.rdvs.last.organisation
Il faut garder le `policy_scope` sur les organisations ici, en faisant ça on peut potentiellement récupérer une orga à laquelle l'agent n'appartient pas.

2022-03-22 19:20 UTC, qblanc commented on app/controllers/applicants_controller.rb
> +        @applicant.rdvs.last.organisation
J'ai pushé une solution mais en rajoutant un where rubocop râlait sur l'assignment branch condition size, du coup j'ai du faire une sous-méthode, je sais pas si c'est très propre :-/

2022-03-28 10:34 UTC, aminedhobb requested changes
Il y a encore un petit souci @qblanc , je t'ai fait une suggestion d'implémentation, je te laisse voir!

2022-03-28 10:34 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> +        @applicant.rdvs.where(organisation_id: policy_scope(Organisation).pluck(:id)).last.organisation
Si la personne a un RDV mais dans une orga qui n'est pas dans le scope de l'agent, on ne récupère aucune organisation donc ça marche pas.

On pourrait peut-être avoir un scope `organisations_with_rdvs` au niveau de l'applicant, et faire l'intersection avec le policy_scope, et s'il y en a pas en récuperer une comme on le fait à la ligne 151.

2022-03-28 10:34 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
>        end
On pourra aussi ajouter un commentaire pour expliquer pourquoi on fait ça

2022-03-28 17:19 UTC, qblanc commented
Je me demande si le check sur `department: @department` aux lignes 146 et 149 pourrait être enlevé, car il me semble qu'un applicant ne peut de toute façon appartenir qu'à un département ? 
Dans le doute je l'ai laissé.

2022-03-29 08:34 UTC, aminedhobb approved these changes
LGTM 👍

2022-03-29 08:48 UTC, merged