feat(app): change resolved status to archive and add archiving_reason
betagouv/rdv-insertion pull request #282
Opened 2022-03-24 15:16 UTC by qblanc

Dans cette PR, je change le nom du statut de clôture d'un dossier de `resolved` à `archived`, et j'ajoute la possibilité d'ajouter un commentaire pour préciser le motif de l'archivage. J'en ai également profité pour simplifier l'écriture du code de la page `show` (retrait de balises pas indispensables).

Pistes de réflexions pour l'avenir (ce ne sont que des idées, mais si certaines te paraissent pertinentes on peut peut-être en faire des tickets) : 
- Faire un champ `is_archived?` sur la table `applicants` ou similaire plutôt que se servir du statut, pour permettre de continuer à consulter le statut du/des rendez-vous une fois le dossier archivé.
- Filtrer automatiquement les bRSA archivés de l'index et les regrouper dans un onglet ou une page différente (en tout cas, ne pas les afficher par défaut)
- En cas de réouverture du dossier, le motif de clôture précédemment renseigné est perdu. Il faudrait réfléchir à une solution (peut-être que les contextes aideront), ou a minima installer papertrail pour pouvoir récupérer en cas de besoin ce qui avait été inscrit.

2022-03-28 15:34 UTC, aminedhobb reviewed
Good job @qblanc , j'ai juste une remarque sur l'UX: 
La personne ne peut pas changer la raison de l'archivage à moins de rouvrir son dossier (ce qui efface la raison 😬 ) et le rouvre en en écrivant un nouveau. Est-ce que c'est fait exprès ? Parce que c'est pas top pour l'utilisateur non ? (cc @rprebot )

2022-03-28 15:34 UTC, aminedhobb commented on db/migrate/20220323164708_add_archiving_reason_to_applicants.rb
> +    add_column :applicants, :archiving_reason, :string
En général on utilise le type `text` pour ces champs-là, après vu qu'on veut pas trop de remplissage ici on peut laisser en string ça me dérange pas.

2022-03-28 15:34 UTC, aminedhobb commented on app/javascript/components/update-applicant-button.js
> +const displayUpdateStatusModal = async (updateButton) => {
Peut-être que `archive` est plus approprié que `update` dans le nom de la méthode et du bouton, WDYT?

D'ailleurs c'est pas forcément lié à cette PR mais j'ai l'impression que c'est le cas pour toutes les méthodes et le nom de ce component.

2022-03-28 15:59 UTC, qblanc commented on app/javascript/components/update-applicant-button.js
> +const displayUpdateStatusModal = async (updateButton) => {
oui pourquoi pas. En soit ça serait pas illogique de le faire passer dans cette PR

2022-03-28 16:03 UTC, qblanc commented
J'ai hésité à pouvoir "modifier" ce champ là sur la page edit, je peux le rajouter si vous voulez.
Pour le fait que la raison s'efface si on rouvre c'est un problème que je soulevais dans le descriptif de la PR, je pense qu'il faudrait qu'on trouve une solution (qui peut peut-être passer par le fait de ne pas faire de "archived" un statut mais une colonne ?)

2022-03-28 16:21 UTC, aminedhobb commented
> J'ai hésité à pouvoir "modifier" ce champ là sur la page edit, je peux le rajouter si vous voulez. Pour le fait que la raison s'efface si on rouvre c'est un problème que je soulevais dans le descriptif de la PR, je pense qu'il faudrait qu'on trouve une solution (qui peut peut-être passer par le fait de ne pas faire de "archived" un statut mais une colonne ?)

Ah mince j'avais pas lu effectivement.
Je comprends pas exactement pourquoi on est obligé d'effacer la raison, mais ce que tu proposes (faire de "archived" un statut mais une colonne) me semble nécessaire dans tous les cas, parce qu'on va déplacer le statut dans les contextes. Donc on peut le faire ici 👍

2022-03-29 14:34 UTC, qblanc commented
Ok, `is_archived` est désormais une colonne et plus un statut. J'ai fait pas mal de modifs pour gérer l'affichage en conséquence, je te laisse regarder si ça te va. En attendant de sortir les dossiers archivés de l'index (pour les mettre ailleurs), je les signale clairement.

Pour le motif d'archivage, il continue à être remis à zéro au cas où un dossier est rouvert puis ré-archivé : je pense que ça pourrait être pas mal de faire de archiving_reason un array qui permettrait de conserver l'historique, et de stocker les dates également. Cela permettrait d'afficher un historique des ouvertures/archivage de dossier avec les raisons à chaque fois. Je pense que cela pourrait être utile aux agents dans une optique de suivi des dossiers. Mais ça méritera sans doute une autre PR.
Qu'en penses-tu ?

2022-03-29 15:26 UTC, qblanc commented on app/models/applicant.rb
> +    rdv_seen: 8, deleted: 10, multiple_rdvs_cancelled: 11
Est-ce que c'est gênant d'avoir un "trou" dans l'enum ? J'ai gardé les chiffres en l'état pour ne pas avoir à modifier tous les utilisateurs ayant les status 10 et 11.

2022-03-30 09:41 UTC, aminedhobb requested changes
C'est cool @qblanc on est sur la bonne voie 👍 !

J'ai noté quelques points en plus des remarques ci-dessous: 

* L'`archiving_reason` est toujours en base quand on rouvre un dossier (ce qui est logique). Pourquoi ne pas l'afficher dans l'input de la modale lorsqu'on veut re-archiver un dossier ? Ça réglerait ce problème d'overwrite

* Lorsqu'on est sur la fiche de l'applicant au niveau du département et qu'on archive le dossier, on revient sur la fiche de l'applicant au niveau d'une organisation

* Les tests sont peut-être un peu légers pour une fonctionnalité comme ça. On pourrait au moins tester la logique d'affichage lorsque la personne est archivée

2022-03-30 09:41 UTC, aminedhobb commented on app/models/applicant.rb
> +    rdv_seen: 8, deleted: 10, multiple_rdvs_cancelled: 11
On peut peut-être le garder peut-être le temps même s'il est plus utilisé non ?
Même si je pense que ça n'a pas d'incidence de l'enlever.
Je pourrai l'enlever au moment où je déplacerai les status vers les contextes

2022-03-30 09:41 UTC, aminedhobb commented on db/migrate/20220329112332_add_is_archived_to_applicants.rb
> +    end
ah ouais là tu reset tous les statuts de tous les applicants!
Ça va prendre du temps et c'est potentiellement dangereux, faudrait le faire que sur les archivés.

On peut du coup mettre en première ligne du bloc `next unless applicant.status == 9`, WDYT?

2022-03-30 09:41 UTC, aminedhobb commented on db/migrate/20220329112332_add_is_archived_to_applicants.rb
> +      applicant.status = 9 if applicant.is_archived == true
Pareil ici on peut mettre `next unless applicant.is_archived?`

2022-03-30 09:41 UTC, aminedhobb commented on app/views/applicants/_applicant_form.html.erb
> +<% end %>
C'est bien de bien montrer que le dossier archivé, mais le code couleur et le fait d'avoir les warning c'est peut-être un peu violent non ?
Ça fait comme s'il y avait un souci alors qu'il y en a pas vraiment

2022-03-30 11:00 UTC, qblanc commented on app/views/applicants/_applicant_form.html.erb
> +<% end %>
Ok j'ai enlevé les panneaux de warning. En revanche j'ai laissé le code couleur car je veux quand même que cela soit très visible, sinon je suis persuadé qu'on va avoir des remontées du style "je n'arrive pas à relancer l'invitation, je ne comprends pas".

2022-03-30 11:01 UTC, qblanc commented on db/migrate/20220329112332_add_is_archived_to_applicants.rb
> +    end
Ah yes, j'avais mis le if sur la ligne 6 et je n'avais pas fait attention que la ligne 7 allait s'appliquer à tout le monde, my bad.

2022-03-30 12:25 UTC, qblanc commented
- Pour `archiving_reason`, étant donné qu'il peut être modifié à la main au cas où l'agent veut le modifier sans rouvrir le dossier, je ne suis pas sûr que cela ait du sens de le réafficher dans la modal si le dossier est re-archivé une deuxième fois : a priori, si il a été rouvert, c'est que le bRSA est revenu dans le process ; si il est re-archivé, ce sera pour une raison indépendante de la fois précédente.
En revanche c'est vrai qu'il n'y a pas de raison de le garder en base à la réouverture du dossier dans ce cas là: pour rester cohérent, je fais le changement pour le suprrimer. Dis moi si tu es ok avec ça. De mon point de vue, il n'y a d'intérêt de le garder en base uniquement si on en fait un historique. Sinon, on court le risque que l'agent valide avec l'ancienne raison alors que le dossier a été cloturé pour une nouvelle raison.

- J'ai fix la redirection

- J'ai ajouté un test sur la logique d'affichage

J'ai également ajouté deux choses en plus par rapport à ta précédente review :
- J'ai sorti les applicants archivés des scopes `action_required` et `attention_needed`, ainsi que des résultats filtrés par statut, ça me paraît plus logique. En attendant qu'on les sorte éventuellement carrément de la liste principale de l'index.
- J'empêche la gestion des utilisateurs archivés depuis la page d'upload (je les flag un peu comme les doublons)

2022-03-30 13:42 UTC, aminedhobb approved these changes
Ok on pourra voir à l'usage si ça gêne les départements que le motif d'archivage s'efface

2022-03-30 13:42 UTC, aminedhobb commented on spec/controllers/applicants_controller_spec.rb
> +        expect(response.body).to match(/Dossier archivé/)
on aurait pu ajouter une `archiving_reason` ici

2022-03-31 09:03 UTC, aminedhobb commented on app/controllers/concerns/filterable_applicants_concern.rb
> +    @applicants = @applicants.active.status(params[:status]) if params[:status].present?
Tu le fais déjà sur le scope le fait de récupérer que les `active` non ?

2022-03-31 09:32 UTC, qblanc commented on app/controllers/concerns/filterable_applicants_concern.rb
> +    @applicants = @applicants.active.status(params[:status]) if params[:status].present?
nope, je le fais sur les scopes `attention_need` et `action_required`, mais pas sur le scope par status. Je pourrais aussi mais je me dis que ça pourrait être utile dans d'autres cas de pouvoir chercher sur les statuts sans prendre en compte l'archivage ou non.

2022-03-31 09:44 UTC, merged