feat(app): Enable add applicant to other org with context
betagouv/rdv-insertion pull request #392
Opened 2022-05-13 16:01 UTC by aminedhobb

2022-05-16 15:43 UTC, qblanc reviewed
J'ai un peu de mal à te faire un retour sur la partie Hotwire vu que je ne connais pas la techno (et je ne suis pas dans un environnement très favorable à me former cette semaine), mais dans l'ensemble ça m'a l'air de fonctionner, même si pour l'instant j'ai une erreur de module manquant en local, mais j'imagine que ça vient de ma config que je n'ai pas encore updaté. Je t'ai laissé une question.

J'avoue que de manière générale je suis un peu sceptique sur la nécessité d'embarquer une nouvelle techno dont le bénéficie me paraît assez faible pour nous pour l'instant par rapport au coût d'apprentissage, mais peut-être que je ne vois pas tous les bénéfices qu'on peut en tirer et/ou que je surestime le coût d'apprentissage (c'est vrai que ça n'a pas l'air extrêmement compliqué non plus, encore une fois on est pas dans le meilleur environnement pour apprendre cette semaine :) )

2022-05-16 15:43 UTC, qblanc commented on Gemfile
> +
De ce que je lis sur Hotwire (je découvre), c'est présent nativement sur Rails 7, est-ce nécessaire d'installer cette gem ? D'autant que son repo est archive sur github et n'a plus été update depuis décembre.

2022-05-16 15:43 UTC, qblanc commented on app/javascript/react/components/InvitationBlock.jsx
>                <td className="px-4 py-2" colSpan={3} style={{ cursor: "pointer" }}>
Que fait ce bloc showInvitation("sms") ? Et pourquoi le garder simplement pour les sms ?

2022-05-16 16:48 UTC, aminedhobb commented
> J'avoue que de manière générale je suis un peu sceptique sur la nécessité d'embarquer une nouvelle techno dont le bénéficie me paraît assez faible pour nous pour l'instant par rapport au coût d'apprentissage, mais peut-être que je ne vois pas tous les bénéfices qu'on peut en tirer et/ou que je surestime le coût d'apprentissage (c'est vrai que ça n'a pas l'air extrêmement compliqué non plus, encore une fois on est pas dans le meilleur environnement pour apprendre cette semaine :) )

Pour moi il y a deux bénéfices clairs à passer par hotwire:

* Avoir des pages dynamiques en écrivant du ruby et sans se prendre la tête à écrire des components react avec une tonne de logique associée
* Être à la page en terme de pratiques de dev en lien avec l'ecosystème rails

Ceci dit rien n'oblige à utiliser Hotwire sur de nouvelles features s'il y en a pas besoin.
Je pense aussi qu'on va de toutes façons garder la partie React sur l'upload pour un bon moment.

2022-05-20 11:23 UTC, qblanc approved these changes

2022-05-20 11:51 UTC, qblanc requested changes
De mon côté j'ai des erreurs, je n'arrive plus à faire tourner l'app.
J'ai essayé de désinstaller tout et tout réinstaller et ça n'a pas résolu le problème, je pense qu'il y a un souci sur l'install (peut-être avec le changement de gem ? Mais ceci dit j'avais déjà des erreurs avant)
Avant j'avais des erreurs JS "Module not found" pour tous les @hotwired/blabla, maintenant j'ai également 
```
undefined method `turbo_frame_tag' for #<ActionView::Base:0x00000000018308>
```
![image](https://user-images.githubusercontent.com/46218316/169522510-cb6a6afd-8f8c-40fa-8d69-afe027cd25ef.png)

L'erreur vient peut-être de mon côté ?

2022-05-20 11:57 UTC, qblanc commented
Ok, les erreurs ont été résolues en lançant `rails turbo:install`, mais il faudrait peut-être le rajouter dans ce que fait `make install`, voire ailleurs ?

2022-05-23 08:53 UTC, aminedhobb commented
@qblanc t'avais bien lancé `yarn` et `bundle` avant de lancer l'appli ? 
C'est bizarre normalement `turbo:install` ne fait que setup les fichiers et les librairies.
Si c'est pas le cas d'ailleurs l'appli crachera sûrement au moment du déploiement, donc on peut peut-être voir comment ça se passe en demo.

2022-05-23 08:58 UTC, qblanc commented
Oui oui, j'ai même refait l'install de 0 pour vérifier (et dans le make install, il run bien `yarn`), et je l'ai aussi lancé à la main. J'ai eu le souci sur mon PC et sur mon mac.
Yes on peut essayer de déployer si tu veux, mais a minima j'ai peur qu'un nouveau développeur puisse avoir des soucis à l'install (tu pourrais essayer de désinstall et réinstall l'app en local chez toi pour vérifier si tu veux être sûr)

2022-05-23 14:00 UTC, aminedhobb commented
> Oui oui, j'ai même refait l'install de 0 pour vérifier (et dans le make install, il run bien `yarn`), et je l'ai aussi lancé à la main. J'ai eu le souci sur mon PC et sur mon mac. Yes on peut essayer de déployer si tu veux, mais a minima j'ai peur qu'un nouveau développeur puisse avoir des soucis à l'install (tu pourrais essayer de désinstall et réinstall l'app en local chez toi pour vérifier si tu veux être sûr)

Bizarre j'ai lu qu'il y avait eu effectivement un problème d'autoloader des helpers mais que sur rails 7 c'était réparé.
Bon essayons voir je reverterais le cas échéant de toutes façons

2022-05-23 14:05 UTC, merged