fix(stats): invitations not sended
betagouv/rdv-insertion pull request #399
Opened 2022-05-16 14:50 UTC by qblanc

Dans cette PR, je corrige le bug sur les nouvelles stats lorsque la méthode `first_invitation_sent_at` d'un `RdvContext` renvoie `nil`.
Je n'ai pas opté pour le SQL car je ne veux pas écarter tous les rdv_contexts qui ont une invitation avec `sent_at: nil`

2022-05-16 15:08 UTC, aminedhobb requested changes
C'est mieux si on reste le faire dans la requête comme pour les rdvs, on pourra d'ailleurs réutiliser ce scope ailleurs.

On peut faire : 
```ruby
rdv_contexts.where(applicant_id: relevant_applicants.pluck(:id))
                        .where.associated(:rdvs)
                        .with_sent_invitations
                        .distinct
 
```

et dans `rdv_context.rb`:

```ruby 

scope :with_sent_invitations, -> { where(id: joins(:invitations).where.not(invitations: { sent_at: nil }).pluck(:rdv_context_id)) }

```

2022-05-20 11:17 UTC, qblanc commented
Je pensais qu'en faisant ça il allait enlever les rdv_contexts dès qu'il y aurait une invitation avec `sent_at: nil` dedans.
J'ai fait le scope (en utilisant `associated` pour que ce soit plus simple), mais je n'ai pas mis le pluck, cela me parait curieux de ne renvoyer que des ids alors que la méthode est sensée juste scoper des rdv_contexts.

2022-05-23 08:27 UTC, aminedhobb commented
> J'ai fait le scope (en utilisant `associated` pour que ce soit plus simple), mais je n'ai pas mis le pluck, cela me parait curieux de ne renvoyer que des ids alors que la méthode est sensée juste scoper des rdv_contexts.

Utiliser le scope `associated` donne une requête un peu différente (on vérifie en plus que l'id n'est pas nul), c'est overkill ici: 

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/7602809/169775554-47e3c74d-78d8-4d45-89ac-d7efb03f7fc2.png">

Par contre oui pas besoin de la requête supplémentaire avec les ids 👍

2022-05-23 08:56 UTC, qblanc commented
J'ai viré le associated

2022-05-23 09:26 UTC, aminedhobb approved these changes
🙇

2022-05-23 09:27 UTC, merged