feat(app): change invited_before_time_window & last invitation date display
betagouv/rdv-insertion pull request #413
Opened 2022-05-31 09:09 UTC by qblanc

Dans cette PR, je modifie la logique d'affichage de la date de dernière invitation sur l'index bénéficiaires : plutôt que de l'afficher dès qu'il y a plusieurs invitations, elle n'est désormais affichée que s'il y a plusieurs invitations *et* que la date de première et de dernière invitation sont différentes. (#407)
Je modifie également le calcul de `invited_before_time_window?` afin qu'il se fasse à partir de la date de première invitation plutôt que sur celle de la dernière invitation, afin que le "compteur" ne soit pas remis à zéro en cas de relance. (#393)

2022-05-31 11:58 UTC, aminedhobb requested changes
Il y a une erreur de typo par rapport à l'affichage de la dernière invitation mais sinon c'est cool 👍 . 
On aurait pu aussi afficher les 2 dates sans trop se prendre la tête mais si tu penses que c'est plus lisible comme ça ça me va 👍 .

Pour ce qui est du fait de compter à partir de la première invitation, je pense qu'il faut aussi changer le scope `:invited_before_time_window` sur les `rdv_contexts` pour avoir la même logique

2022-05-31 11:58 UTC, aminedhobb commented on app/views/applicants/_applicants_list.html.erb
> +                  <td><%= show_last_invitation_date?(rdv_context) ? display_attribute(format_date(rdv_context.last_invitation_sent_at)) : "-" %></td>
Tu mets deux fois la dernière invitation ici

2022-05-31 13:43 UTC, qblanc commented on app/views/applicants/_applicants_list.html.erb
> +                  <td><%= show_last_invitation_date?(rdv_context) ? display_attribute(format_date(rdv_context.last_invitation_sent_at)) : "-" %></td>
🙊

2022-05-31 15:04 UTC, qblanc commented
J'ai fait les modifs demandées. Pour le scope de `:invited_before_time_window` je ne sais pas si on ne pourrait pas faire un peu plus efficace comme requête mais je n'ai pas réussi à trouver mieux, n'hésite pas à me dire si tu vois mieux.

2022-06-01 12:43 UTC, aminedhobb requested changes
Je t'ai fait une remarque sur le scope, et j'en profite pour faire quelques remarques ici pêle-mêle:

> Pour le scope de :invited_before_time_window je ne sais pas si on ne pourrait pas faire un peu plus efficace comme requête mais je n'ai pas réussi à trouver mieux, n'hésite pas à me dire si tu vois mieux.

* A première vu je pense que le scope peut être tout simplement: 

```ruby
joins(:invitations).where("invitations.sent_at < ?", number_of_days_before_action_required.days.ago)
```

Seulement il y a un cas que ça prend pas en compte: Si la personne a une RDV honoré, puis qu'elle est réinvitée à prendre rdv, elle sera toujours dans le scope `action_required` vu que sa première invitation sera fatalement antérieure au nombre de jours limite.

C'est compliqué de le faire à partir d'un scope parce qu'il faudrait récupérer pour chaque context qui un rdv honoré la date du rdv pour ne prendre en  compte que les invitations au delà de cette date. On peut peut-être juste exclure ces contextes là dans le scope ?

* Par contre on devrait au moins le mettre dans la méthode `invited_before_time_window?`, c'est plus facile pour un record donné

* Il faudrait changer l'update automatique du statut [ici](https://github.com/betagouv/rdv-insertion/blob/3e52af2083c74fd1bb9bfe892e5a1a527d7ae0e4/app/javascript/react/components/InvitationBlock.jsx#L36) quand on relance l'invite. Il ne faut changer le texte que dans les cas où le statut n'est pas déjà `invitation_pending`

* Il faudrait ajouter des tests plus précis, c'est pas normal que de changer cette logique ne fasse pas péter les tests

2022-06-01 12:43 UTC, aminedhobb commented on app/models/rdv_context.rb
> +      .where.not(id: Invitation.sent_in_time_window(number_of_days_before_action_required).pluck(:rdv_context_id).uniq)
Je suis pas sûr de comprendre ton scope `RdvContext.includes(:invitations).select(&:first_sent_invitation).map(&:id)` 🤔  . 
En gros ici tu récupères les `rdv_contexts` qui ont des invitations envoyées comme dans une `:with_sent_invitations` sauf que c'est de manière bcp plus complexe vu que tu itères sur tous les contextes et toutes les invitations.

2022-06-02 15:42 UTC, aminedhobb commented on app/models/concerns/invitable_concern.rb
> -    last_invitation_sent_at && last_invitation_sent_at < number_of_days_before_action_required.days.ago
A mon avis la logique aurait plus ça place ici. On aurait quelque chose du style: 

```ruby 
def invited_before_time_window?(number_of_days_before_action_required)
  invitation_date_to_compare = \
    if last_seen_rdv.present?
      invitations.select { |invitation| invitation.sent_at > last_seen_rdv.starts_at }.map(&:sent_at).compact.min
    else
      first_invitation_sent_at
    end
  invitation_date_to_compare  && invitation_date_to_compare  < number_of_days_before_action_required.days.ago
end
```

2022-06-02 15:46 UTC, aminedhobb commented on app/models/rdv_context.rb
>    scope :with_sent_invitations, -> { where(id: joins(:invitations).where.not(invitations: { sent_at: nil })) }
D'ailleurs là non plus, c'était une erreur de ma part :)

2022-06-02 15:47 UTC, aminedhobb commented on app/models/rdv_context.rb
> +    first_invitation_sent_at = invitations.select(&:sent_at).min_by(&:sent_at).sent_at
Du coup on aurait pas besoin de cette ligne

2022-06-02 16:04 UTC, qblanc commented on spec/models/rdv_context_spec.rb
> +      end
Je ne trouve pas, la logique que l'on vient de changer aurait modifié le résultat d'un des deux tests mais pas de l'autre si ils avaient existé il me semble

2022-06-02 16:07 UTC, qblanc commented on app/models/concerns/invitable_concern.rb
> -    last_invitation_sent_at && last_invitation_sent_at < number_of_days_before_action_required.days.ago
j'ai hésité entre les deux. Mais à mon sens sur l'index, une fois qu'une invitation a été relancée après un rdv honoré, on veut aussi afficher la "nouvelle" date de première invitation, non ?

2022-06-02 16:07 UTC, qblanc commented on app/models/rdv_context.rb
> +    where(id: joins(:invitations).where("invitations.sent_at < ?", number_of_days_before_action_required.days.ago))
si on en a besoin, car `invited_before_time_window` est réutilisé dans un autre scope et sans ça ça ne marche pas

2022-06-02 16:12 UTC, qblanc commented on app/models/rdv_context.rb
> +    where(id: joins(:invitations).where("invitations.sent_at < ?", number_of_days_before_action_required.days.ago))
L'erreur qu'on a quand je l'enlève : `Relation passed to #or must be structurally compatible. Incompatible values: [:joins]`

2022-06-02 17:25 UTC, qblanc commented
Ok j'ai répondu à tes remarques et essayer de prendre en compte tes retours. J'ai fait en sorte que `first_sent_invitation` continue de toujours renvoyer la date de première invitation, mais j'ai créé une méthode `first_current_invitation` (on peut peut-être améliorer le nom), car je pense que pour l'index notamment on doit aussi changer la logique d'affichage une fois qu'une invitation a été relancée après un rdv honoré.

2022-06-07 16:37 UTC, qblanc commented on app/models/concerns/invitable_concern.rb
> +  def first_current_invitation_sent_at
pas génial non plus 😂 Mais vendu, on ne trouvera rien d'idéal je pense de toute façon

2022-06-07 19:07 UTC, aminedhobb approved these changes
Merci pour les modifs @qblanc !
Je t'ai fait deux commentaires mineurs mais je marque comme "approved" 👍

2022-06-07 19:07 UTC, aminedhobb commented on app/helpers/applicants_helper.rb
> +    if rdv_context.last_seen_rdv.present? && rdv_context.status != "rdv_seen"
nitpick: tu peux utiliser le helper que rails inclus avec les enum et utiliser `rdv_context.rdv_seen?` plutôt que `rdv_context.status != "rdv_seen"`

2022-06-07 20:30 UTC, merged