feat(invitation letter): allow fully customable signature
betagouv/rdv-insertion pull request #417
Opened 2022-06-01 16:33 UTC by qblanc

Dans cette PR, je permet la personnalisation intégrale de la signature de la lettre d'invitation. Par défaut, c'est le nom du département qui est utilisé.
Pour les départements ayant une signature configurée par rapport au nom de leur responsable, elle est persistée dans la nouvelle colonne.

2022-06-02 08:26 UTC, aminedhobb reviewed
C'est cool merci @qblanc 👍 .
Peut-être qu'on supprimera la table `responsibles` plus tard aussi

2022-06-02 08:26 UTC, aminedhobb commented on app/views/letters/_signature.html.erb
> +          <%= address_line %>
y a écrit `addess_line` ici

2022-06-02 08:26 UTC, aminedhobb commented on db/migrate/20220601160812_add_letter_signature.rb
> +    Organisation.all.each do |organisation|
Il faudrait encadrer ça dans un `up_only`

2022-06-02 16:00 UTC, aminedhobb approved these changes
👍

2022-06-06 16:09 UTC, qblanc commented
Pour permettre la personnalisation de la signature de l'email (issue #385), j'ai déplacé `signature_lines` dans `configuration` plutôt que `letter_configuration`, et j'ai fait les changements afférents. Une signature custom, si elle est configurée, sera désormais utilisée de la même façon pour les mails et les courriers.

2022-06-07 10:12 UTC, aminedhobb requested changes
Merci @qblanc pour l'ajout.
J'ai fait pas mal de commentaires, je pense notamment qu'on a un problème au niveau de l'archi et qu'il faut faire attention à mieux structurer tout ça.
Si tu veux et que tu penses que mes propositions sont ok, je peux prendre le relais à partir de là pour essayer de mettre ça en place.

2022-06-07 10:12 UTC, aminedhobb commented on db/migrate/20220601160812_add_letter_signature.rb
> +    add_column :configurations, :signature_lines, :string, array: true
Je pense pas que cette colonne ait sa place dans la table `configurations` car elle ne dépend pas du contexte.
A mon avis on devrait éviter de complexifier la table `configurations` et lui assigner trop de choses (mais ça vient probablement du nom du modèle qui est trop vague).
Je serais tenté de renommer la table `LetterConfiguration` en `InvitationParameters` et y ajouter `signature_lines` et `sms_sender_name` (et donc renommer `sender_name` en `letter_sender_name`).
T'y vois un inconvénient ?

2022-06-07 10:12 UTC, aminedhobb commented on app/views/common/_invitations_signature.html.erb
> +<% else %>
Pour les mails le "à bientôt" est peut-être redondant avec la signature, WDYT ? 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/7602809/172354741-c7e6cac2-4abd-4561-8685-60bdbeecf6c8.png">

2022-06-07 10:18 UTC, qblanc commented on app/views/mailers/invitation_mailer/invitation_for_rsa_accompagnement.html.erb
> +<%= render 'common/invitations_signature', configuration: @invitation.organisations.last.configurations.find_by(context: @invitation.context), department: @invitation.department %>
yes j'avais corrigé ça dans la seconde PR.

2022-06-07 14:41 UTC, aminedhobb approved these changes
C'est top @qblanc merci pour les changements ! J'ai l'impression que cette abstraction rend les choses plus lisibles ! 

L'implémentation est nickel, j'ai laissé 2 mini commentaires ça a l'air tout bon 👏

2022-06-07 14:41 UTC, aminedhobb commented on app/services/invitations/generate_letter.rb
> +      @invitation.invitation_parameters
On pourrait mémoizer `invitation_parameters` ici pour pas faire la requête plusieurs fois

2022-06-07 15:33 UTC, aminedhobb approved these changes

2022-06-07 15:34 UTC, merged