feat(stats): change orientation in less than 30 days calculation
betagouv/rdv-insertion pull request #431
Opened 2022-06-07 07:53 UTC by qblanc

Dans cette PR, je change la méthode de calcul des bRSA orientés en - de 30 jours, pour ne prendre en compte que la période relative à leur présence sur RDV-Insertion

2022-06-08 10:10 UTC, aminedhobb approved these changes
👍

2022-06-08 15:16 UTC, aminedhobb requested changes
Pardon @qblanc je suis allé un peu vite sur la review.
La méthode `applicants_oriented_in_less_than_30_days` fait toujours appel à la méthode `orientation_delay_in_days` qui n'a pas été mise à jour..

2022-06-08 17:11 UTC, qblanc commented
Bien vu

2022-06-09 12:06 UTC, aminedhobb reviewed
Du coup on devrait peut-être plus parler d'`oriented` mais de `seen` dans les différentes méthode ?

2022-06-09 20:04 UTC, qblanc commented
J'ai fait le changement de wording pour enlever la notion d'orientation, mais je trouve que ce n'est pas une très bonne idée en fait, ça apporte davantage de confusion qu'autre chose.
A mon sens on pourrait garder la notion "d'orientation" dans le code pour désigner la logique du calcul de délai de rdv_seen en - de 30 jours, parce que ça nous permet de choisir les rdv_contexts pertinents etc et qu'au final c'est une bonne manière de définir ce qu'on essaye de calculer dans la logique de l'app (si on oublie la définition "officielle" d'une "orientation).
Est-ce que tu peux regarder le dernier commit (peut-être que je n'ai juste pas trouvé les bons nommages) et me dire ce que tu en penses ?

2022-06-13 10:25 UTC, aminedhobb reviewed
Effectivement la formulation actuelle porte à confusion, mais je pense qu'en fait on peut/doit calculer ce délai pour tous types de rdvs et ce sera direct plus clair.

2022-06-13 10:25 UTC, aminedhobb commented on app/models/applicant.rb
> +    rdv_contexts.reject(&:rsa_orientation_on_phone_platform?).flat_map(&:rdvs)
Si on calculait cette stat pour les orientations sur plateforme téléphonique je vois pas de raisons de changer maintenant.
On peut donc garder tous les rdvs sur les 3 contextes.

2022-06-13 15:10 UTC, aminedhobb approved these changes
Merci pour les changements @qblanc ! Ça m'a l'air bon modulo une petite remarque 🙌

2022-06-13 15:26 UTC, aminedhobb approved these changes

2022-06-13 15:27 UTC, merged