feat(app): add archived tab on applicants index
betagouv/rdv-insertion pull request #528
Opened 2022-09-08 09:56 UTC by qblanc

Dans cette PR, je rajoute un onglet "Archivés" qui regroupe les utilisateurs archivés du département ou de l'organisation sélectionnée. En conséquent, ces utilisateurs ne sont plus montrés dans les onglets par contexte.

2022-09-08 15:30 UTC, qblanc commented
Je peux le faire si tu veux mais je ne suis pas persuadé de l'intérêt de cette solution. Concrètement, cela permettra d'enlever une condition pour `set_current_configuration` et `set_current_motif_category`, mais les conditions devront rester pour `set_applicants` et `set_rdv_contexts`. Et ce qu'on affiche reste un index d'applicants. 
Du coup au final ca donne une solution non REST qui économise peu de lignes de code.
Qu-est-ce que tu en penses ?

2022-09-08 16:19 UTC, aminedhobb commented
> Je peux le faire si tu veux mais je ne suis pas persuadé de l'intérêt de cette solution. Concrètement, cela permettra d'enlever une condition pour `set_current_configuration` et `set_current_motif_category`, mais les conditions devront rester pour `set_applicants` et `set_rdv_contexts`. Et ce qu'on affiche reste un index d'applicants. Du coup au final ca donne une solution non REST qui économise peu de lignes de code. Qu-est-ce que tu en penses ?

Dans ta solution actuelle, la route `/applicants` renvoie les personnes archivées. Tu utilises comme condition la présence de paramètre sur les catégories de motif (et donc de configuration) pour afficher ou non les personnes archivées, c'est pas du tout clair.
L'idée d'avoir une nouvelle route c'est pour avoir une route `/archived` plutôt qu'une route `/applicants?is_archived=true`. Surtout parce que cette route ne dépend pas des `rdv_contexts` il me semble ni des catégories de motifs. 
Et effectivement, si on veut rester REST le plus propre serait d'avoir un nouveau controller `ArchivedController` et y implémenter un `index` :).

2022-09-12 13:40 UTC, qblanc commented
@aminedhobb j'ai pris en compte tes remarques, j'ai créé un `ArchivedApplicantsController`. Du coup, pour éviter de répéter des méthodes dans les deux controllers, j'en ai déplacé un certain nombre dans des concerns. J'ai aussi adapté les tests en conséquence.

2022-09-12 17:43 UTC, aminedhobb requested changes
Merci @qblanc , je t'ai fait quelques retours.
C'est pas si évident que ça de trouver la meilleure solution de mettre ça en place, j'essaierai de faire un truc en liaison avec ce que t'as commencé à faire et ce j'ai fait aujourd'hui [ici](https://github.com/betagouv/rdv-insertion/pull/534) et voir si on peut partir de là.

2022-09-12 17:43 UTC, aminedhobb commented on app/controllers/archived_applicants_controller.rb
> +  end
Du coup ce serait bien de ne pas avoir besoin de faire ça 😬

2022-09-12 17:43 UTC, aminedhobb commented on app/controllers/archived_applicants_controller.rb
> +                  .preload(:organisations, rdv_contexts: [:invitations, :rdvs])
Je pense pas qu'on aurait besoin de preloader tout ça du coup

2022-09-12 17:43 UTC, aminedhobb commented on app/views/applicants/_applicants_list.html.erb
> +      <%= link_to "Archivés", compute_archived_index_path(@organisation, @department), class: "nav-link #{@all_configurations.map(&:id).include?(@current_configuration&.id) ? '' : 'active'}" %>
Je ne comprends pas la condition `@all_configurations.map(&:id).include?(@current_configuration&.id)`

2022-09-12 17:43 UTC, aminedhobb commented on config/routes.rb
> +    resources :archived_applicants, only: [:index]
Il serait préférable d'avoir une route namespacé par les `applicants` ici, du style `/applicants/archived`

2022-09-12 17:43 UTC, aminedhobb commented on config/routes.rb
> +    resources :archived_applicants, only: [:index]
same here

2022-09-12 17:59 UTC, qblanc commented on app/controllers/archived_applicants_controller.rb
> +      format.html { render "applicants/index" }
Mmmm en effet, intéressant.
En revanche je pense que la logique de filtres, même si elle aura peut-être besoin d'être retravaillée, peux tout de même rester pertinente sur cette page.

2022-09-12 18:01 UTC, qblanc commented on app/views/applicants/_applicants_list.html.erb
> +      <%= link_to "Archivés", compute_archived_index_path(@organisation, @department), class: "nav-link #{@all_configurations.map(&:id).include?(@current_configuration&.id) ? '' : 'active'}" %>
Si cette condition est remplie, cela veut dire que l'un des autres onglets est actif, puisque c'est "l'inverse" de cette logique qui est utilisée pour les mettre en `active` ; si ce n'est pas le cas, alors on veut que cet onglet soit actif (mais si on décorelle les html, on peut faire différemment)

2022-09-12 18:03 UTC, qblanc commented on config/routes.rb
> +    resources :archived_applicants, only: [:index]
OK ; en revanche je pense qu'il vaut mieux garder le nom que j'ai choisi pour le controller (`ArchivedController` n'est pas précis je trouve)

2022-09-15 16:29 UTC, aminedhobb commented
Je ferme au profit de #540

2022-09-15 16:29 UTC, closed without merging