feat(invitations) add follow up motif and texts for follow up & insertion offer invitations
betagouv/rdv-insertion pull request #565
Opened 2022-09-27 12:33 UTC by qblanc

Dans cette PR, j'ajoute le motif `rsa_follow_up` pour les rendez-vous de suivi, et je rajoute les textes pour les invitations relatives à ce motif et au motif `insertion_offer`. Je modifie également quelques détails d'autres textes pour garder plus de cohérence sur la rédaction (l'utilisation de RDV/rendez-vous, notamment).

2022-09-27 13:53 UTC, aminedhobb requested changes
Pas grand chose à ajouter sur la forme mais les textes ne correspondent pas à ce qui a été précisé dans l'issue. Pour l'offre d'insertion pro il n'y a notamment pas de notion d'expiration.
Il me semble également que la catégorie RDV de suivi n'est pas présente sur RDV-S (mais ça peut être fait en parallèle)

2022-09-27 13:53 UTC, aminedhobb commented on app/services/concerns/invitations/sms_content.rb
> +        "suivant dans un délai de #{number_of_days_to_accept_invitation} jours: " \
Il n'y a pas de notion de délai pour l'offre d'insertion pro. C'est d'ailleurs précisé dans le message [ici](https://github.com/betagouv/rdv-insertion/issues/556)

2022-09-27 13:53 UTC, aminedhobb commented on app/services/concerns/invitations/sms_content.rb
> +        "Le lien de prise de RDV suivant expire dans #{@invitation.number_of_days_before_expiration} jours: " \
Pareil ici

2022-09-27 13:53 UTC, aminedhobb commented on app/services/concerns/invitations/sms_content.rb
> +        "#{number_of_days_to_accept_invitation} jours: " \
Il y a pas de notion de jours d'acceptation [dans l'issue](https://github.com/betagouv/rdv-insertion/issues/556), à vérifier.

2022-09-27 13:53 UTC, aminedhobb commented on app/views/letters/invitation_for_rsa_follow_up.html.erb
> +  <p>Ce code d'invitation est valable <span class="bold-blue"><%= invitation.number_of_days_to_accept_invitation %> jours</span> à réception de ce courrier.</p>
Je suis pas fan de cette formulation parce que c'est pas vrai.
La notion de devoir prendre rdv dans les XX jours est discutable aussi mais moins incorrect sémantiquement parlant.

2022-09-27 13:53 UTC, aminedhobb commented on app/views/letters/invitation_for_rsa_insertion_offer.html.erb
> +  <p>Ce code d'invitation est valable <span class="bold-blue"><%= invitation.number_of_days_to_accept_invitation %> jours</span> à réception de ce courrier.</p>
Pareil pour l'offre d'insertion

2022-09-27 15:57 UTC, qblanc commented on app/services/concerns/invitations/sms_content.rb
> +        "suivant dans un délai de #{number_of_days_to_accept_invitation} jours: " \
Il y en avait pour la relance, j'avais demandé avec Rémi ; je l'enlève.

2022-09-27 16:02 UTC, qblanc commented
Pour les textes : ils étaient incohérents, et j'avais vérifié avec Rémi ce qu'il préférait, j'avais bien lu l'issue...
Pour la formulation de la lettre : les deux formulations sont fausses, il n'y en a pas une qui l'est moins que l'autre ^^ Mais comme la prise du rendez-vous est facultative, je l'ai privilégiée à "vous devez prendrez rendez-vous dans les XX jours"

2022-09-27 16:25 UTC, qblanc commented
D'ailleurs je ne vois pas non plus bien la logique qui ferait que l'on ne ferait pas expirer les liens pour les rendez-vous de suivi (ou même pour les ateliers) : il y a un moment où les agents vont positionner un rendez-vous eux-même si le bRSA ne répond pas à l'invitation, et on voudra éviter des doublons de rendez-vous, cela ne me parait donc pas logique de ne pas mettre de durrée de validité.

2022-09-27 16:48 UTC, aminedhobb commented
> D'ailleurs je ne vois pas non plus bien la logique qui ferait que l'on ne ferait pas expirer les liens pour les rendez-vous de suivi (ou même pour les ateliers)

Pour les RDVs de suivi je ne sais pas c'est à vérifier comme j'ai dit, pour les ateliers par contre il ne faut pas parler d'expiration. Ces RDVs de sont pas obligatoires et le process n'est pas le même, il n'y a pas de convocation. @rprebot l'explique bien [ici](https://mattermost.incubateur.net/betagouv/pl/mtrxhfux3tyrbdtqxxcxcz6yhc). Nous on pourra mettre une expiration à 365 jours mais il n'y a pas à la mentionner. D'ailleurs on ne fera pas de relance pour ces rdvs, le texte de relance est présent le temps qu'on rende la relance paramétrable si j'ai bien compris.

>  les deux formulations sont fausses, il n'y en a pas une qui l'est moins que l'autre ^^ Mais comme la prise du rendez-vous est facultative, je l'ai privilégiée à "vous devez prendrez rendez-vous dans les XX jours"

Les 2 formulations pour moi ne sont pas bonnes. Je disais juste que le fait de "devoir prendre rdv" restait interprétable par rapport au process du département, alors que le fait que le code ne soit plus valable au bout de 3 jours est faux. 
Mais bon ça revient un peu au même, on peut peut-être juste rester homogène sur la formule le temps de trouver mieux ?

2022-09-28 08:55 UTC, qblanc commented
Ok, j'ai enlevé la notion de délai pour les rendez-vous d'offre d'insertion (mais pas pour les RDV de suivi), et j'ai changé le wording pour les lettres, je te laisse checker si ça te va.

2022-09-29 09:54 UTC, aminedhobb approved these changes
LGTM 👍

2022-10-03 08:08 UTC, merged