feat(app): Send convocations
betagouv/rdv-insertion pull request #588
Opened 2022-10-10 16:43 UTC by aminedhobb

Cette PR est liée aux issues #480 , #481  et #482 et gère le mécanisme d'envoi de notifications à la prise de rdvs. 
On gère ici l'envoi en fonction des différents évènements (création, annulation et modification), sur différents formats (SMS et email). On gère également l'affichage de la date de la dernière convocation sur la page index et des différents formats de convocation sur la page show.

### Mécanisme

J'ajoute une colonne `convocable` à la table `rdvs` qui est un booléen égal à `false` par défaut.
Lorsque l'on reçoit et traite un webhook de rdv (dans le `RdvSolidaritesWebhooks::ProcessRdvJob`), on assigne ce booléen au record de `rdv`. 
On marque le rdv comme convocable seulement si: 
* Le rdv vient d'être créé (on considère que la nature convocable d'un rdv ne change pas au cours du temps)
* La convocation est activée dans la configuration correspondante (colonne `convene_applicant`, anciennement appelée `notify_applicant`)
* Le motif du Rdv comporte le mot "convocation"

Ainsi je rajoute un callback `after_commit` au model Rdv pour que, quand un `rdv` est créé/modifié et que celui-ci est notifiable (= convocable), on enqueue un job `NotifyApplicantsToRdvJob` qui va envoyer les notifications aux formats correspondants.
Les notifications ne sont envoyées que si le rdv vient d'être créé, s'il a été annulé ou si l'adresse où l'horaire a changé. On ne veut pas envoyer de notifications pour des changements non impactant.

### Envois de messages

La logique d'envois de messages étant similaire pour les invitations et les notifications, j'ajoute deux services `Messengers::SendSms` et `Messengers::SendEmail` qui vont être appelés par les services d'envoi de sms et de mails des notifications et des invitations.

**Aussi, pour ne pas avoir à écrire les 5 messages de notifications (en fonction de l'event et si le rdv est présentiel et par téléphone) pour chaque catégorie de motif j'introduis un fichier YAML `settings/motif_category.yml` (qui est loadé par un objet ruby `Settings::MotifCategory`) qui récupère les infos à mettre dans ces messages.** 
L'idée serait de faire la même chose pour les invitations. Le fait de réécrire chaque message nous apporte certes + de flexibilité mais rend aussi ce code là + difficile à modifier et à maintenir.
 
### Les changements non liées directement aux issues citées

Il y a certains changements de cette PR qui ne sont pas "directement" liés à l'envoi de notificatitons: 

* Renommage des concerns pour être plus en phase avec la ["Rails way" de nommer les concerns](https://world.hey.com/jorge/code-i-like-iii-good-concerns-5a1b391c).
* Renommage de la table `invitation_parameters` en `messages_configuration` puisque cette configuration est aussi utilisée pour les notifications

### Previews 📸 

* Exemple de mail envoyé pour la création d'un rdv d'accompagnement en présentiel 
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/7602809/194914747-38b57ab5-c2c5-42a6-8fea-72415af90d75.png">

* page index 

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/7602809/194914976-f912d561-13ca-4230-b685-12665bbd5daa.png">

* Page show 

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/7602809/194915059-f7a0c3f6-a8f7-4e15-aa0d-39f8c50d86df.png">

2022-10-12 15:08 UTC, qblanc requested changes
Je n'ai pas regardé les tests, mais pour le reste voilà mes retours. Dans l'ensemble c'est top, quelques questions et/ou remarques sur l'implem. Une autre question plus générale par rapport à la description de la PR :

> La convocation est activée dans la configuration correspondante (colonne convene_applicant, anciennement appelée notify_applicant)
Le motif du Rdv comporte le mot "convocation"

Pourquoi "doubler" la condition ? Est-ce que la première condition ne serait pas suffisante, pour être moins dépendant du nom du motif

2022-10-12 15:08 UTC, qblanc commented on app/views/mailers/notification_mailer/presential_rdv_created.html.erb
> +<p>Vous êtes bénéficiaire du RSA et à ce titre vous avez été convoqué(e) à un <%= @rdv_title %>.</p>
En soit on a l'info si c'est un homme ou une femme, on pourrait mettre le e en conditionnel par rapport à cette variable (sauf si c'est plus inclusif comme ça)

2022-10-12 15:08 UTC, qblanc commented on app/views/mailers/notification_mailer/presential_rdv_created.html.erb
> +<p>Vous êtes attendu(e) <span class="font-weight-bold">le <%= @rdv.formatted_start_date %> à <%= @rdv.formatted_start_time %></span> ici: </p>
Je trouve que "ici" est une formulation assez brute/brutale. On pourrait peut-être mettre "à l'adresse suivante", par exemple ?

2022-10-12 15:08 UTC, qblanc commented on app/views/mailers/notification_mailer/presential_rdv_updated.html.erb
> +<p>Vous êtes attendu(e) <span class="font-weight-bold">le <%= @rdv.formatted_start_date %> à <%= @rdv.formatted_start_time %></span> ici: </p>
pareil ici pour le "ici" (et dans tous les messages suivants)

2022-10-12 15:08 UTC, qblanc commented on config/settings/motif_category.yml
> +  rdv_title_by_phone: rendez-vous téléphonique afin de construire et signer votre Contrat d'Engagement Réciproque
"pour" plutôt que "afin de" ? (un peu plus léger)

2022-10-12 17:25 UTC, aminedhobb commented on app/jobs/notify_rdv_to_applicant_job.rb
> +          .where("sent_at > ?", 1.hour.ago).count > 1
C'est pour garder un semblant d'idempotence sur ce job: Je veux surtout éviter que le job fail et se lance 1000 fois pour une quelconque erreur et envoie 1000 fois le sms. 
Après le choix de 2 changements par heure est un peu arbitraire, on peut augmenter le nombre de changements et/ou diminuer la fenêtre.

2022-10-12 19:51 UTC, aminedhobb commented on app/services/invitations/send_email.rb
> +        mailer_method: mailer_method,
Je pense que `mailer_method` est plus clair que `invitation_type` qui pourrait être confondu avec le format ou autre

2022-10-12 22:28 UTC, aminedhobb commented on app/models/applicant.rb
> -  include HasRdvsConcern
Ok done here: https://github.com/betagouv/rdv-insertion/pull/588/commits/02a96d4a71ff055c3f769fe7fadbf2fbf479fe0d

2022-10-12 22:28 UTC, aminedhobb commented on app/helpers/applicants_helper.rb
> +    else
C'est pas forcément en cas d'échec, c'est aussi si la personne n'a pas de numéro de tel mobile ou d'email. Donc "RDV-Insertion a échoué à prévenir le bénéficiaire" marche pas dans ces cas-là.
Mais on peut trouver mieux, si t'as d'autres propositions let me know.

2022-10-12 22:28 UTC, aminedhobb commented on app/jobs/notify_applicant_job.rb
> +      @rdv.notifications.sent.where(event: "rdv_updated", format: @format).where("sent_at > ?", 1.hour.ago).count > 1
C'est pour garder un semblant d'idempotence sur ce job: Je veux surtout éviter que le job se relance 1000 fois à cause  d'une quelconque erreur et envoie 1000 fois le sms. 
Après le choix de 2 changements par heure est un peu arbitraire, on peut jouer sur le nb de changements et la durée.

2022-10-12 22:28 UTC, aminedhobb commented on app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb
> -    end
Ah oui bien vu je sais pas ce qu'il s'est passé j'ai fait nimp 🤔 . Merci en tous cas je l'ai supprimé ici: https://github.com/betagouv/rdv-insertion/pull/588/commits/02a96d4a71ff055c3f769fe7fadbf2fbf479fe0d

2022-10-12 22:29 UTC, aminedhobb commented on app/jobs/rdv_solidarites_webhooks/process_rdv_job.rb
> +      verify_lieu_sync! if rdv_convocable?
Parce qu'il est important que le lieu soit à jour au moment où on envoie la convocation.
Les lieux ne sont pas utilisés dans d'autres cas, donc il est moins important que le cache soit à jour à la minute près.

2022-10-12 22:29 UTC, aminedhobb commented on app/mailers/notification_mailer.rb
> +    return if @applicant.phone_number_is_mobile?
indeed nice catch 👍 ! Corrigé ici: https://github.com/betagouv/rdv-insertion/pull/588/commits/02a96d4a71ff055c3f769fe7fadbf2fbf479fe0d

2022-10-12 22:29 UTC, aminedhobb commented on config/settings/motif_category.yml
> +  rdv_title: rendez-vous de suivi avec votre référent de parcours
Hmm il y a pas toujours "dans le cadre de votre RSA", donc il vaut peut-être mieux garder cette précision.

2022-10-12 22:29 UTC, aminedhobb commented on app/mailers/notification_mailer.rb
> +      subject: "[Important] Vous êtes convoqué(e) à un #{@rdv_title} dans le cadre de votre RSA"
Ok mais du coup j'ai viré "dans le cadre de votre RSA" dans l'objet

2022-10-12 22:30 UTC, aminedhobb commented on app/models/applicant.rb
> -  has_and_belongs_to_many :rdvs
Je suis vraiment partagé sur ça, parce que dans les concerns on incorpore toute la logique sur ces relations, ça me parait donc pas illogique que la relation elle-même y figure. 
Mais j'ai pas d'avis hyper tranché donc j'ai quand même fait le changement ici: https://github.com/betagouv/rdv-insertion/pull/588/commits/02a96d4a71ff055c3f769fe7fadbf2fbf479fe0d

2022-10-12 22:30 UTC, aminedhobb commented on app/models/messages_configuration.rb
> +                              presence: true
Nope bien vu 🙌 ! Corrigé ici: https://github.com/betagouv/rdv-insertion/pull/588/commits/02a96d4a71ff055c3f769fe7fadbf2fbf479fe0d

2022-10-12 22:30 UTC, aminedhobb commented on app/models/organisation.rb
> +  belongs_to :sms_configuration, optional: true
Indeed merci pour ta vigilance !

2022-10-12 22:30 UTC, aminedhobb commented on app/models/rdv_solidarites/motif.rb
> +    end
Non c'est pas prévu. 
Je pense que là c'est moins embêtant, ces rdvs ne sont pas réservable en ligne et la mention "convocation" est moins contraignante que "rsa orientation". Ça permet également de bien différencier les motifs pour lesquels on convoque.

2022-10-12 22:30 UTC, aminedhobb commented on app/services/concerns/invitations/sms_content.rb
> +    end
Y a pas vraiment de règles, mais oui c'est mieux j'ai rajouté pour `help_phone_number` et `number_of_days_before_expiration` ici: https://github.com/betagouv/rdv-insertion/pull/588/commits/02a96d4a71ff055c3f769fe7fadbf2fbf479fe0d

2022-10-12 22:30 UTC, aminedhobb commented on app/services/concerns/notifications/sms_content.rb
> +    end
Le YAML ne store que la règle "je montre" ou "je ne montre pas" dans les variables `display..` mais pas la phrase en question

2022-10-12 22:31 UTC, aminedhobb commented on app/services/invitations/send_email.rb
> +        mailer_method: mailer_method,
Je pense que `mailer_method` est plus précis que `invitation_type` qui pourrait être confondu avec le format ou autre

2022-10-12 22:31 UTC, aminedhobb commented on app/services/messengers/send_email.rb
> +      @sendable = sendable
Non parce que `sendable` fait bien référence a un objet qui inclut le  module `Sendable`, soit un `sendable` qui n'est n'importe quel objet ou record

2022-10-12 22:32 UTC, aminedhobb commented on app/views/mailers/notification_mailer/by_phone_rdv_updated.html.erb
> +<p>Un travailleur social vous appellera <span class="font-weight-bold">le <%= @rdv.formatted_start_date %> à <%= @rdv.formatted_start_time %></span> sur votre numéro de téléphone: <span class="font-w
C'est ce qu'on avait pour l'Yonne, mais à vérifier avec l'équipe 👍

2022-10-12 22:32 UTC, aminedhobb commented on app/views/mailers/notification_mailer/presential_rdv_created.html.erb
> +<p>Vous êtes bénéficiaire du RSA et à ce titre vous avez été convoqué(e) à un <%= @rdv_title %>.</p>
Oui j'y ai pensé, on pourra le faire si besoin mais c'est peut-être plus inclusif comme ça

2022-10-12 22:33 UTC, aminedhobb commented on app/views/mailers/notification_mailer/presential_rdv_created.html.erb
> +<p>Vous êtes attendu(e) <span class="font-weight-bold">le <%= @rdv.formatted_start_date %> à <%= @rdv.formatted_start_time %></span> ici: </p>
Pour les mails ok c'est mieux, pour les sms ça nous rajoute pas mal de caractères. J'ai fait le changement pour les mails ici: https://github.com/betagouv/rdv-insertion/pull/588/commits/02a96d4a71ff055c3f769fe7fadbf2fbf479fe0d

2022-10-12 22:33 UTC, aminedhobb commented on config/settings/motif_category.yml
> +  rdv_title_by_phone: rendez-vous téléphonique afin de construire et signer votre Contrat d'Engagement Réciproque
oui ok 👍

2022-10-12 22:35 UTC, aminedhobb commented
> Je n'ai pas regardé les tests, mais pour le reste voilà mes retours. Dans l'ensemble c'est top, quelques questions et/ou remarques sur l'implem. 

Merci pour la review 🙌 ! 
J'ai répondu à tes questions et fait des changements ici : https://github.com/betagouv/rdv-insertion/pull/588/commits/02a96d4a71ff055c3f769fe7fadbf2fbf479fe0d

> Une autre question plus générale par rapport à la description de la PR :
> 
> > La convocation est activée dans la configuration correspondante (colonne convene_applicant, anciennement appelée notify_applicant)
> > Le motif du Rdv comporte le mot "convocation"
> 
> Pourquoi "doubler" la condition ? Est-ce que la première condition ne serait pas suffisante, pour être moins dépendant du nom du motif

Parce que sinon on enverrait des notifications pour tous les rdvs, même ceux pris en autonomie par l'usager, et c'est pas ce qu'on veut 😬

2022-10-13 07:29 UTC, qblanc commented on app/views/mailers/notification_mailer/presential_rdv_created.html.erb
> +<p>Vous êtes attendu(e) <span class="font-weight-bold">le <%= @rdv.formatted_start_date %> à <%= @rdv.formatted_start_time %></span> ici: </p>
Top merci. Sinon peut-être encore mieux (et plus court, donc applicable au SMS) : on fait deux lignes, avec :
`Date du RDV : <%= @rdv.formatted_start_date %> à <%= @rdv.formatted_start_time %>`
ou `RDV le : <%= @rdv.formatted_start_date %> à <%= @rdv.formatted_start_time %>`
et `Lieu du RDV: <%= @rdv.lieu.name %> - @rdv.lieu.address`
Ce n'est pas crucial, mais je trouve vraiment le "ici" pas du tout naturel et très agressif

2022-10-13 07:41 UTC, qblanc commented on app/helpers/applicants_helper.rb
> +    else
On ne pourrait pas store l'erreur quelque part et l'afficher plus clairement ? ie, si c'est parce qu'il n'y a  pas de numéro/d'email, ça explique qu'il n'y a pas de numéro/d'email ; si c'est un fail de l'envoi, ça l'explicite, etc.

2022-10-13 08:34 UTC, aminedhobb commented on app/helpers/applicants_helper.rb
> +    else
Ben du coup si y a pas d'envoi y a pas forcément d'erreurs 😬 .
Je pense que ce qui est important ici c'est d'attirer l'attention sur le fait qu'on ait pas envoyé de notifs, quelque soit la raison.

2022-10-13 08:45 UTC, aminedhobb commented on app/views/mailers/notification_mailer/presential_rdv_created.html.erb
> +<p>Vous êtes attendu(e) <span class="font-weight-bold">le <%= @rdv.formatted_start_date %> à <%= @rdv.formatted_start_time %></span> ici: </p>
Ça fait un peu + robotique et plus proche des messages de RDV-S ta proposition. 
C'est marrant je trouve pas ça vraiment agressif pour un sms, mais je trouve pas de bon synonyme pas trop long 😬 .

2022-10-13 12:21 UTC, aminedhobb commented
Let's go 🚀 !

2022-10-13 12:21 UTC, merged