fix applicant_title omission in sms
betagouv/rdv-insertion pull request #771
Opened 2023-01-19 10:07 UTC by Holist

Fix https://github.com/betagouv/rdv-insertion/issues/755
Et un oubli dans cette PR : https://github.com/betagouv/rdv-insertion/pull/747

2023-01-19 17:29 UTC, aminedhobb approved these changes
🚀 💪

2023-01-19 17:29 UTC, aminedhobb commented on Gemfile.lock
> +  arm64-darwin-21
Je pense que t'es pas à jour avec `staging`

2023-01-20 09:51 UTC, qblanc requested changes
Juste une petite remarque de mon côté :)

2023-01-20 09:51 UTC, qblanc commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
Du coup le `rdv_subject` pourrait être `demande d'emploi`, mais l'objet du mail commencerait quand même par `[RSA]`. Il faudrait peut-être rajouter une variable supplémentaire, quelque chose comme `mail_slug` ou un autre nom, qu'en pensez-vous ?

2023-01-23 09:48 UTC, aminedhobb commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
Yes bien vu on en avait d'ailleurs parlé avec Romain avant 👍 . Pour moi ça reste le `rdv_subject` entre crochet, je vois pas de raison de rajouter un autre ?

2023-01-23 10:00 UTC, qblanc commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
Oui mais dans ce cas là il faut a minima la `capitalize` sinon ça fera `demande d'emploi` quand ce n'est pas le RSA. Mais je trouve ça un peu bizarre l'expression `Demande d'emploi` entre crochet, je suis le seul ?

2023-01-23 10:03 UTC, aminedhobb commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
Moi ça me choque pas mais si c'est problématique on pourra utiliser une autre méthode

2023-01-24 08:51 UTC, Holist commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
Merci Quentin pour cette remarque. Ca ne me choque pas particulièrement non plus. Je vais faire les modifs.

2023-01-24 11:39 UTC, Holist commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
C'est pas bon avec la methode capitalize. On a un comportement qui n'est pas souhaitable. "[RSA]" devient "[Rsa]"...
Du coup je peux mettre une nouvelle variable (mail_slug par exemple oui) qui ne sera utilisé qu'ici et on peut remplacer "[Demande d'emploi]" par "[SPIE]" ? Vous en pensez quoi ?

2023-01-24 13:23 UTC, qblanc commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
Pour moi SPIE ça ne va vraiment pas. Mais on peut mettre `upcase` à la place de `capitalize` et avoir [RSA] et [DEMANDE D'EMPLOI]. Sinon on peut aussi enlever cette partie entre crochets au pire.
D'ailleurs en écrivant ça ça me fait penser : est-ce qu'on ne devrait pas plutôt parler de "recherche d'emploi" que de "demande d'emploi" ??

2023-01-24 13:24 UTC, aminedhobb commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
Oui dans [la PR](https://github.com/betagouv/rdv-insertion/pull/774) que je viens de merger j'utilise `upcase` du coup. 
Mais ici ça peut faire bizarre en effet "[DEMANDE D'EMPLOI]" en majuscule.
Je sais pas si `mail_slug` serait le terme qui correspond, peut-être `rdv_subject_abbreviation`.
Il faut vérifier si on veut vraiment rendre visibile le terme SPIE pour le bénéficiaire.

2023-01-24 14:09 UTC, Holist commented on app/mailers/invitation_mailer.rb
> +      subject: "[RSA]: Votre #{@rdv_title} dans le cadre de votre #{@rdv_subject}"
Je vais utiliser upcase sur rdv_subject comme dans ta PR même si c'est un peu "lourd" d'avoir demande d'emploi tout en MAJ. On ajoutera une nouvelle variable si besoin.

2023-01-24 16:16 UTC, aminedhobb approved these changes
👍

2023-01-25 10:04 UTC, qblanc approved these changes

2023-01-25 10:58 UTC, merged