feat(organisations) Pouvoir changer d'organisation depuis l'index.
betagouv/rdv-insertion pull request #825
Opened 2023-02-07 13:08 UTC by Holist

close #805 
Pas vraiment complexe mais ca va être pratique aussi.
A voir dans le cas ou il y a vraiment bcp d'orgas la tête de la dropdown.
![Capture d’écran 2023-02-07 à 14 00 10](https://user-images.githubusercontent.com/28594222/217253290-928a03a4-64a3-4427-be36-6d7dd299ec59.png)

2023-02-07 17:35 UTC, qblanc requested changes
Merci Romain ! Bonne idée de le mettre à cet endroit là, ça s'intègre bien.

2023-02-07 17:35 UTC, qblanc commented on app/views/applicants/_applicants_list_header.html.erb
> +      <% if @department.organisations.length > 1%>
il faudrait regarder par rapport aux organisations de l'agent plutôt que celles du département je pense.

2023-02-07 17:35 UTC, qblanc commented on app/views/applicants/_applicants_list_header.html.erb
> +            <% end %>
Ici je mettrais plutôt "Toutes les organisations" plutôt que le nom du département

2023-02-08 08:52 UTC, Holist commented on app/views/applicants/_applicants_list_header.html.erb
> +      <% if @department.organisations.length > 1%>
Effectivement...

2023-02-08 10:01 UTC, Holist commented on app/controllers/applicants_controller.rb
> -    return unless department_level?
Je ne suis pas certain de l'utilité de cette ligne qui m'embêtait pour accéder au scope des orgas depuis le département.

2023-02-08 10:20 UTC, aminedhobb reviewed
Merci @Holist 🙌 !
Je t'ai fait une suggestion mais ça m'a l'air cool sinon 👍 !

2023-02-08 10:20 UTC, aminedhobb commented on app/views/applicants/_applicants_list_header.html.erb
> +            <%= link_to department_applicants_path(@department) do %>
On pourrait passer un `motif_category_id` dans le lien (comme on fait dans l'index des orgas), en prenant la première catégorie dans la chronologie du parcours

2023-02-08 10:20 UTC, aminedhobb commented on app/views/applicants/_applicants_list_header.html.erb
> +              <%= link_to organisation_applicants_path(organisation) do %>
Pareil ici

2023-02-08 10:20 UTC, aminedhobb commented on app/controllers/applicants_controller.rb
> -    return unless department_level?
Je pense que c'était juste parce que ce n'était pas nécessaire dans le contexte d'une orga

2023-02-08 10:57 UTC, Holist commented on app/views/applicants/_applicants_list_header.html.erb
> +            <%= link_to department_applicants_path(@department) do %>
J'y ai pensé mais c'est pas le fonctionnement par défaut si on ne spécifie pas de motif_category_id justement ?

2023-02-08 12:56 UTC, qblanc commented on app/views/applicants/_applicants_list_header.html.erb
> +            <%= link_to department_applicants_path(@department) do %>
>> On pourrait passer un motif_category_id dans le lien (comme on fait dans l'index des orgas), en prenant la première catégorie dans la chronologie du parcours

Pas vraiment le scope de cette PR mais si tu fais ça tu pourrais en profiter pour modifier le `motif_category_id` dans les liens de l'index des orgas, afin de résoudre [ce ticket](https://github.com/betagouv/rdv-insertion/issues/767)

2023-02-08 12:57 UTC, qblanc approved these changes
🕺

2023-02-08 13:04 UTC, aminedhobb commented on app/views/applicants/_applicants_list_header.html.erb
> +            <%= link_to department_applicants_path(@department) do %>
> J'y ai pensé mais c'est pas le fonctionnement par défaut si on ne spécifie pas de motif_category_id justement ? (dans set_all_configurations)

Oui c'est vrai, ça vient juste du fait que je voulais pas qu'on tombe sur une 404 si on a pas de `motif_category` dans l'url.
Après c'est peut-être un comportement qu'on veut, que lorsqu'on aille sur `/applicants` on tombe sur la première catégorie de motif et donc ne pas avoir à préciser la catégorie (auquel cas pour le ticket que mentionne Quentin il ne faudrait juste pas passer de catégorie de motif).
Je suis preneur de vos avis là-dessus.

2023-02-08 13:30 UTC, Holist commented on app/views/applicants/_applicants_list_header.html.erb
> +            <%= link_to department_applicants_path(@department) do %>
Les 2 solutions ont des avantages/inconvénient.
Je trouve ça assez logique de tomber sur la première catégorie par défaut même sans le params et ça fait moins de code.

2023-02-08 14:28 UTC, aminedhobb approved these changes

2023-02-09 14:47 UTC, aminedhobb approved these changes
🙌

2023-02-09 15:33 UTC, merged