Feat/add inclusion connect
betagouv/rdv-insertion pull request #898
Opened 2023-03-09 18:32 UTC by Holist

Close #78 

Dans cette PR je met en place Inclusion Connect pour RDV Insertion.
L'idée est d'utiliser le système précédemment mis en place d'authentification via secret partagé pour les appels API de RDV-S.
On s'affranchit du système par token devise de RDV-S qui n'est pas utilisable avec les agents Inclusion Connecté.

2023-03-13 10:57 UTC, aminedhobb reviewed
Merci @Holist 🙌 !
Je t'ai laissé des commentaires / suggestions, dispo pour en discuter quand tu veux !

2023-03-13 10:57 UTC, aminedhobb commented on app/controllers/concerns/authenticated_controller_concern.rb
> +    set_rdv_solidarites_session_for_inclusion_connected_agents if session[:connected_with_inclusionconnect]
à mon avis on devrait mettre en session la signature de l'agent et l'uid au moment de recevoir le callback d'inclusion connect.

2023-03-13 10:57 UTC, aminedhobb commented on app/controllers/concerns/authenticated_controller_concern.rb
>        client: session["rdv_solidarites"]["client"]
du coup ici il faut passer le `x_agent_auth_signature` aussi. On pourrait éventuellement rajouter un booléen pour voir si la personne s'est inclusion connectée

2023-03-13 10:57 UTC, aminedhobb commented on app/controllers/concerns/rdv_solidarites_session_concern.rb
> +      )
C'est pour l'API que tu fais ça ? 
Je pense pas qu'on en ait besoin ici (ce concern est utilisé que sur l'API et le session controller).

2023-03-13 10:57 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +    @current_agent = agent
Je pense pas qu'il y ait besoin de faire ça, mettre l'id en session devrait suffire

2023-03-13 10:57 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +      x_agent_auth_signature: nil,
Du coup on mettrait la signature ici

2023-03-13 10:57 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +    session[:connected_with_inclusionconnect] = true
On pourrait mettre ça dans la méthode `set_session_credentials_for_inclusion_connect`

2023-03-13 10:57 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +    redirect_to root_path
```suggestion
    redirect_to session.delete(:agent_return_to) || root_path
```
Comme dans le `sessions_controller`

2023-03-13 10:57 UTC, aminedhobb commented on app/models/rdv_solidarites_session.rb
> +  attr_accessor :x_agent_auth_signature
Je suis pas sûr qu'on ait envie de le changer depuis l'extérieur du coup

2023-03-13 10:57 UTC, aminedhobb commented on app/services/inclusion_connect.rb
> +module InclusionConnect
Je préférerais qu'on garde dans les services les services objects qui descendent du `BaseService` et qui ne réponde qu'à une méthode.
On pourrait en faire une classe qui irait dans `app/models/`

2023-03-13 10:57 UTC, aminedhobb commented on app/services/inclusion_connect.rb
> +        nonce: Digest::SHA1.hexdigest("Something to check when it come back ?"),
```suggestion
        nonce: Digest::SHA1.hexdigest("Something to check when it comes back ?"),
```

2023-03-13 10:57 UTC, aminedhobb commented on app/services/inclusion_connect.rb
> +    def agent(code, inclusion_connect_callback_url)
```suggestion
    def find_agent(code, inclusion_connect_callback_url)
```
?

2023-03-13 10:57 UTC, aminedhobb commented on app/services/inclusion_connect.rb
> +      user_info = get_user_info(token)
on peut peut-être parler d'`agent_info` ici pour être cohérent

2023-03-13 10:57 UTC, aminedhobb commented on app/services/inclusion_connect.rb
> +      response = Net::HTTP.post_form(uri, data)
Je sais que c'est le code présent sur RDV-S mais on a la gem `Faraday` pour faire des requêtes un peu plus facilement, on pourrait l'utiliser ici plutôt que d'utiliser la librairie standard :)

2023-03-13 10:57 UTC, aminedhobb commented on app/services/inclusion_connect.rb
> +      return false unless response.is_a?(Net::HTTPSuccess)
Pareil ici

2023-03-13 16:03 UTC, Holist commented on app/controllers/concerns/authenticated_controller_concern.rb
>        client: session["rdv_solidarites"]["client"]
J'ai un peu de mal à comprendre l'utilité d'un booléen dans notre cas ?
Est ce que le flag `session[:connected_with_inclusionconnect]` n'est pas suffisant ?

2023-03-13 16:05 UTC, Holist commented on app/controllers/concerns/rdv_solidarites_session_concern.rb
> +      )
Effectivement en appliquant les recommandations de ta review ce n'est plus nécessaire.

2023-03-13 16:08 UTC, Holist commented on app/controllers/concerns/authenticated_controller_concern.rb
> +    set_rdv_solidarites_session_for_inclusion_connected_agents if session[:connected_with_inclusionconnect]
Cette ligne a été supprimée et n'est plus pertinente mais concernant ton commentaire, je pense que c'est déjà fait dans la methode `set_session_credentials_for_inclusion_connect` dans `InclusionConnectController`

2023-03-14 11:13 UTC, aminedhobb commented on app/models/inclusion_connect.rb
> +
Tu peux laisser des méthodes de classes comme avant ici du coup ;)

2023-03-14 13:58 UTC, Holist commented on app/models/inclusion_connect_session.rb
> +  def initialize(uid, x_agent_auth_signature)
Il y a une raison pour laquelle on utilise pas de symbol ici ?

2023-03-14 14:00 UTC, aminedhobb commented on app/models/inclusion_connect_session.rb
> +  def initialize(uid, x_agent_auth_signature)
Non c'est un oubli bien vu!

2023-03-16 11:05 UTC, aminedhobb submitted a review, later dismissed
Trop bien merci @Holist 🙌 !
Les stubs de 3rd party API n'ont plus aucun secret pour toi à ce que je vois :D.

J'ai juste une question: Est-ce que les sessions IC sont censés avoir une durée définie ? Parce que là une fois que l'agent se log on ne définit pas de durée d'expiration de session et il pourra continuer d'utiliser tant que le browser est ouvert. Il faudrait peut-être définir une durée de session.

2023-03-16 14:31 UTC, Holist commented on spec/models/inclusion_connect_session_spec.rb
> +        RdvSolidaritesSession.from(:inclusion_connect).with(
Pas directement, à priori car new est en methode privée pour InclusionConnectSession.
J'ai une préférence pour cette facon d'appeler la sesssion dans le test car c'est aussi comme ca que l'on fait dans le code.

2023-03-16 14:42 UTC, Holist commented on spec/controllers/inclusion_connect_controller_spec.rb
> +    stub_const("InclusionConnect::BASE_URL", base_url)
Bonne question :) 
En stubant la variable d'environnement dans le before avec ça :
    `allow(ENV).to receive(:fetch).with("SHARED_SECRET_FOR_AGENTS_AUTH").and_return("S3cr3T")`
J'avais des erreurs liées au stub des requêtes Faraday et je n'ai pas trop cherché à le résoudre.
Du coup j'ai modifié en mettant le stub du shared secret uniquement dans le test qui en avait besoin.

2023-03-16 15:16 UTC, Holist commented
> Trop bien merci @Holist 🙌 ! Les stubs de 3rd party API n'ont plus aucun secret pour toi à ce que je vois :D.
> 
> J'ai juste une question: Est-ce que les sessions IC sont censés avoir une durée définie ? Parce que là une fois que l'agent se log on ne définit pas de durée d'expiration de session et il pourra continuer d'utiliser tant que le browser est ouvert. Il faudrait peut-être définir une durée de session.

Merci :) Il y a une durée d'expiration du token coté inclusion-connect (60 jours à priori en démo, faut que je regarde en prod à combien il est). Je peux le mettre en place dans cette PR ou dans une autre. Ou se trouve notre propre logique d'expiration des connexions d'ailleurs ?

2023-03-23 11:16 UTC, tonial commented on app/models/inclusion_connect_client.rb
> +      JSON.parse(response.body)["access_token"]
Il faut récupérer l'id_token pour la deconnexion 
voir https://github.com/betagouv/itou-inclusion-connect/blob/dev/docs/inclusion_connect.md#r%C3%A9ponse-1

2023-03-24 10:21 UTC, Holist commented on app/models/inclusion_connect_client.rb
> +      JSON.parse(response.body)["access_token"]
Merci :)

2023-03-27 16:09 UTC, aminedhobb requested changes
Merci @Holist , je t'ai laissé quelques suggestions, je pense qu'on peut améliorer un peu notre mécanisme, tu me diras ce que tu en penses :).

2023-03-27 16:09 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +    if response["error"].nil? && set_session(response)
Peut-être qu'on pourrait utiliser un service `RetrieveInclusionConnectAgentInfos` qui, à partir du `code`, fait l'appel à InclusionConnect et renvoie le record `agent` et le `inclusion_connect_token_id`.
Ça permettra de gérer plus facilement les cas où l'appel échoue, ou quand l'agent n'est pas retrouvé en DB.

2023-03-27 16:09 UTC, aminedhobb commented on app/controllers/sessions_controller.rb
> +    return unless logged_with_inclusion_connect? || session[:agent_id].present?
Je ne suis pas sûr de comprendre cette condition et dans quels cas on veut pas enlever les identifiants de session.

2023-03-27 16:09 UTC, aminedhobb commented on app/models/inclusion_connect_client.rb
> +    end
Il y a que cette méthode qu'on pourrait laisser différente du coup des autres du coup

2023-03-28 09:20 UTC, Holist commented on app/controllers/inclusion_connect_controller.rb
> +    if response["error"].nil? && set_session(response)
Effectivement, ca sera plus propre. Je m'en occupe.
Juste une précision, quand tu dis renvoyer l'agent et le token_id. Juste pour être sur, c'est à dire que faire un call du service renverrai les 2 éléments sous forme de hash par exemple. { agent: "un objet agent", inclusion_token_id: 12345 }

2023-03-28 15:30 UTC, Holist commented on app/controllers/inclusion_connect_controller.rb
> +    if response["error"].nil? && set_session(response)
Merci pour ton commentaire. J'ai appliqué ta proposition et effectivement le code est beaucoup plus clair comme ca.

2023-03-28 16:07 UTC, Holist commented on app/controllers/sessions_controller.rb
> +    return unless logged_with_inclusion_connect? || session[:agent_id].present?
Effectivement, cette ligne n'a plus rien à faire ici.

2023-03-28 16:17 UTC, Holist commented on app/models/inclusion_connect_client.rb
> +    end
Tu as complètement raison. 🙇  C'était flou. C'est beaucoup plus clair maintenant avec le nouveau service et le `Client::InclusionConnect` qui contient plus que les appel Faraday. Les tests étaient aussi beaucoup plus facile à implémenter.

2023-03-29 16:44 UTC, aminedhobb reviewed
Merci @Holist pour les changements 🙌 !
Je t'ai laissé quelques dernières remarques mais c'est vraiment que des petites remarques de style 💪  !

2023-03-29 16:44 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +    if result.errors.empty? && @agent
nitpick: 
Tu peux englober l'appel au service `RetrieveInclusionConnectAgentInfos` dans une méthode plutôt que dans une variable, comme on le fait sur des autres controller. Ça donne qq chose d'un peu plus clair je trouve: 

```ruby

def callback
  if retrieve_inclusion_connect_infos.success?
    set_session_credentials
    redirect_to session.delete(:agent_return_to) || root_path
  else
    handle_failed_authentication(retrieve_inclusion_connect_infos.errors.join(", "))
  end
end

private

def retrieve_inclusion_connect_infos
  @retrieve_inclusion_connect_infos ||=  RetrieveInclusionConnectAgentInfos.call(
     code: params[:code], callback_url: inclusion_connect_callback_url
   )
end

def agent 
  retrieve_inclusion_connect_infos.agent
end

2023-03-29 16:44 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +    redirect_to sign_in_path
```suggestion
    handle_failed_authentication("Failed to authenticate agent with InclusionConnect : Invalid State")
```

2023-03-29 16:44 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +    redirect_to sign_in_path
Du coup il faut juste que `handle_failed_authentication` prenne un string en entrée.

2023-03-29 16:44 UTC, aminedhobb commented on app/models/client/inclusion_connect.rb
> +  CLIENT_ID = ENV["INCLUSION_CONNECT_CLIENT_ID"]
Il y a déjà un namespace `app/clients/` où on place nos clients, on pourrait le mettre là (pardon c'était peut-être pas clair dans ma dernière review)

2023-03-29 16:44 UTC, aminedhobb commented on app/models/client/inclusion_connect.rb
> +      def connect(code, inclusion_connect_callback_url)
est-ce que cette action devrait pas plutôt s'appeler `verify_token` que `connect` ? 
J'ai l'impression qu'elle ne fait que vérifier le token mais je me trompe peut-être.

2023-03-29 16:44 UTC, aminedhobb commented on app/services/retrieve_inclusion_connect_agent_infos.rb
> +  def connect_body
il faudrait éventuellement renommer ces méthodes par rapport à ma remarque précédente

2023-03-29 16:44 UTC, aminedhobb commented on app/services/retrieve_inclusion_connect_agent_infos.rb
> +    fail!("Inclusion Connect Error: Email not verified") unless agent_info_body["email_verified"]
nitpick:  j'aurais tendance à dire que cette ligne ne devrait pas appartenir à cette méthode mais c'est pas très grave

2023-03-29 16:44 UTC, aminedhobb commented on app/services/retrieve_inclusion_connect_agent_infos.rb
> +    result.agent.presence || fail!("Agent doesnt exist in rdv-insertion")
```suggestion
    result.agent.presence || fail!("Agent doesn't exist in rdv-insertion")
```

2023-03-29 16:44 UTC, aminedhobb commented on app/services/retrieve_inclusion_connect_agent_infos.rb
> +    fail!("Inclusion Connect API Error : Connexion failed")
```suggestion
    fail!("Inclusion Connect API Error : Token verification failed")
```

2023-03-29 16:44 UTC, aminedhobb commented on app/services/retrieve_inclusion_connect_agent_infos.rb
> +  end
En général les méthodes qui finissent par `!` dans les services c'est pour les méthodes qui peuvent fail.

2023-03-29 16:44 UTC, aminedhobb commented on app/controllers/sessions_controller.rb
>    end
On pourrait mettre que l'appel API dans cette méthode et dire `if logout_inclusion_connect.success?` dans la méthode `destroy`

2023-03-29 16:44 UTC, aminedhobb commented on app/controllers/sessions_controller.rb
> +    end
On pourrait limite mettre le logout inclusion dans un before action
```ruby
  def handle_inclusion_connect_logout
     return if logout_inclusion_connect.success?

     flash[:error] = "Nous n'avons pas pu vous déconnecter d'Inclusion Connect. Contacter le support à l'adresse \
                        <data.insertion@beta.gouv.fr> si le problème persiste."
    redirect_to root_path
 end

```

2023-03-30 07:53 UTC, Holist commented on app/models/client/inclusion_connect.rb
> +  CLIENT_ID = ENV["INCLUSION_CONNECT_CLIENT_ID"]
J'avais pas fait attention effectivement :) C'est modifié

2023-03-30 07:56 UTC, Holist commented on app/models/client/inclusion_connect.rb
> +      def connect(code, inclusion_connect_callback_url)
Effectivement j'étais pas trés inspiré pour cette methode :)
Ce serait même plutôt `get_token` en fait.
Le token est vérifié dans `get_agent_info`.
Je vais changer dans ce sens.

2023-03-30 08:12 UTC, Holist commented on app/controllers/sessions_controller.rb
>    end
Effectivement... 😓

2023-03-30 13:27 UTC, aminedhobb approved these changes
Ça m'a l'air nickel du coup merci pour ta patience 🙌 !
Je t'ai laissé 2 mini commentaires mais c'est top 🚀 !

2023-03-30 13:27 UTC, aminedhobb commented on app/controllers/inclusion_connect_controller.rb
> +    redirect_to sign_in_path
du coup je crois que cette méthode a pas été changée

2023-03-30 13:27 UTC, aminedhobb commented on app/services/retrieve_inclusion_connect_agent_infos.rb
> +  def email_verified!
j'aurais plus dit `check_email_verified!` ici pour montrer ce que ça fait.
Et je pense qu'on peut même l'appeler depuis `call`.

2023-03-30 14:52 UTC, aminedhobb approved these changes

2023-03-30 15:01 UTC, merged