Feat/Front for mail invitations
betagouv/rdv-insertion pull request #91
Opened 2021-10-10 19:23 UTC by qblanc

Cette PR modifie le front de la page d'ajout des allocataires via l'upload de fichiers en créant différents boutons pour les différentes phases de l'invitation : Création du compte, Invitation par SMS, Invitation par mail.

Quelques modifications visuelles du front également, afin de commencer à harmoniser certains designs et couleurs (aperçu du résultat sur les captures d'écran ci-dessous)

![image](https://user-images.githubusercontent.com/46218316/136710273-a13f7051-21e1-49d8-ac6c-72b3a25bc3a0.png)
![image](https://user-images.githubusercontent.com/46218316/136709613-c4f1a9ab-f25c-4917-90af-c2f51b3e6842.png)

2021-10-12 10:15 UTC, aminedhobb requested changes
Merci pour cette PR @qblanc, c'est cool que t'aies pris des initiatives de design je trouve aussi que ça rend bien mieux bien joué 👏 !

Je t'ai laissé quelques commentaires tu me diras ce que tu en penses. 

Aussi j'ai une remarque supplémentaire: 

* Avec ce design il n'est pas possible de réinviter une personne. Dans la maquette c'est possible de le faire depuis  la page `show`, mais du coup ça voudrait dire qu'un ne peut pas merge cette PR tant que #52 n'est pas fini parce que les départements ont besoin de cette option..

2021-10-12 10:15 UTC, aminedhobb commented on app/javascript/react/components/Applicant.jsx
> +          </td>
Tu prends pas en compte la configuration ici, c'est un choix volontaire ? 
On peut proposer par défaut la possibilité d'inviter par mail, mais si un département n'est vrmt pas intéressé on  pourrait peut-être le cacher en fonction de la configuration. Pour les Ardennes on aura pas le choix mais pour l'instant c'est discutable.

2021-10-12 10:15 UTC, aminedhobb commented on app/javascript/react/components/Applicant.jsx
> +                disabled={isLoading.sms_invitation}
Est-ce qu'on le mettrait pas aussi `disabled` si l'applicant n'est pas créé  **ou** Le téléphone n'est pas présent ?

2021-10-12 10:15 UTC, aminedhobb commented on app/javascript/react/components/Applicant.jsx
> +                disabled={isLoading.email_invitation}
Pareil ici est-ce qu'on le mettrait pas aussi `disabled` si l'applicant n'est pas créé  **ou** l'email n'est pas présent ?

2021-10-12 10:15 UTC, aminedhobb commented on app/views/static_pages/welcome.html.erb
> +              <div class="card-body card-welcome-body white">
Ça rend mieux good call 👍

2021-10-12 10:15 UTC, aminedhobb commented on app/views/applicants/index.html.erb
>          <% end %>
Ce bouton a une couleur bizarre quand on passe la souris dessus.

2021-10-12 10:15 UTC, aminedhobb commented on app/javascript/react/pages/ApplicantsUpload.jsx
> +            pendingMessage="Récupération des informations, merci de patienter"
C'est un détail mais le pending message se retrouve du coup excentré, ce serait peut-être bien de le centrer si possible. WDYT?

2021-11-02 14:04 UTC, aminedhobb reviewed
Merci @qblanc pour les changements 🙇 ! 
Et bravo je viens de tester c'est vachement plus beau 👏 . 

Par contre c'est bien toi qui m'avait dit que ça n'avait aucun sens de mettre les filtres et le bouton "intervention nécessaire" sur des côtés différents 😄 ? Après ça me va de laisser comme ça je trouve que ça rend plutôt bien.

Par contre je suis toujours pas fan des boutons, surtout que tu fais ce que je t'ai proposé pour les boutons avec un background blanc (comme "Rechercher") !

2021-11-02 23:27 UTC, qblanc commented
J'ai fait les changements demandés. Pour la dernière demande, c'est à dire retirer la méthode `as_json` de `applicant.rb` pour récupérer plutôt les invitations directement dans le `applicants_controller`, je me demande si c'est une bonne idée car cela impose des `.filter` au client qui peuvent devenir très nombreux en cas de gros fichiers. 

Mais peut-être que je n'adopte pas la bonne approche, ou que les filters sont vraiment peu gourmands en ressources (mais bon c'est une méthode récursive donc ce n'est jamais idéal il me semble ; est-ce que ça vaut le coup d'imposer ça aux clients des agents, qui auront potentiellement des ordis bien pourris, pour économiser quelques appels à la base de donnée ?)

2021-11-03 10:50 UTC, aminedhobb commented
> J'ai fait les changements demandés. Pour la dernière demande, c'est à dire retirer la méthode `as_json` de `applicant.rb` pour récupérer plutôt les invitations directement dans le `applicants_controller`, je me demande si c'est une bonne idée car cela impose des `.filter` au client qui peuvent devenir très nombreux en cas de gros fichiers.
> 
> Mais peut-être que je n'adopte pas la bonne approche, ou que les filters sont vraiment peu gourmands en ressources (mais bon c'est une méthode récursive donc ce n'est jamais idéal il me semble ; est-ce que ça vaut le coup d'imposer ça aux clients des agents, qui auront potentiellement des ordis bien pourris, pour économiser quelques appels à la base de donnée ?)

Tu as raison @qblanc au temps pour moi, je pensais qu'on renvoyait un applicant et ses invitations mais là répondre avec tous les applicants et toutes les invits associées c'est pas ouf effectivement (en terme de ressource par contre je pense pas que ça ait un impact significatif). Ok pour envoyer pour chaque applicant les invitations associées 👍

2021-11-08 10:58 UTC, aminedhobb approved these changes
👍

2021-11-10 10:08 UTC, aminedhobb commented
Mergé avec #116

2021-11-10 10:08 UTC, closed without merging