Feat(template) Nouveau template atelier enfants et ados
betagouv/rdv-insertion pull request #966
Opened 2023-04-04 14:52 UTC by Holist

Close https://github.com/betagouv/rdv-insertion/issues/929

Ajout du template spécifique à la catégorie de motif `atelier_enfants_ados`
J'ai également renseigné quelques motif_category manquantes dans le concern `Sortable` et le yml des motifs

2023-04-04 15:57 UTC, Holist commented
Est ce que les méthodes et les vues pour les reminders dans views/mailers/invitation_mailer sont nécessaires pour tout les nouveaux template  ?
En l'occurence je pense aussi au short_template qui a été merge mais pour lequel je n'ai pas créer de vue ou de methode pour les emails et sms de relance !

2023-04-04 16:05 UTC, qblanc approved these changes
Merci ! 🙏 J'ai laissé une ou deux suggestions mais rien de bloquant

2023-04-04 16:05 UTC, qblanc commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +      rdv_title: "atelier enfants et ados",
est-ce qu'on veut mettre "enfants et ados" dans le `rdv_title` ? En tant qu'enfant je trouve ça un peu bizarre de recevoir `Tu es invité à un atelier enfants et ados`. Soit juste `Tu es invité à un atelier`, soit quelque chose comme `Tu es invité à un atelier destiné aux jeunes de ton âge`. WDYT ?

2023-04-04 16:05 UTC, qblanc commented on spec/services/invitations/send_sms_spec.rb
> +      first_name: "john", last_name: "doe", title: "monsieur"
Pourquoi ce changement ? Pour vérifier que ça capitalize bien ?

2023-04-04 16:13 UTC, aminedhobb commented on app/mailers/invitation_mailer.rb
> +  ### Spécifique à un contexte
Par ce commentaire tu veux dire qu'il n'est utilisé que sur une catégorie de motif ? 
Si oui tu peux mettre ça c'est plus clair.
On est sûr qu'il sera pas utilisé pour d'autres catégories ?

2023-04-04 16:13 UTC, aminedhobb commented on app/services/concerns/invitations/sms_content.rb
> +    ### Spécifique à un contexte
same here

2023-04-04 16:13 UTC, aminedhobb commented on app/services/concerns/invitations/sms_content.rb
> +      "#{applicant},\n Tu es invité à participer à un atelier organisé par le département. " \
```suggestion
      "#{applicant},\nTu es invité à participer à un atelier organisé par le département. " \
```

2023-04-04 16:16 UTC, aminedhobb commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +    template = Template.create(
J'aurais tendance à utiliser des `!` après les `create` ici, et mettre une méthode `down` qui détruit cette catégorie et ce template si on veut rollback

2023-04-04 16:18 UTC, aminedhobb commented on app/models/concerns/motif_category/sortable.rb
> +    atelier_enfants_ados
si ça rentre pas dans le parcours RSA  dans une position spécifique je ne  pense pas qu'il y ait besoin de préciser sa position ici

2023-04-04 16:27 UTC, aminedhobb commented
> Est ce que les méthodes et les vues pour les reminders dans views/mailers/invitation_mailer sont nécessaires pour tout les nouveaux template ? En l'occurence je pense aussi au short_template qui a été merge mais pour lequel je n'ai pas créé de vue ou de methode pour les emails et sms de relance !

A partir du moment où on veut des rappels sur des catégories utilisant ces templates oui il faut les rajouter. 
Pour info, le fait que des rappels ou non soit lancés est déterminé par l'attribut `participation_optional` d'une catégorie de motif (cet attribut est amené à changer de nom: https://github.com/betagouv/rdv-insertion/issues/937)

2023-04-05 09:09 UTC, Holist commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +      rdv_title: "atelier enfants et ados",
Dans ce template le `rdv_title` est utilisé uniquement pour le titre de l'email : "Atelier enfants ados"
Dans le corps du message ca donne : 
Tu es invité à participer à un atelier organisé par le département. etc...

2023-04-05 09:10 UTC, Holist commented on app/mailers/invitation_mailer.rb
> +  ### Spécifique à un contexte
Alors effectivement on sait jamais, ca pourrait être utilisable dans d'autres contexte vu que le corps du message n'est pas trés spécifique (hormis le tutoiement).
J'enléve le commentaire

2023-04-05 09:13 UTC, Holist commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +    template = Template.create(
yes merci :)

2023-04-05 09:25 UTC, qblanc commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +      rdv_title: "atelier enfants et ados",
Je trouve quand même ça bizarre dans l'objet du mail :)
Pour l'objet on pourrait mettre `Invitation à un atelier` ? L'un des trucs que je trouve gênant c'est que si tu es un ado et que tu reçois un truc destiné aux "enfants/ados", ça va pas te donner envie d'y aller à mon avis (tu as pas envie d'être avec des "gamins")

2023-04-05 09:43 UTC, Holist commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +      rdv_title: "atelier enfants et ados",
C'est probable effectivement :)
J'aime bien la formulation `atelier destiné aux jeunes de ton âge`
Je pars sur : "Invitation à atelier destiné aux jeunes de ton âge" en titre de mail.
On pourra toujours le changer si on le souhaite.

2023-04-05 09:52 UTC, qblanc commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +      rdv_title: "atelier enfants et ados",
ça fera `Invitation à atelier destiné aux jeunes de ton âge` ou `Invitation à un atelier destiné aux jeunes de ton âge` ? La deuxième serait mieux imo :)

2023-04-05 10:04 UTC, Holist commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +      rdv_title: "atelier enfants et ados",
lol oui. C'est le cas. Mauvais copier coller

2023-04-05 13:31 UTC, Holist commented
> 

Très bien, j'ai ajouté les reminders pour ce nouveau template et pour le template short qui n'en avait pas.
Petit question. Le short template a été utilisé pour la catégorie de motif de suivi psychologue et les parametres 
`number_of_days_to_accept_invitation` et `number_of_days_before_action_required` sont set à 365 jours.
Cela signifie que dans ce cas ils recevront un rappel 3 jours après l'invitation puis plus de rappel ?
Il y a bien qu'un seul rappel sms/mail par invitation ?

2023-04-05 13:33 UTC, Holist commented
> 



> Pourquoi est-ce qu'on a pas un template sur le courrier aussi ?

Je l'ai ajouté.

2023-04-05 16:39 UTC, aminedhobb reviewed
Merci @Holist pour les changements ! 

On a donc des catégories utilisant le template enfant/ados qui auront potentiellement des rappels ? 

> Cela signifie que dans ce cas ils recevront un rappel 3 jours après l'invitation puis plus de rappel ?

Le rappel est envoyé si `participation_optional` est `false` au niveau de la catégorie de motif (le nom est à changer encore une fois: https://github.com/betagouv/rdv-insertion/issues/937). 
Ce qui n'est pas le cas pour les rdv psychologues, donc il n'y aura pas de rappel pour cette catégorie.
Cependant il est probable que le template `short` soit réutilisé pour une autre catégorie, qui nécessitera potentiellement des rappels, donc je ne pense pas que ce soit une mauvaise chose de le rajouter.

> Il y a bien qu'un seul rappel sms/mail par invitation ?

Oui

2023-04-05 16:39 UTC, aminedhobb commented on app/views/mailers/invitation_mailer/atelier_enfants_ados_invitation_reminder.html.erb
> +<p>Tu as reçu un premier mail il y a 3 jours t'invitant à un <%= @rdv_title %>.</p>
PI  la première PR qui sera mergée entre celle-ci et celle de @qblanc (#973 ) devra changer changer le `3` ici

2023-04-05 16:39 UTC, aminedhobb commented on app/mailers/invitation_mailer.rb
> +  def atelier_enfants_ados_invitation_reminder
Du coup on aura potentiellement des catégories utilisant ce template qui auront des rappels c'est ça ?

2023-04-05 16:39 UTC, aminedhobb commented on db/migrate/20230404134841_add_atelier_enfants_ados_template.rb
> +    Template.find_by(rdv_title: "atelier destiné aux jeunes de ton âge", model: "atelier_enfants_ados").destroy
```suggestion
    MotifCategory.find_by(short_name: "atelier_enfants_ados").destroy!
    Template.find_by(rdv_title: "atelier destiné aux jeunes de ton âge", model: "atelier_enfants_ados").destroy!
```

2023-04-06 08:43 UTC, Holist commented on app/mailers/invitation_mailer.rb
> +  def atelier_enfants_ados_invitation_reminder
Effectivement ça pourrait arriver.

2023-04-06 09:20 UTC, qblanc requested changes
des micro changements et ce sera bon pour moi :)

2023-04-06 09:20 UTC, qblanc commented on app/services/concerns/invitations/sms_content.rb
> +        "Si tu es intéressé pour participer, tu n’auras qu’à cliquer et t’inscrire en ligne avec le lien suivant: " \
ce serait pas mal de `conjugate` les participes passés je pense

2023-04-06 09:20 UTC, qblanc commented on app/views/letters/invitations/atelier_enfants_ados.html.erb
> +  <p><%= sender_name.capitalize %> a mis en place <span class="bold-blue">une plateforme te permettant de t'inscrire.</span></p>
pareil

2023-04-06 09:20 UTC, qblanc commented on app/views/mailers/invitation_mailer/atelier_enfants_ados_invitation.html.erb
> +<p><span class="font-weight-bold">Si tu es intéressé pour participer, tu n’auras qu’à cliquer ci-dessous et t’inscrire en ligne.</p>
pareil

2023-04-06 09:20 UTC, qblanc commented on db/schema.rb
> +    t.text "custom_sentence"
je ne vois pas où cet ajout est utilisé (peut-être pas le scope de cette PR)

2023-04-06 09:27 UTC, Holist commented on db/schema.rb
> +    t.text "custom_sentence"
effectivement, j'ai oublié de revert une migration en changeant de branche, j'enleve ca

2023-04-06 09:49 UTC, Holist commented on app/services/concerns/invitations/sms_content.rb
> +        "Si tu es intéressé pour participer, tu n’auras qu’à cliquer et t’inscrire en ligne avec le lien suivant: " \
Done, j'ai pas encore pris le reflexe d'utiliser cette methode. Merci

2023-04-06 13:16 UTC, merged